"use client";
import { useInterfaceCopy } from "@/lib/i18n";

import { useActionState, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { saveLessonContent, publishLesson, unpublishLesson } from "../actions";

type Hint = { id: string; slug: string; title: { en: string; sr: string }; body: { en: string; sr: string } };
type Validator = { type: "transform_range"; objectId: string; field?: "position" | "rotation" | "scale"; position: [number, number, number]; axes: ("x" | "y" | "z")[]; toleranceMm: number } | { type: "required_object"; objectId: string; visible?: boolean; selected?: boolean; minOpacity?: number; maxOpacity?: number; minGeometryRevision?: number } | { type: "required_step"; message?: { en: string; sr: string } } | { type: "margin_complete"; objectId: string } | { type: "analysis_target"; kind: "contact" | "thickness" | "undercut" | "deviation"; objectIds: string[]; minValue?: number; maxValue?: number } | { type: "denture_setup"; check: "model_analysis" | "tooth_setup" | "chain_mode" | "boundary" | "base" | "complete_case"; arch?: "upper" | "lower"; segment?: "anterior" | "posterior" } | { type: "restorative_setup"; check: "bridge_design" | "single_unit_design" | "veneer_position"; restorationType?: "crown" | "bridge" | "inlay" | "onlay" | "veneer" } | { type: "implant_check"; check: "fixture" | "depth" | "axis" | "distance" | "relationships"; objectId?: string; targetMm?: number; tolerance?: number };
type CaseSetup = { source: "shared-demo-workspace" | "lesson-assets" | "crown-case" | "denture-case" | "restorative-case" | "partial-denture-case" | "bite-splint-case" | "digital-model-case" | "articulator-case" | "implant-case"; restorationType?: "crown" | "bridge" | "inlay" | "onlay" | "veneer"; objectMappings: { runtimeObjectId: string; semanticRole: string; editable: boolean }[] };
type Step = { id: string; slug: string; title: { en: string; sr: string }; instructions: { en: string; sr: string }; theory: { en: string; sr: string }; targets: string[]; tools: string[]; referenceModes: string[]; referenceObjectId: string; referencePosition: [number, number, number]; exampleMode: string; exampleLabel: { en: string; sr: string }; required: boolean; hints: Hint[]; validator: Validator | null };
type EditorValue = { id?: string; updatedAt?: string; moduleId?: string; moduleSlug: string; moduleTitle: { en: string; sr: string }; moduleSummary: { en: string; sr: string }; slug: string; difficulty: "foundation" | "beginner" | "intermediate" | "advanced"; title: { en: string; sr: string }; summary: { en: string; sr: string }; goal: { en: string; sr: string }; minutes: number; assets: { assetId: string; role: string; isReference: boolean }[]; caseSetup: CaseSetup; steps: Step[] };

const tools = ["select", "move", "rotate", "scale", "sculpt", "mesh_edit", "analysis", "camera", "scene"];
const objects = ["demo-crown", "demo-prepared-tooth", "demo-reference", "demo-synthetic-scan"];
const modes = ["off", "outline", "transparent", "full"];
const makeStep = (order: number): Step => ({ id: crypto.randomUUID(), slug: `step_${order}`, title: { en: "", sr: "" }, instructions: { en: "", sr: "" }, theory: { en: "", sr: "" }, targets: ["demo-crown"], tools: ["select", "move", "camera"], referenceModes: ["off", "outline", "transparent", "full"], referenceObjectId: "demo-reference", referencePosition: [0, 0, 0], exampleMode: "outline", exampleLabel: { en: "Target for this exercise", sr: "Cilj ove vežbe" }, required: true, hints: [], validator: { type: "transform_range", objectId: "demo-crown", position: [0, 0, 0], axes: ["x"], toleranceMm: 0.5 } });
const initialValue = (): EditorValue => ({ moduleSlug: "new_module", moduleTitle: { en: "", sr: "" }, moduleSummary: { en: "", sr: "" }, slug: "new_lesson", difficulty: "foundation", title: { en: "", sr: "" }, summary: { en: "", sr: "" }, goal: { en: "", sr: "" }, minutes: 5, assets: [], caseSetup: { source: "shared-demo-workspace", objectMappings: [] }, steps: [makeStep(1)] });

function Field({ label, value, onChange, textarea = false, required = false }: { label: string; value: string; onChange: (value: string) => void; textarea?: boolean; required?: boolean }) {
  const common = { value, required, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(event.target.value), className: "mt-1 block w-full rounded-md border border-input bg-background px-2.5 py-2 text-xs text-foreground" };
  return <label className="block text-[10px] font-medium text-muted-foreground">{label}{textarea ? <textarea {...common} rows={3} /> : <input {...common} />}</label>;
}

export function LessonEditor({ initial, modules, tools: availableTools, assets: availableAssets, status }: { initial?: EditorValue; modules: { id: string; slug: string; title_en: string; title_sr: string }[]; tools: { id: string; label_en: string; label_sr: string }[]; assets: { id: string; name: string; role: string }[]; status?: string }) {
  const tx = useInterfaceCopy();
  const router = useRouter();
  const [value, setValue] = useState<EditorValue>(initial ?? initialValue());
  const [dirty, setDirty] = useState(false);
  const editVersion = useRef(0);
  const saveContent = useCallback(async (previous: { error?: string; id?: string; savedAt?: number }, formData: FormData) => {
    const submittedVersion = editVersion.current;
    const result = await saveLessonContent(previous, formData);
    if (result.savedAt && submittedVersion === editVersion.current) setDirty(false);
    return result;
  }, []);
  const [saveState, saveAction] = useActionState<{ error?: string; id?: string; savedAt?: number }, FormData>(saveContent, {});
  const [publishState, publishAction] = useActionState(publishLesson, {});
  const [unpublishState, unpublishAction] = useActionState(unpublishLesson, {});
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  useEffect(() => { if (saveState.id && saveState.savedAt) { router.push(`/admin/lessons/${saveState.id}`); router.refresh(); } }, [saveState.id, saveState.savedAt, router]);
  const updateLesson = <K extends keyof EditorValue>(key: K, next: EditorValue[K]) => { setDirty(true); setValue((current) => ({ ...current, [key]: next })); };
  const updateStep = (index: number, updater: (step: Step) => Step) => updateLesson("steps", value.steps.map((step, current) => current === index ? updater(step) : step));
  const addHint = (index: number) => updateStep(index, (step) => ({ ...step, hints: [...step.hints, { id: crypto.randomUUID(), slug: `hint_${step.hints.length + 1}`, title: { en: "", sr: "" }, body: { en: "", sr: "" } }] }));
  const moveStep = (index: number, by: number) => { const next = [...value.steps]; const destination = index + by; if (destination < 0 || destination >= next.length) return; [next[index], next[destination]] = [next[destination], next[index]]; updateLesson("steps", next); };
  return <div>
    <form action={saveAction} onChange={() => { editVersion.current += 1; setDirty(true); }} onSubmit={(event) => { const form = event.currentTarget; const hidden = form.elements.namedItem("content") as HTMLInputElement; hidden.value = JSON.stringify(value); }}>
      <input type="hidden" name="content" />
      <section className="app-surface grid gap-4 p-5 md:grid-cols-2">
        <h2 className="text-sm font-semibold md:col-span-2">{tx("Lesson and module")}</h2>
        <label className="block text-[10px] font-medium text-muted-foreground">{tx("Module")}<select value={value.moduleId ?? "new"} onChange={(event) => { const selected = modules.find((item) => item.id === event.target.value); setDirty(true); setValue((current) => ({ ...current, moduleId: selected?.id, moduleSlug: selected?.slug ?? current.moduleSlug, moduleTitle: selected ? { en: selected.title_en, sr: selected.title_sr } : current.moduleTitle })); }} className="mt-1 block h-9 w-full rounded-md border border-input bg-background px-2 text-xs"><option value="new">{tx("Create a new module")}</option>{modules.map((module) => <option key={module.id} value={module.id}>{module.title_en} / {module.title_sr}</option>)}</select></label>
        {!value.moduleId && <><Field label={tx("Module slug")} value={value.moduleSlug} onChange={(v) => updateLesson("moduleSlug", v)} required /><Field label={tx("Module title · English")} value={value.moduleTitle.en} onChange={(v) => updateLesson("moduleTitle", { ...value.moduleTitle, en: v })} /><Field label={tx("Module title · Serbian")} value={value.moduleTitle.sr} onChange={(v) => updateLesson("moduleTitle", { ...value.moduleTitle, sr: v })} /><Field label={tx("Module summary · English")} value={value.moduleSummary.en} onChange={(v) => updateLesson("moduleSummary", { ...value.moduleSummary, en: v })} /><Field label={tx("Module summary · Serbian")} value={value.moduleSummary.sr} onChange={(v) => updateLesson("moduleSummary", { ...value.moduleSummary, sr: v })} /></>}
        <Field label={tx("Lesson slug")} value={value.slug} onChange={(v) => updateLesson("slug", v)} required />
        <label className="block text-[10px] font-medium text-muted-foreground">{tx("Difficulty")}<select value={value.difficulty} onChange={(event) => updateLesson("difficulty", event.target.value as EditorValue["difficulty"])} className="mt-1 block h-9 w-full rounded-md border border-input bg-background px-2 text-xs">{["foundation", "beginner", "intermediate", "advanced"].map((item) => <option key={item}>{item}</option>)}</select></label>
        <Field label={tx("Title · English")} value={value.title.en} onChange={(v) => updateLesson("title", { ...value.title, en: v })} required />
        <Field label={tx("Title · Serbian")} value={value.title.sr} onChange={(v) => updateLesson("title", { ...value.title, sr: v })} required />
        <Field label={tx("Description · English")} value={value.summary.en} onChange={(v) => updateLesson("summary", { ...value.summary, en: v })} textarea />
        <Field label={tx("Description · Serbian")} value={value.summary.sr} onChange={(v) => updateLesson("summary", { ...value.summary, sr: v })} textarea />
        <Field label={tx("Learning objective · English")} value={value.goal.en} onChange={(v) => updateLesson("goal", { ...value.goal, en: v })} textarea required />
        <Field label={tx("Learning objective · Serbian")} value={value.goal.sr} onChange={(v) => updateLesson("goal", { ...value.goal, sr: v })} textarea required />
        <label className="block text-[10px] font-medium text-muted-foreground">{tx("Estimated minutes")}<input type="number" min="1" max="600" value={value.minutes} onChange={(event) => updateLesson("minutes", Number(event.target.value))} className="mt-1 block h-9 w-full rounded-md border border-input bg-background px-2 text-xs" /></label>
        <div className="flex items-center text-[10px] text-muted-foreground">{tx("Status:")} <strong className="ml-1 text-foreground">{status ?? "draft"}</strong></div>
        <div className="grid gap-2 rounded-md border border-border p-3 md:col-span-2 md:grid-cols-2"><div><p className="text-xs font-semibold">{tx("Case initialization")}</p><p className="mt-1 text-[10px] text-muted-foreground">{tx("Choose the shared CAD runtime setup used when the learner starts this lesson.")}</p></div><label className="text-[10px] text-muted-foreground">{tx("Source")}<select value={value.caseSetup.source} onChange={(event) => updateLesson("caseSetup", { ...value.caseSetup, source: event.target.value as CaseSetup["source"] })} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs"><option value="shared-demo-workspace">{tx("Shared demo workspace")}</option><option value="lesson-assets">{tx("Lesson assets")}</option><option value="crown-case">{tx("Synthetic Crown case")}</option><option value="denture-case">{tx("Synthetic Complete Denture case")}</option><option value="restorative-case">{tx("Synthetic restorative case")}</option><option value="partial-denture-case">{tx("Synthetic Partial Denture case")}</option><option value="bite-splint-case">{tx("Synthetic Bite Splint case")}</option><option value="digital-model-case">{tx("Synthetic Digital Model case")}</option><option value="articulator-case">{tx("Synthetic Virtual Articulator case")}</option><option value="implant-case">{tx("Synthetic Implant Practice case")}</option></select></label>{value.caseSetup.source === "restorative-case" && <label className="text-[10px] text-muted-foreground">{tx("Restoration type")}<select value={value.caseSetup.restorationType ?? "bridge"} onChange={(event) => updateLesson("caseSetup", { ...value.caseSetup, restorationType: event.target.value as CaseSetup["restorationType"] })} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs">{["bridge", "inlay", "onlay", "veneer", "crown"].map((type) => <option key={type} value={type}>{type[0].toUpperCase() + type.slice(1)}</option>)}</select></label>}</div>
      </section>

      <section className="app-surface mt-4 p-4"><h2 className="text-xs font-semibold">{tx("Referenced model and reference assets")}</h2><p className="mt-1 text-[10px] text-muted-foreground">{tx("Only ready registry assets are listed. Published lesson assets also require license/provenance metadata.")}</p><div className="mt-2 space-y-1">{availableAssets.map((asset) => { const selected = value.assets.find((item) => item.assetId === asset.id); return <label key={asset.id} className="flex items-center gap-2 rounded border border-border px-2 py-1.5 text-[10px]"><input type="checkbox" checked={Boolean(selected)} onChange={(event) => updateLesson("assets", event.target.checked ? [...value.assets, { assetId: asset.id, role: asset.role, isReference: false }] : value.assets.filter((item) => item.assetId !== asset.id))} /><span className="min-w-0 flex-1 truncate">{asset.name} · {asset.role}</span>{selected && <span className="flex items-center gap-1"><input aria-label={`Use ${asset.name} as a reference`} type="checkbox" checked={selected.isReference} onChange={(event) => updateLesson("assets", value.assets.map((item) => item.assetId === asset.id ? { ...item, isReference: event.target.checked } : item))} />{tx("Reference")}</span>}</label>; })}{availableAssets.length === 0 && <p className="text-[10px] text-muted-foreground">{tx("Upload and license a platform model in Admin → Platform assets first.")}</p>}</div></section>

      <div className="mt-5 flex items-center justify-between"><div><h2 className="text-lg font-medium">{tx("Ordered lesson steps")}</h2><p className="text-[10px] text-muted-foreground">{tx("Step order is saved sequentially. Only runtime supported tools and validators are available.")}</p></div><Button type="button" variant="outline" size="sm" onClick={() => updateLesson("steps", [...value.steps, makeStep(value.steps.length + 1)])}><Plus className="size-3.5" /> {tx("Add step")}</Button></div>
      <div className="mt-3 space-y-3">{value.steps.map((step, index) => <section key={step.id} className="app-surface space-y-4 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Step {index + 1}</h3><div className="flex gap-1"><Button type="button" aria-label={tx("Move step up")} size="icon" variant="ghost" disabled={index === 0} onClick={() => moveStep(index, -1)}><ArrowUp className="size-4" /></Button><Button type="button" aria-label={tx("Move step down")} size="icon" variant="ghost" disabled={index === value.steps.length - 1} onClick={() => moveStep(index, 1)}><ArrowDown className="size-4" /></Button><Button type="button" aria-label={tx("Delete step")} size="icon" variant="ghost" disabled={value.steps.length === 1} onClick={() => updateLesson("steps", value.steps.filter((_, i) => i !== index))}><Trash2 className="size-4 text-destructive" /></Button></div></div>
        <div className="grid gap-3 md:grid-cols-2"><Field label={tx("Stable step key")} value={step.slug} onChange={(v) => updateStep(index, (s) => ({ ...s, slug: v }))} required /><label className="flex items-center gap-2 text-[10px] text-muted-foreground"><input type="checkbox" checked={step.required} onChange={(event) => updateStep(index, (s) => ({ ...s, required: event.target.checked }))} />{tx("Required step")}</label><Field label={tx("Title · English")} value={step.title.en} onChange={(v) => updateStep(index, (s) => ({ ...s, title: { ...s.title, en: v } }))} /><Field label={tx("Title · Serbian")} value={step.title.sr} onChange={(v) => updateStep(index, (s) => ({ ...s, title: { ...s.title, sr: v } }))} /><Field label={tx("Instruction · English")} value={step.instructions.en} onChange={(v) => updateStep(index, (s) => ({ ...s, instructions: { ...s.instructions, en: v } }))} textarea /><Field label={tx("Instruction · Serbian")} value={step.instructions.sr} onChange={(v) => updateStep(index, (s) => ({ ...s, instructions: { ...s.instructions, sr: v } }))} textarea /><Field label={tx("Short theory / context · English")} value={step.theory.en} onChange={(v) => updateStep(index, (s) => ({ ...s, theory: { ...s.theory, en: v } }))} textarea /><Field label={tx("Short theory / context · Serbian")} value={step.theory.sr} onChange={(v) => updateStep(index, (s) => ({ ...s, theory: { ...s.theory, sr: v } }))} textarea /></div>
        <fieldset><legend className="text-[10px] font-semibold">{tx("Allowed tools")}</legend><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1">{availableTools.filter((tool) => tools.includes(tool.id)).map((tool) => <label key={tool.id} className="flex items-center gap-1 text-[10px] text-muted-foreground"><input type="checkbox" checked={step.tools.includes(tool.id)} onChange={(event) => updateStep(index, (s) => ({ ...s, tools: event.target.checked ? [...s.tools, tool.id] : s.tools.filter((id) => id !== tool.id) }))} />{tool.label_en}</label>)}</div></fieldset>
        <fieldset><legend className="text-[10px] font-semibold">{tx("Reference modes")}</legend><div className="mt-1 flex gap-3">{modes.map((mode) => <label key={mode} className="flex items-center gap-1 text-[10px] capitalize text-muted-foreground"><input type="checkbox" checked={step.referenceModes.includes(mode)} onChange={(event) => updateStep(index, (s) => ({ ...s, referenceModes: event.target.checked ? [...s.referenceModes, mode] : s.referenceModes.filter((item) => item !== mode) }))} />{mode}</label>)}</div><label className="mt-2 block max-w-sm text-[10px] text-muted-foreground">{tx("Reference object")}<select value={step.referenceObjectId} onChange={(event) => updateStep(index, (s) => ({ ...s, referenceObjectId: event.target.value }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs"><option value="">{tx("Off")}</option>{objects.map((object) => <option key={object}>{object}</option>)}{value.assets.map((asset) => <option key={asset.assetId} value={asset.assetId}>{availableAssets.find((item) => item.id === asset.assetId)?.name ?? asset.assetId}{asset.isReference ? " · reference" : ""}</option>)}</select></label></fieldset>
        <div className="grid gap-2 md:grid-cols-3"><label className="text-[10px] text-muted-foreground">{tx("Show example")}<select value={step.exampleMode} onChange={(event) => updateStep(index, (s) => ({ ...s, exampleMode: event.target.value }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs">{modes.map((mode) => <option key={mode}>{mode}</option>)}</select></label><Field label={tx("Example label · English")} value={step.exampleLabel.en} onChange={(v) => updateStep(index, (s) => ({ ...s, exampleLabel: { ...s.exampleLabel, en: v } }))} /><Field label={tx("Example label · Serbian")} value={step.exampleLabel.sr} onChange={(v) => updateStep(index, (s) => ({ ...s, exampleLabel: { ...s.exampleLabel, sr: v } }))} /></div>
        <label className="block max-w-sm text-[10px] font-medium text-muted-foreground">{tx("Target object IDs")}<select multiple value={step.targets} onChange={(event) => updateStep(index, (s) => ({ ...s, targets: Array.from(event.target.selectedOptions, (option) => option.value) }))} className="mt-1 block h-20 w-full rounded-md border border-input bg-background p-2 text-xs">{objects.map((object) => <option key={object}>{object}</option>)}{value.assets.map((asset) => <option key={asset.assetId} value={asset.assetId}>{availableAssets.find((item) => item.id === asset.assetId)?.name ?? asset.assetId}{asset.isReference ? " · reference" : ""}</option>)}</select></label>
        <details className="rounded-md border border-border p-3" open><summary className="cursor-pointer text-xs font-semibold">{tx("Design Check · registered validator")}</summary><p className="mt-1 text-[10px] text-muted-foreground">{tx("Numeric targets are exercise targets. Acknowledgment is appropriate for actions the runtime cannot measure reliably, such as camera navigation or taking a measurement.")}</p>
          <label className="mt-2 block max-w-sm text-[10px] text-muted-foreground">{tx("Check type")}<select value={step.validator?.type ?? "required_step"} onChange={(event) => { const type = event.target.value; const validator: Validator = type === "transform_range" ? { type, objectId: "crown26-restoration", field: "position", position: [0, 0, 0], axes: ["x", "y", "z"], toleranceMm: 0.5 } : type === "required_object" ? { type, objectId: "crown26-reference", visible: true } : type === "margin_complete" ? { type, objectId: "crown26-preparation" } : type === "analysis_target" ? { type, kind: "contact", objectIds: ["crown26-restoration", "crown26-adjacent-25"] } : type === "denture_setup" ? { type, check: "model_analysis" } : type === "implant_check" ? { type, check: "fixture" } : { type: "required_step" }; updateStep(index, (s) => ({ ...s, validator })); }} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs"><option value="required_step">{tx("Learner acknowledgment")}</option><option value="required_object">{tx("Scene object state")}</option><option value="transform_range">{tx("Transform target")}</option><option value="margin_complete">{tx("Margin Line state")}</option><option value="analysis_target">{tx("Current analysis and exercise target")}</option><option value="denture_setup">{tx("Complete Denture setup check")}</option><option value="implant_check">{tx("Implant exercise check")}</option></select></label>
          {step.validator?.type === "transform_range" && <div className="mt-3 grid gap-2 sm:grid-cols-4"><label className="text-[9px] text-muted-foreground">{tx("Object ID")}<input value={step.validator.objectId} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "transform_range" ? { ...s.validator, objectId: event.target.value } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs" /></label><label className="text-[9px] text-muted-foreground">{tx("Transform field")}<select value={step.validator.field ?? "position"} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "transform_range" ? { ...s.validator, field: event.target.value as "position" | "rotation" | "scale" } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs"><option value="position">{tx("Position (mm)")}</option><option value="rotation">{tx("Rotation (radians)")}</option><option value="scale">{tx("Scale (factor)")}</option></select></label>{([0, 1, 2] as const).map((axis) => <label key={axis} className="text-[9px] text-muted-foreground">Target {(["X", "Y", "Z"] as const)[axis]}<input type="number" step="0.01" value={(step.validator as Extract<Validator, { type: "transform_range" }>).position[axis]} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "transform_range" ? { ...s.validator, position: s.validator.position.map((item, i) => i === axis ? Number(event.target.value) : item) as [number, number, number] } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs" /></label>)}<label className="text-[9px] text-muted-foreground">{tx("Checked axes")}<input value={step.validator.axes.join(",")} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "transform_range" ? { ...s.validator, axes: event.target.value.split(",").map((axis) => axis.trim()).filter((axis): axis is "x" | "y" | "z" => ["x", "y", "z"].includes(axis)) } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs" /></label><label className="text-[9px] text-muted-foreground">{tx("Tolerance")}<input type="number" min="0.01" step="0.01" value={step.validator.toleranceMm} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "transform_range" ? { ...s.validator, toleranceMm: Number(event.target.value) } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs" /></label></div>}
          {step.validator?.type === "required_object" && <div className="mt-3 grid gap-2 sm:grid-cols-3"><Field label={tx("Object ID")} value={step.validator.objectId} onChange={(v) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "required_object" ? { ...s.validator, objectId: v } : s.validator }))} /><label className="text-[9px] text-muted-foreground">{tx("Visibility")}<select value={step.validator.visible === undefined ? "any" : step.validator.visible ? "visible" : "hidden"} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "required_object" ? { ...s.validator, visible: event.target.value === "any" ? undefined : event.target.value === "visible" } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs"><option value="any">{tx("Any")}</option><option value="visible">{tx("Visible")}</option><option value="hidden">{tx("Hidden")}</option></select></label><label className="flex items-center gap-2 pt-4 text-[10px] text-muted-foreground"><input type="checkbox" checked={Boolean(step.validator.selected)} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "required_object" ? { ...s.validator, selected: event.target.checked || undefined } : s.validator }))} />{tx("Must be active selection")}</label><label className="text-[9px] text-muted-foreground">{tx("Minimum opacity")}<input type="number" min="0.15" max="1" step="0.05" value={step.validator.minOpacity ?? ""} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "required_object" ? { ...s.validator, minOpacity: event.target.value ? Number(event.target.value) : undefined } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs" /></label><label className="text-[9px] text-muted-foreground">{tx("Minimum mesh revision")}<input type="number" min="0" step="1" value={step.validator.minGeometryRevision ?? ""} onChange={(event) => updateStep(index, (s) => ({ ...s, validator: s.validator?.type === "required_object" ? { ...s.validator, minGeometryRevision: event.target.value ? Number(event.target.value) : undefined } : s.validator }))} className="mt-1 block h-8 w-full rounded border border-input bg-background px-2 text-xs" /></label></div>}
          {step.validator?.type === "required_step" && <p className="mt-2 text-[10px] text-muted-foreground">{tx("Design Check records that the learner has performed the instruction. The runtime does not infer success from camera movement or an unobservable inspection.")}</p>}
          {(step.validator?.type === "margin_complete" || step.validator?.type === "analysis_target" || step.validator?.type === "denture_setup" || step.validator?.type === "restorative_setup" || step.validator?.type === "implant_check") && <label className="mt-3 block text-[9px] text-muted-foreground">{tx("Validator configuration JSON")}<textarea aria-label={tx("Validator configuration JSON")} rows={4} value={JSON.stringify(step.validator, null, 2)} onChange={(event) => { try { const parsed = JSON.parse(event.target.value) as Validator; if (parsed.type === "margin_complete" || parsed.type === "analysis_target" || parsed.type === "denture_setup" || parsed.type === "restorative_setup" || parsed.type === "implant_check") updateStep(index, (s) => ({ ...s, validator: parsed })); } catch { setDirty(true); } }} className="mt-1 block w-full rounded border border-input bg-background p-2 font-mono text-[10px]" /></label>}
        </details>
        <div><div className="flex items-center justify-between"><h4 className="text-xs font-semibold">{tx("Progressive hints")}</h4><Button type="button" variant="outline" size="sm" onClick={() => addHint(index)}><Plus className="size-3" /> {tx("Add hint")}</Button></div><div className="mt-2 space-y-2">{step.hints.map((item, hintIndex) => <div key={item.id} className="grid gap-2 rounded border border-border p-2 md:grid-cols-2"><div className="flex justify-between text-[10px] font-semibold">{tx("Hint")} {hintIndex + 1}<Button type="button" size="icon" variant="ghost" aria-label={tx("Delete hint")} onClick={() => { if (window.confirm(tx("Delete this hint?"))) updateStep(index, (s) => ({ ...s, hints: s.hints.filter((hint) => hint.id !== item.id) })); }}><Trash2 className="size-3 text-destructive" /></Button></div><Field label={tx("Title · EN")} value={item.title.en} onChange={(v) => updateStep(index, (s) => ({ ...s, hints: s.hints.map((hint) => hint.id === item.id ? { ...hint, title: { ...hint.title, en: v } } : hint) }))} /><Field label={tx("Title · SR")} value={item.title.sr} onChange={(v) => updateStep(index, (s) => ({ ...s, hints: s.hints.map((hint) => hint.id === item.id ? { ...hint, title: { ...hint.title, sr: v } } : hint) }))} /><Field label={tx("Hint text · EN")} value={item.body.en} onChange={(v) => updateStep(index, (s) => ({ ...s, hints: s.hints.map((hint) => hint.id === item.id ? { ...hint, body: { ...hint.body, en: v } } : hint) }))} textarea /><Field label={tx("Hint text · SR")} value={item.body.sr} onChange={(v) => updateStep(index, (s) => ({ ...s, hints: s.hints.map((hint) => hint.id === item.id ? { ...hint, body: { ...hint.body, sr: v } } : hint) }))} textarea /></div>)}</div></div>
      </section>)}</div>
      <div className="sticky bottom-0 z-10 mt-5 flex flex-wrap items-center gap-2 border-t border-border bg-background/95 py-3 backdrop-blur"><Button type="submit" disabled={!dirty && Boolean(value.id)}>{tx("Save draft")}</Button><span className="text-[10px] text-muted-foreground">{dirty ? tx("Unsaved changes") : tx("Saved")}</span></div>
    </form>
    {(saveState.error || publishState.error || unpublishState.error) && <p role="alert" className="mt-3 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-xs text-destructive">{tx(saveState.error ?? publishState.error ?? unpublishState.error ?? "Unable to save this content.")}</p>}
    {value.id && <div className="mt-3 flex items-center gap-2">{status === "published" ? <form action={unpublishAction}><input type="hidden" name="id" value={value.id} /><Button type="submit" variant="outline">{tx("Unpublish")}</Button></form> : <form action={publishAction}><input type="hidden" name="id" value={value.id} /><Button type="submit" variant="outline">{tx("Publish")}</Button></form>}<a className="inline-flex h-9 items-center gap-1 rounded-md border border-border px-3 text-xs font-semibold" href={`/practice/${value.slug}?preview=1`}>{tx("Preview in Practice")} <span aria-hidden="true">→</span></a></div>}
    {status === "published" && <p className="mt-2 text-[10px] text-muted-foreground">{tx("Saving changes returns this lesson to draft so edits do not silently replace published content.")}</p>}
    {availableTools.length === 0 && <p className="mt-3 text-[10px] text-amber-700">{tx("No registered runtime tools are available.")}</p>}
  </div>;
}
