import { caseObjectRuntimeId } from "@/cad/case-packages/identity";
import { DIGITAL_MODEL_R6_PACKAGES, BITE_SPLINT_R6_PACKAGES } from "@/cad/case-packages/definitions/dental-realism-r6";
import { lessonSchema, type PracticeLesson, type PracticeStep } from "./types";

type Stage = {
  id: string;
  order: number;
  title: { en: string; sr: string };
  what: { en: string; sr: string };
  why: { en: string; sr: string };
  object: { en: string; sr: string };
  tool: string;
  action: { en: string; sr: string };
  target: { en: string; sr: string };
  check: { en: string; sr: string };
  objectIds: string[];
  tools: PracticeStep["allowedTools"];
  validators: PracticeStep["validators"];
};

const l = (en: string, sr: string) => ({ en, sr });
const hint = (id: string, en: string, sr: string) => ({ id, title: l("Use the Scene", "Koristite Scene"), body: l(en, sr) });

function makeStep(stage: Stage): PracticeStep {
  return {
    id: stage.id,
    order: stage.order,
    title: stage.title,
    instructions: {
      en: `WHAT: ${stage.what.en}\nWHY: ${stage.why.en}\nOBJECT: ${stage.object.en}\nTOOL: ${stage.tool}\nACTION: ${stage.action.en}\nTARGET: ${stage.target.en}\nCHECK: ${stage.check.en}`,
      sr: `ŠTA: ${stage.what.sr}\nZAŠTO: ${stage.why.sr}\nOBJEKAT: ${stage.object.sr}\nALAT: ${stage.tool}\nAKCIJA: ${stage.action.sr}\nCILJ: ${stage.target.sr}\nPROVERA: ${stage.check.sr}`,
    },
    theory: stage.why,
    allowedTools: stage.tools,
    targetObjectIds: stage.objectIds,
    hints: [hint(`${stage.id}-next`, "The Scene uses SOURCE, DESIGN, GUIDE, and REFERENCE roles. Keep the raw scan locked and work on the editable DESIGN object.", "Scene koristi uloge SOURCE, DESIGN, GUIDE i REFERENCE. Sirovi snimak ostaje zaključan, a radi se na DIZAJN objektu koji može da se menja.")],
    referenceModes: ["off", "outline", "transparent"],
    validators: stage.validators,
    required: true,
  };
}

function lesson(input: { id: string; databaseId: string; moduleId: string; title: { en: string; sr: string }; summary: { en: string; sr: string }; goal: { en: string; sr: string }; casePackageId: string; checkpointId: string; source: "bite-splint-case" | "digital-model-case" | "articulator-case"; estimatedMinutes: number; difficulty: "beginner" | "intermediate" | "advanced"; prerequisites?: PracticeLesson["recommendedPrerequisites"]; steps: Stage[]; caseId: string; objects: string[] }): PracticeLesson {
  return lessonSchema.parse({
    id: input.id,
    databaseId: input.databaseId,
    moduleId: input.moduleId,
    title: input.title,
    summary: input.summary,
    goal: input.goal,
    difficulty: input.difficulty,
    recommendedPrerequisites: input.prerequisites ?? [],
    estimatedMinutes: input.estimatedMinutes,
    assets: [],
    caseSetup: { source: input.source, casePackageId: input.casePackageId, checkpointId: input.checkpointId, objectMappings: input.objects.flatMap((localId) => {
      const packageObject = [...BITE_SPLINT_R6_PACKAGES, ...DIGITAL_MODEL_R6_PACKAGES].find((manifest) => manifest.caseId === input.caseId)?.objects.find((object) => object.id === localId)
        ?? (articulator.caseId === input.caseId ? articulator.objects.find((object) => object.id === localId) : undefined);
      return packageObject ? [{ runtimeObjectId: caseObjectRuntimeId(input.caseId, localId), semanticRole: `${packageObject.caseRole}:${packageObject.cadRole}`, editable: packageObject.editable }] : [];
    }) },
    steps: input.steps.map(makeStep),
  });
}

const splint = BITE_SPLINT_R6_PACKAGES[0];
const splintId = (localId: string) => caseObjectRuntimeId(splint.caseId, localId);
const splintBoundaryId = `${splint.caseId}-boundary`;
const splintSteps: Stage[] = [
  { id: "inspect", order: 1, title: l("Inspect arches and relation", "Pregled lukova i odnosa"), what: l("Identify the upper SOURCE, lower antagonist, and their synthetic relation.", "Uočite gornji IZVOR, donjeg antagonistu i njihov sintetički odnos."), why: l("The design arch and antagonist define which surfaces need review.", "Luk za dizajn i antagonist određuju koje površine treba pregledati."), object: l("SOURCE upper and lower arches; REFERENCE relation plane.", "IZVORNI gornji i donji luk; REFERENTNA ravan odnosa."), tool: "Scene, Select, Camera", action: l("Orbit both arches, toggle the relation reference, and identify the upper design arch.", "Rotirajte oba luka, uključite referencu odnosa i odredite gornji luk za dizajn."), target: l("Target for this exercise: identify the design arch and opposing arch.", "Cilj ove vežbe: odredite luk za dizajn i suprotni luk."), check: l("Confirm the package has upper and lower SOURCE objects with a shared jaw reference.", "Potvrdite da paket sadrži gornji i donji IZVORNI objekat i zajedničku referencu odnosa vilica."), objectIds: [splintId("source-upper-arch"), splintId("source-lower-arch")], tools: ["select", "camera", "scene"], validators: [{ type: "required_object", objectId: splintId("source-upper-arch"), visible: true }, { type: "required_object", objectId: splintId("source-lower-arch"), visible: true }] },
  { id: "alignment", order: 2, title: l("Verify the jaw relation", "Proverite odnos vilica"), what: l("Inspect vertical and horizontal alignment before designing the shell.", "Pre dizajna udlage pregledajte vertikalno i horizontalno poravnanje."), why: l("A consistent relation makes static antagonist comparisons easier to interpret.", "Dosledan odnos olakšava tumačenje statičkog poređenja sa antagonistom."), object: l("SOURCE arches and the synthetic relation REFERENCE.", "IZVORNI lukovi i sintetička REFERENCA odnosa."), tool: "Scene, Select, Camera", action: l("Compare cusp regions and support context in front, top, and oblique views.", "Uporedite kvržice i potpornu anatomiju iz frontalnog, gornjeg i kosog prikaza."), target: l("Target for this exercise: a reviewed teaching relation, not patient-specific occlusion.", "Cilj ove vežbe: pregledan edukativni odnos, ne okluzija konkretnog pacijenta."), check: l("Record that you reviewed the reference relation before selecting the splint arch.", "Zabeležite da ste pregledali referentni odnos pre izbora luka za udlagu."), objectIds: [splintId("reference-relation")], tools: ["select", "camera", "scene"], validators: [{ type: "required_step" }] },
  { id: "boundary", order: 3, title: l("Review the splint boundary", "Pregledajte granicu udlage"), what: l("Inspect the closed GUIDE boundary on the selected upper arch.", "Pregledajte zatvorenu granicu VODIČA na izabranom gornjem luku."), why: l("The boundary sets the extent of the inner, tooth-facing form.", "Granica određuje opseg unutrašnjeg oblika okrenutog zubima."), object: l("Upper SOURCE and editable splint boundary curve.", "Gornji IZVOR i kriva granice udlage koja može da se menja."), tool: "Scene, Select, Analysis · Boundary", action: l("Select the upper arch, inspect the closed loop, and edit points only where the boundary should change.", "Izaberite gornji luk, pregledajte zatvorenu liniju i menjajte tačke samo tamo gde treba promeniti granicu."), target: l("Target for this exercise: a closed boundary that follows the selected arch.", "Cilj ove vežbe: zatvorena granica koja prati izabrani luk."), check: l("Design Check confirms a closed splint boundary attached to the upper SOURCE.", "Design Check potvrđuje zatvorenu granicu udlage povezanu sa gornjim IZVOROM."), objectIds: [splintId("source-upper-arch")], tools: ["select", "analysis", "camera"], validators: [{ type: "curve_closed", objectId: splintId("source-upper-arch"), curveId: splintBoundaryId, curveKind: "splint_boundary" }, { type: "r6_workflow", workflow: "bite_splint", check: "boundary" }] },
];

const splintBuildSteps: Stage[] = [
  { id: "inner-surface", order: 1, title: l("Generate the inner surface", "Napravite unutrašnju površinu"), what: l("Build the editable shell from the arch boundary.", "Napravite udlagu koja može da se menja iz granice luka."), why: l("The lower shell surface introduces the tooth-facing side of the splint.", "Donja površina uvodi stranu udlage koja naleže uz zube."), object: l("Editable DESIGN splint and GUIDE boundary.", "DIZAJN udlaga koja može da se menja i VODIČ granice."), tool: "Bite Splint controls, Scene", action: l("Choose Build / update splint, then select the DESIGN shell to inspect its inner surface.", "Izaberite Build / update splint, pa izaberite DIZAJN udlagu i pregledajte unutrašnju površinu."), target: l("Target for this exercise: one registered editable shell following the selected arch.", "Cilj ove vežbe: registrovana udlaga koja može da se menja i prati izabrani luk."), check: l("Confirm the shell is visible, editable, package-backed, and has a mesh revision.", "Potvrdite da je udlaga vidljiva, može da se menja, potiče iz paketa i ima reviziju mreže."), objectIds: [splintId("design-splint")], tools: ["select", "sculpt", "mesh-edit", "scene"], validators: [{ type: "required_object", objectId: splintId("design-splint"), visible: true, minGeometryRevision: 1 }, { type: "r6_workflow", workflow: "bite_splint", check: "splint" }] },
  { id: "outer-thickness", order: 2, title: l("Review outer form and thickness", "Pregledajte spoljašnji oblik i debljinu"), what: l("Inspect the outer shell and adjust the target thickness for this exercise.", "Pregledajte spoljašnju udlagu i podesite ciljnu debljinu za ovu vežbu."), why: l("An outer form that stays over the inner surface makes the teaching shell easier to understand.", "Spoljašnji oblik iznad unutrašnje površine olakšava razumevanje edukativne udlage."), object: l("DESIGN shell, thickness guide, and selected target value.", "DIZAJN udlaga, vodič debljine i izabrana ciljna vrednost."), tool: "Bite Splint controls, Analysis · Thickness, Sculpt", action: l("Set a small exercise thickness target, rebuild the shell, then inspect its section and smooth only obvious irregularities.", "Postavite ciljnu debljinu za vežbu, ponovo napravite udlagu, pa pregledajte presek i zagladite samo očigledne nepravilnosti."), target: l("Target for this exercise: the registered shell depth represents the selected thickness value.", "Cilj ove vežbe: dubina registrovane udlage odgovara izabranoj vrednosti debljine."), check: l("Compare the geometry depth with the thickness target; it is not a patient-fit limit.", "Uporedite dubinu geometrije sa ciljem debljine; to nije granica naleganja na pacijenta."), objectIds: [splintId("design-splint"), splintId("guide-thickness")], tools: ["select", "sculpt", "analysis", "scene"], validators: [{ type: "r6_workflow", workflow: "bite_splint", check: "thickness" }] },
];

const splintReviewSteps: Stage[] = [
  { id: "contacts", order: 1, title: l("Analyze contacts", "Analizirajte kontakte"), what: l("Compare the splint with the lower antagonist using the shared proximity map.", "Uporedite udlagu sa donjim antagonistom zajedničkom mapom blizine."), why: l("A contact distribution view helps locate broad near-contact regions and obvious high areas.", "Prikaz rasporeda kontakata pomaže da uočite široke zone blizine i očigledno visoke delove."), object: l("DESIGN splint and SOURCE antagonist.", "DIZAJN udlaga i IZVORNI antagonist."), tool: "Analysis · Proximity map", action: l("Run Proximity analysis for the splint and lower arch, then inspect the coloured map across the posterior and anterior regions.", "Pokrenite analizu blizine za udlagu i donji luk, pa pregledajte mapu boja u prednjim i bočnim regijama."), target: l("Target for this exercise: review contact distribution and identify any obvious high-contact region.", "Cilj ove vežbe: pregledajte raspored kontakata i uočite očigledne zone visokog kontakta."), check: l("The Design Check requires a current shared proximity result for this pair.", "Design Check zahteva aktuelnu zajedničku analizu blizine ovog para."), objectIds: [splintId("design-splint"), splintId("source-lower-arch")], tools: ["select", "analysis", "camera"], validators: [{ type: "r6_workflow", workflow: "bite_splint", check: "contacts" }] },
  { id: "occlusion", order: 2, title: l("Review antagonist intersection", "Pregledajte presek sa antagonistom"), what: l("Check the synthetic reference pose for gross intersections and major clearance concerns.", "Proverite sintetički referentni položaj zbog grubih preseka i većih problema sa zazorom."), why: l("Intersection feedback distinguishes gross overlap from simple proximity in this simplified teaching case.", "Povratna informacija o preseku razlikuje grubo preklapanje od same blizine u ovom pojednostavljenom modelu."), object: l("DESIGN shell, antagonist SOURCE, and relation GUIDE.", "DIZAJN udlaga, IZVORNI antagonist i VODIČ odnosa."), tool: "Analysis · Intersection", action: l("Run Intersection for splint and antagonist. Review any overlap, then inspect the pair again after a geometry adjustment.", "Pokrenite Intersection za udlagu i antagonistu. Pregledajte preklapanje, pa ponovo proverite par posle izmene geometrije."), target: l("Target for this exercise: no gross shell-antagonist intersection in the synthetic reference pose.", "Cilj ove vežbe: bez grubog preseka udlage i antagonista u sintetičkom referentnom položaju."), check: l("The current intersection result must report no overlap; this is not functional occlusion validation.", "Aktuelni rezultat preseka treba da pokaže da nema preklapanja; ovo nije provera funkcionalne okluzije."), objectIds: [splintId("design-splint"), splintId("source-lower-arch")], tools: ["select", "analysis", "camera"], validators: [{ type: "r6_workflow", workflow: "bite_splint", check: "occlusion" }] },
  { id: "final", order: 3, title: l("Final Bite Splint Design Check", "Završni Design Check za udlagu"), what: l("Review the boundary, editable shell, thickness, contact map, and synthetic antagonist pair.", "Pregledajte granicu, udlagu koja može da se menja, debljinu, mapu kontakata i sintetički par sa antagonistom."), why: l("A structural review catches missing design and analysis state before the training case is complete.", "Strukturni pregled otkriva nedostajući dizajn ili analizu pre završetka edukativnog slučaja."), object: l("All package SOURCE, DESIGN, GUIDE, and REFERENCE objects.", "Svi SOURCE, DESIGN, GUIDE i REFERENCE objekti paketa."), tool: "Scene, Analysis, Design Check", action: l("Run Design Check and resolve any missing boundary, shell, proximity, or gross-intersection feedback.", "Pokrenite Design Check i rešite nedostajuću granicu, udlagu, mapu blizine ili grubo preklapanje."), target: l("Target for this exercise: a complete editable package-backed teaching design.", "Cilj ove vežbe: potpun edukativni dizajn iz paketa koji može da se menja."), check: l("Review every result. No patient fit, manufacturing, or functional-occlusion correctness is claimed.", "Pregledajte sve rezultate. Ne tvrdi se naleganje na pacijenta, mogućnost proizvodnje ni ispravnost funkcionalne okluzije."), objectIds: [splintId("source-upper-arch"), splintId("source-lower-arch"), splintId("design-splint")], tools: ["select", "analysis", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "bite_splint", check: "final" }] },
];

const digital = DIGITAL_MODEL_R6_PACKAGES[0];
const digitalId = (localId: string) => caseObjectRuntimeId(digital.caseId, localId);
const digitalStagesOne: Stage[] = [
  { id: "raw-source", order: 1, title: l("Inspect the raw SOURCE", "Pregledajte sirovi IZVOR"), what: l("Identify peripheral excess, scan holes, orientation, and the locked original.", "Uočite periferni višak, rupe snimka, orijentaciju i zaključani original."), why: l("Scan preparation starts with a read-only source and a separate working copy.", "Priprema snimka počinje izvornim objektom samo za čitanje i odvojenom radnom kopijom."), object: l("Locked SOURCE raw scan and editable DESIGN working copy.", "Zaključani sirovi IZVOR i DIZAJN radna kopija koja može da se menja."), tool: "Scene, Select, Camera", action: l("Compare the source and working copy. Select the raw SOURCE and confirm mesh editing is disabled.", "Uporedite izvor i radnu kopiju. Izaberite sirovi IZVOR i proverite da je uređivanje mreže onemogućeno."), target: l("Target for this exercise: preserve the raw SOURCE while editing only the DESIGN copy.", "Cilj ove vežbe: sačuvajte sirovi IZVOR i menjajte samo DIZAJN kopiju."), check: l("Design Check confirms independent raw and editable objects and unchanged SOURCE geometry.", "Design Check potvrđuje odvojene sirove i radne objekte i neizmenjenu geometriju IZVORA."), objectIds: [digitalId("source-raw-scan"), digitalId("design-working-copy")], tools: ["select", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "source_preserved" }, { type: "r6_workflow", workflow: "digital_model", check: "working_copy" }] },
  { id: "trim", order: 2, title: l("Trim scan excess", "Odsecite višak snimka"), what: l("Remove unwanted peripheral scan mesh from the working copy.", "Uklonite neželjenu perifernu mrežu snimka iz radne kopije."), why: l("Trimming narrows the model to the anatomy needed for a clean presentation.", "Trimovanje sužava model na anatomiju potrebnu za jasan prikaz."), object: l("Editable DESIGN working copy and trim GUIDE.", "DIZAJN radna kopija i VODIČ trimovanja."), tool: "Mesh Edit · Trim, Analysis · Boundary", action: l("Select the working copy, review or edit its closed trim boundary, then run Trim on the selected mesh.", "Izaberite radnu kopiju, pregledajte ili izmenite zatvorenu granicu, pa pokrenite Trim nad izabranom mrežom."), target: l("Target for this exercise: remove obvious peripheral excess while retaining the arch.", "Cilj ove vežbe: uklonite očigledan periferni višak i sačuvajte luk."), check: l("A successful shared Trim operation advances the package to the trim checkpoint.", "Uspešno zajedničko Trimovanje pomera paket na kontrolnu tačku trimovanja."), objectIds: [digitalId("design-working-copy"), digitalId("guide-trim-boundary")], tools: ["select", "mesh-edit", "analysis", "camera"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "trim" }] },
  { id: "cleanup", order: 3, title: l("Clean disconnected scan noise", "Očistite odvojeni šum snimka"), what: l("Remove remaining unwanted components and smooth only suitable noisy regions.", "Uklonite preostale neželjene komponente i zagladite samo odgovarajuće bučne regije."), why: l("Cleanup improves the working mesh while keeping meaningful tooth and ridge form.", "Čišćenje poboljšava radnu mrežu uz očuvanje oblika zuba i grebena."), object: l("Editable DESIGN scan copy and its mesh children.", "DIZAJN kopija snimka i njene mesh komponente."), tool: "Mesh Edit · Delete, Cleanup, Smooth", action: l("Inspect each mesh child, delete detached noise if present, then run Cleanup. Use Smooth only on visible scan roughness.", "Pregledajte svaku mesh komponentu, obrišite odvojeni šum ako postoji, pa pokrenite Cleanup. Smooth koristite samo na vidljivoj hrapavosti."), target: l("Target for this exercise: remove obvious disconnected noise without erasing the arch.", "Cilj ove vežbe: uklonite očigledan odvojeni šum bez brisanja luka."), check: l("A shared cleanup, delete, or smooth edit records the cleanup checkpoint.", "Zajednička Cleanup, Delete ili Smooth izmena beleži kontrolnu tačku čišćenja."), objectIds: [digitalId("design-working-copy")], tools: ["select", "mesh-edit", "camera"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "cleanup" }] },
  { id: "hole-fill", order: 4, title: l("Fill and inspect scan holes", "Popunite i pregledajte rupe snimka"), what: l("Repair a small open patch on the editable working copy.", "Popravite mali otvor na radnoj kopiji koja može da se menja."), why: l("Hole filling makes the teaching surface easier to inspect and prepare for a base.", "Popunjavanje rupa olakšava pregled edukativne površine i pripremu baze."), object: l("DESIGN working copy; keep SOURCE untouched.", "DIZAJN radna kopija; IZVOR ostaje neizmenjen."), tool: "Mesh Edit · Fill Hole", action: l("Select the open boundary on the working mesh and run Fill Hole, then inspect the repair in an oblique view.", "Izaberite otvorenu granicu na radnoj mreži i pokrenite Fill Hole, pa pregledajte popravku iz kosog ugla."), target: l("Target for this exercise: handle the visible scan opening without changing the raw source.", "Cilj ove vežbe: obradite vidljivi otvor snimka bez izmene sirovog izvora."), check: l("Design Check confirms the hole-fill stage and an intact locked raw source.", "Design Check potvrđuje fazu popunjavanja i netaknut sirovi izvor."), objectIds: [digitalId("design-working-copy"), digitalId("source-raw-scan")], tools: ["select", "mesh-edit", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "hole_fill" }, { type: "r6_workflow", workflow: "digital_model", check: "source_preserved" }] },
];

const digitalStagesTwo: Stage[] = [
  { id: "orientation", order: 1, title: l("Orient the model", "Orijentišite model"), what: l("Set the editable working copy in a clear arch presentation orientation.", "Postavite radnu kopiju koja može da se menja u jasnu orijentaciju luka."), why: l("A consistent orientation helps inspect the scan, base, and later exports.", "Dosledna orijentacija olakšava pregled snimka, baze i kasnijeg izvoza."), object: l("Editable DESIGN working copy.", "DIZAJN radna kopija koja može da se menja."), tool: "Move, Rotate, Digital Model · Orient", action: l("Use Orient working copy to reset its teaching transform, then inspect the arch from the top and side.", "Koristite Orient working copy da vratite edukativnu transformaciju, pa pregledajte luk odozgo i sa strane."), target: l("Target for this exercise: a stable reference orientation, recorded with the working-copy transform.", "Cilj ove vežbe: stabilna referentna orijentacija zabeležena transformacijom radne kopije."), check: l("Design Check confirms the orientation stage follows trim, cleanup, and hole review.", "Design Check potvrđuje da faza orijentacije sledi trimovanje, čišćenje i pregled rupa."), objectIds: [digitalId("design-working-copy")], tools: ["select", "move", "rotate", "camera"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "orientation" }] },
  { id: "base", order: 2, title: l("Create the model base", "Napravite bazu modela"), what: l("Show a separate support base aligned to the prepared dental arch.", "Prikažite zasebnu noseću bazu poravnatu sa pripremljenim zubnim lukom."), why: l("The base creates a clean presentation/support form while remaining distinct from the scan.", "Baza pruža čist oslonac za prikaz, a ostaje odvojena od snimka."), object: l("DESIGN working scan and separate arch-shaped DESIGN base.", "DIZAJN radni snimak i zasebna DIZAJN baza u obliku luka."), tool: "Digital Model controls, Scene, Move", action: l("Choose the exercise base height, reveal or generate the base, and compare its arch course with the working copy.", "Izaberite visinu baze za vežbu, prikažite ili napravite bazu i uporedite njen luk sa radnom kopijom."), target: l("Target for this exercise: one separate arch-support base under the prepared model.", "Cilj ove vežbe: zasebna noseća baza luka ispod pripremljenog modela."), check: l("Design Check confirms a registered, distinct base related to the working copy.", "Design Check potvrđuje registrovanu zasebnu bazu povezanu sa radnom kopijom."), objectIds: [digitalId("design-working-copy"), digitalId("design-model-base")], tools: ["select", "move", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "base" }] },
];

const digitalFinal: Stage[] = [
  { id: "final-review", order: 1, title: l("Final mesh and export-ready review", "Završna provera mreže i pripreme za izvoz"), what: l("Inspect the working mesh, orientation, base, and preserved raw SOURCE.", "Pregledajte radnu mrežu, orijentaciju, bazu i sačuvani sirovi IZVOR."), why: l("A compact final check catches missing stages and makes the prepared educational state explicit.", "Kratka završna provera otkriva nedostajuće faze i jasno označava pripremljeno edukativno stanje."), object: l("SOURCE raw scan, DESIGN working copy, and DESIGN model base.", "IZVORNI sirovi snimak, DIZAJN radna kopija i DIZAJN baza modela."), tool: "Scene, Properties, Digital Model · Final mesh check", action: l("Review visible components and mesh statistics, then choose Final mesh check.", "Pregledajte vidljive komponente i statistiku mreže, pa izaberite Final mesh check."), target: l("Target for this exercise: a preserved SOURCE, prepared working mesh, and distinct support base.", "Cilj ove vežbe: sačuvan IZVOR, pripremljena radna mreža i zasebna noseća baza."), check: l("The final check verifies package roles, geometry availability, and checkpoint state; it is not manufacturing approval.", "Završna provera potvrđuje uloge paketa, dostupnost geometrije i kontrolnu tačku; nije odobrenje za proizvodnju."), objectIds: [digitalId("source-raw-scan"), digitalId("design-working-copy"), digitalId("design-model-base")], tools: ["select", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "digital_model", check: "final" }, { type: "r6_workflow", workflow: "digital_model", check: "mesh_check" }] },
];

const articulator = BITE_SPLINT_R6_PACKAGES[0];
const articulatorId = (localId: string) => caseObjectRuntimeId(articulator.caseId, localId);
const articulatorSteps: Stage[] = [
  { id: "relation", order: 1, title: l("Inspect the reference relation", "Pregledajte referentni odnos"), what: l("Confirm upper and lower SOURCE arches are present in one package.", "Potvrdite da su gornji i donji IZVORNI luk prisutni u istom paketu."), why: l("The teaching articulator moves one arch against the other in a repeatable synthetic setup.", "Edukativni artikulator pomera jedan luk prema drugom u ponovljivom sintetičkom podešavanju."), object: l("Upper and lower SOURCE arches, relation reference, motion controls.", "Gornji i donji IZVORNI luk, referenca odnosa i kontrole pokreta."), tool: "Virtual Articulator, Scene", action: l("Verify fixed upper and moving lower labels, then inspect the centric reference before playback.", "Proverite oznake fiksnog gornjeg i pokretnog donjeg luka, pa pregledajte centričnu referencu pre reprodukcije."), target: l("Target for this exercise: one valid synthetic upper/lower relation.", "Cilj ove vežbe: jedan važeći sintetički odnos gornje i donje vilice."), check: l("Both arches must be package-backed SOURCE objects with upper/lower articulation roles.", "Oba luka moraju biti SOURCE objekti iz paketa sa gornjom/donjom artikulacionom ulogom."), objectIds: [articulatorId("source-upper-arch"), articulatorId("source-lower-arch")], tools: ["select", "articulator", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "relation" }] },
  { id: "open-close", order: 2, title: l("Preview open and close", "Pregledajte otvaranje i zatvaranje"), what: l("Move the lower arch through the deterministic opening path.", "Pomerite donji luk kroz determinističku putanju otvaranja."), why: l("The teaching hinge makes the rotation axis and pivot easy to inspect.", "Edukativna šarka olakšava pregled ose rotacije i oslonca."), object: l("Lower moving SOURCE and configured hinge-axis GUIDE.", "Pokretni donji IZVOR i podešena OSA šarke kao VODIČ."), tool: "Virtual Articulator · Open / Close", action: l("Choose Open / Close, move Motion position above zero, and play or scrub the preview.", "Izaberite Open / Close, pomerite Motion position iznad nule i pokrenite ili pomerajte prikaz."), target: l("Target for this exercise: repeatable opening around the configured educational hinge.", "Cilj ove vežbe: ponovljivo otvaranje oko podešene edukativne šarke."), check: l("The current mode and a nonzero deterministic position are recorded.", "Beleže se aktuelni režim i deterministički položaj različit od nule."), objectIds: [articulatorId("source-lower-arch")], tools: ["articulator", "camera"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "motion", motion: "open_close" }] },
  { id: "protrusive", order: 3, title: l("Preview protrusive movement", "Pregledajte protruzivni pokret"), what: l("Translate the lower teaching arch anteriorly.", "Pomerite donji edukativni luk unapred."), why: l("A deterministic translation illustrates direction without claiming patient-specific motion.", "Deterministički pomak prikazuje smer bez tvrdnje o pokretu konkretnog pacijenta."), object: l("Lower moving SOURCE and Virtual Articulator controls.", "Pokretni donji IZVOR i kontrole Virtual Articulator."), tool: "Virtual Articulator · Protrusive", action: l("Choose Protrusive and scrub the position control above zero.", "Izaberite Protrusive i pomerite kontrolu položaja iznad nule."), target: l("Target for this exercise: observe the synthetic anterior translation.", "Cilj ove vežbe: posmatrajte sintetički pomak unapred."), check: l("Design Check confirms the requested motion mode is active.", "Design Check potvrđuje da je izabran traženi režim pokreta."), objectIds: [articulatorId("source-lower-arch")], tools: ["articulator", "camera"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "motion", motion: "protrusive" }] },
  { id: "left-lateral", order: 4, title: l("Preview left lateral movement", "Pregledajte levi lateralni pokret"), what: l("Move the lower arch laterally in the documented teaching coordinate system.", "Pomerite donji luk bočno prema dokumentovanom edukativnom koordinatnom sistemu."), why: l("The signed deterministic path helps compare the two lateral directions.", "Predznak determinističke putanje olakšava poređenje oba bočna smera."), object: l("Lower moving SOURCE and Virtual Articulator controls.", "Pokretni donji IZVOR i kontrole Virtual Articulator."), tool: "Virtual Articulator · Left lateral", action: l("Choose Left lateral and move the position control above zero.", "Izaberite Left lateral i pomerite kontrolu položaja iznad nule."), target: l("Target for this exercise: inspect one reproducible lateral direction.", "Cilj ove vežbe: pregledajte jedan ponovljiv bočni smer."), check: l("The selected mode and pose position are valid.", "Izabrani režim i položaj su važeći."), objectIds: [articulatorId("source-lower-arch")], tools: ["articulator", "camera"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "motion", motion: "left_lateral" }] },
  { id: "right-lateral", order: 5, title: l("Preview right lateral movement", "Pregledajte desni lateralni pokret"), what: l("Compare the opposite lateral teaching path.", "Uporedite suprotnu edukativnu bočnu putanju."), why: l("A reproducible opposing path makes the sign and direction relationship visible.", "Ponovljiva suprotna putanja prikazuje vezu predznaka i smera."), object: l("Lower moving SOURCE and Virtual Articulator controls.", "Pokretni donji IZVOR i kontrole Virtual Articulator."), tool: "Virtual Articulator · Right lateral", action: l("Choose Right lateral and move the position control above zero.", "Izaberite Right lateral i pomerite kontrolu položaja iznad nule."), target: l("Target for this exercise: inspect the opposite deterministic lateral direction.", "Cilj ove vežbe: pregledajte suprotan deterministički bočni smer."), check: l("The selected mode and pose position are valid.", "Izabrani režim i položaj su važeći."), objectIds: [articulatorId("source-lower-arch")], tools: ["articulator", "camera"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "motion", motion: "right_lateral" }] },
  { id: "dynamic-contact", order: 6, title: l("Analyze sampled contacts", "Analizirajte uzorkovane kontakte"), what: l("Review contact and gross-intersection feedback across deterministic poses.", "Pregledajte kontakt i povratnu informaciju o grubom preseku kroz determinističke položaje."), why: l("Sampled comparisons illustrate changing proximity while remaining explicit about discrete sampling.", "Uzorkovana poređenja prikazuju promenu blizine uz jasno navođenje diskretnog uzorkovanja."), object: l("Upper fixed and lower moving SOURCE pair.", "Fiksni gornji i pokretni donji IZVORNI par."), tool: "Virtual Articulator · Analyze motion", action: l("Select a motion and run Analyze motion. Compare the sampled contact status with the static reference.", "Izaberite pokret i pokrenite Analyze motion. Uporedite uzorkovani kontakt sa statičkom referencom."), target: l("Target for this exercise: one current multi-pose analysis for the selected pair.", "Cilj ove vežbe: aktuelna analiza više položaja za izabrani par."), check: l("The sampled analysis must match the current geometry, transforms, and motion configuration.", "Uzorkovana analiza mora odgovarati aktuelnoj geometriji, transformacijama i podešavanju pokreta."), objectIds: [articulatorId("source-upper-arch"), articulatorId("source-lower-arch")], tools: ["articulator", "analysis", "camera"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "dynamic_contacts" }] },
  { id: "reset", order: 7, title: l("Reset to centric and review", "Vratite centrični položaj i pregledajte"), what: l("Return the lower arch to the reference state and compare it with the recorded motion.", "Vratite donji luk u referentno stanje i uporedite ga sa zabeleženim pokretom."), why: l("Reset gives a stable reproducible comparison point.", "Reset daje stabilnu i ponovljivu tačku poređenja."), object: l("Upper/lower SOURCE pair and motion results.", "Gornji/donji IZVORNI par i rezultati pokreta."), tool: "Virtual Articulator · Reset", action: l("Choose Reset reference, then review the static pair and sampled result summary.", "Izaberite Reset reference, pa pregledajte statički par i sažetak uzorkovanih rezultata."), target: l("Target for this exercise: centric reference pose with no accumulated transform drift.", "Cilj ove vežbe: centrični referentni položaj bez nagomilanog pomeranja transformacije."), check: l("Reset returns the position to zero and the lower source to its original transform.", "Reset vraća položaj na nulu i donji izvor na originalnu transformaciju."), objectIds: [articulatorId("source-upper-arch"), articulatorId("source-lower-arch")], tools: ["articulator", "camera", "scene"], validators: [{ type: "r6_workflow", workflow: "articulator", check: "reset" }] },
];

export const DENTAL_REALISM_R6_LESSONS: PracticeLesson[] = [
  lesson({ id: "r6-bite-splint-foundations", databaseId: "e6000000-0000-4000-8000-000000000001", moduleId: "bite-splint-r6", title: l("Bite Splint · inspect and define", "Udlaga · pregled i definisanje"), summary: l("Inspect the upper/lower relation and prepare the editable arch boundary.", "Pregledajte odnos gornje/donje vilice i pripremite granicu luka koja može da se menja."), goal: l("Review the synthetic scans, relation, and closed upper-arch boundary.", "Pregledajte sintetičke snimke, odnos i zatvorenu granicu gornjeg luka."), casePackageId: splint.packageId, checkpointId: "inspect", source: "bite-splint-case", caseId: splint.caseId, objects: splint.objects.map((entry) => entry.id), estimatedMinutes: 8, difficulty: "beginner", steps: splintSteps }),
  lesson({ id: "r6-bite-splint-design", databaseId: "e6000000-0000-4000-8000-000000000002", moduleId: "bite-splint-r6", title: l("Bite Splint · shell and thickness", "Udlaga · ljuska i debljina"), summary: l("Generate the editable splint and review its inner/outer surfaces and thickness.", "Napravite udlagu koja može da se menja i pregledajte njene unutrašnje/spoljašnje površine i debljinu."), goal: l("Create and refine a synthetic arch-conforming splint shell.", "Napravite i doradite sintetičku udlagu koja prati zubni luk."), casePackageId: splint.packageId, checkpointId: "boundary", source: "bite-splint-case", caseId: splint.caseId, objects: splint.objects.map((entry) => entry.id), estimatedMinutes: 8, difficulty: "beginner", prerequisites: [l("Inspect arches and relation", "Pregled lukova i odnosa")], steps: splintBuildSteps }),
  lesson({ id: "r6-bite-splint-contacts", databaseId: "e6000000-0000-4000-8000-000000000003", moduleId: "bite-splint-r6", title: l("Bite Splint · contacts and final review", "Udlaga · kontakti i završni pregled"), summary: l("Review proximity, gross intersections, and the final synthetic design structure.", "Pregledajte blizinu, grube preseke i završnu strukturu sintetičkog dizajna."), goal: l("Use shared analysis infrastructure for educational antagonist feedback.", "Koristite zajedničku analizu za edukativnu povratnu informaciju antagonista."), casePackageId: splint.packageId, checkpointId: "contacts", source: "bite-splint-case", caseId: splint.caseId, objects: splint.objects.map((entry) => entry.id), estimatedMinutes: 8, difficulty: "intermediate", prerequisites: [l("Generate the inner surface", "Napravite unutrašnju površinu")], steps: splintReviewSteps }),
  lesson({ id: "r6-digital-model-cleanup", databaseId: "e6000000-0000-4000-8000-000000000004", moduleId: "digital-model-r6", title: l("Digital Model · inspect and clean", "Digitalni model · pregled i čišćenje"), summary: l("Keep the raw scan read-only while trimming and repairing an editable working copy.", "Sirovi snimak ostaje samo za čitanje dok trimujete i popravljate radnu kopiju."), goal: l("Prepare a scan-like model using the existing shared mesh tools.", "Pripremite model nalik snimku koristeći postojeće zajedničke alate za mrežu."), casePackageId: digital.packageId, checkpointId: "raw_scan", source: "digital-model-case", caseId: digital.caseId, objects: digital.objects.map((entry) => entry.id), estimatedMinutes: 15, difficulty: "beginner", steps: digitalStagesOne }),
  lesson({ id: "r6-digital-model-orientation-base", databaseId: "e6000000-0000-4000-8000-000000000005", moduleId: "digital-model-r6", title: l("Digital Model · orient and support", "Digitalni model · orijentacija i baza"), summary: l("Orient the cleaned copy and add a separate arch-shaped model base.", "Orijentišite očišćenu kopiju i dodajte zasebnu bazu modela u obliku luka."), goal: l("Create an export-ready educational presentation state.", "Napravite edukativno stanje spremno za prikaz i izvoz."), casePackageId: digital.packageId, checkpointId: "hole_fill", source: "digital-model-case", caseId: digital.caseId, objects: digital.objects.map((entry) => entry.id), estimatedMinutes: 8, difficulty: "intermediate", prerequisites: [l("Inspect the raw SOURCE", "Pregledajte sirovi IZVOR")], steps: digitalStagesTwo }),
  lesson({ id: "r6-digital-model-final", databaseId: "e6000000-0000-4000-8000-000000000006", moduleId: "digital-model-r6", title: l("Digital Model · final mesh check", "Digitalni model · završna provera mreže"), summary: l("Review raw SOURCE preservation, the prepared working mesh, and the separate base.", "Pregledajte očuvanost sirovog IZVORA, pripremljenu radnu mrežu i zasebnu bazu."), goal: l("Confirm the educational mesh-preparation state without making restorative design claims.", "Potvrdite edukativno stanje pripreme mreže bez tvrdnji o restaurativnom dizajnu."), casePackageId: digital.packageId, checkpointId: "base", source: "digital-model-case", caseId: digital.caseId, objects: digital.objects.map((entry) => entry.id), estimatedMinutes: 4, difficulty: "intermediate", prerequisites: [l("Orient the model", "Orijentišite model")], steps: digitalFinal }),
  lesson({ id: "r6-virtual-articulator", databaseId: "e6000000-0000-4000-8000-000000000007", moduleId: "virtual-articulator-r6", title: l("Virtual Articulator · deterministic motion", "Virtual Articulator · deterministički pokret"), summary: l("Explore open/close, protrusive, lateral, contact, and reset controls on reused synthetic arches.", "Istražite kontrole otvaranja/zatvaranja, protruzije, lateralnih pokreta, kontakta i resetovanja na ponovo korišćenim sintetičkim lukovima."), goal: l("Compare reproducible teaching motion with the centric reference relation.", "Uporedite ponovljiv edukativni pokret sa centričnim referentnim odnosom."), casePackageId: articulator.packageId, checkpointId: "alignment", source: "articulator-case", caseId: articulator.caseId, objects: articulator.objects.map((entry) => entry.id), estimatedMinutes: 14, difficulty: "intermediate", steps: articulatorSteps }),
];
