import Link from "next/link";
import { signup } from "@/app/(auth)/actions";

export default async function SignupPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const params = await searchParams;
  const error = params.error ? "We could not create the account. Check your details and try again." : null;
  const notice = params.message === "check-email" ? "If this address can be registered, a confirmation email is on its way. Follow its link to finish creating your account." : null;
  return <main className="mx-auto flex min-h-[calc(100vh-77px)] max-w-md flex-col justify-center px-6 py-12"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">GET STARTED</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Create your account</h1><p className="mt-2 text-sm text-muted-foreground">Set up your learning workspace.</p>{error && <p role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="mt-5 rounded-xl border border-border bg-card px-4 py-3 text-sm leading-6 text-muted-foreground">{notice}</p>}<form action={signup} className="mt-8 space-y-5"><label htmlFor="displayName" className="block text-sm font-medium">Name<input id="displayName" name="displayName" type="text" required maxLength={100} autoComplete="name" placeholder="Your name" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><label htmlFor="email" className="block text-sm font-medium">Email address<input id="email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><label htmlFor="password" className="block text-sm font-medium">Password<input id="password" name="password" type="password" required minLength={8} maxLength={128} autoComplete="new-password" placeholder="At least 8 characters" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><button type="submit" className="h-11 w-full rounded-xl bg-primary text-sm font-medium text-primary-foreground">Create account</button></form><p className="mt-6 text-center text-sm text-muted-foreground">Already have an account? <Link href="/login" className="font-medium text-foreground underline underline-offset-4">Log in</Link></p></main>;
}
