import Link from "next/link";
import { login } from "@/app/(auth)/actions";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string; next?: string }> }) {
  const params = await searchParams;
  const error = params.error === "credentials" ? "Email or password is incorrect." : params.error === "confirmation" ? "The confirmation link could not be verified. Please request a new one." : params.error ? "We could not log you in. Check your details and try again." : null;
  const notice = params.message === "signed-out" ? "You have been signed out." : null;
  return <main className="mx-auto flex min-h-[calc(100vh-77px)] max-w-md flex-col justify-center px-6 py-12"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">WELCOME BACK</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Log in to Prostheia</h1><p className="mt-2 text-sm text-muted-foreground">Continue learning and working on your designs.</p>{error && <p role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="mt-5 rounded-xl border border-border bg-card px-4 py-3 text-sm text-muted-foreground">{notice}</p>}<form action={login} className="mt-8 space-y-5"><input type="hidden" name="next" value={params.next ?? ""}/><label htmlFor="email" className="block text-sm font-medium">Email address<input id="email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><label htmlFor="password" className="block text-sm font-medium">Password<input id="password" name="password" type="password" required autoComplete="current-password" placeholder="Enter your password" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><button type="submit" className="h-11 w-full rounded-xl bg-primary text-sm font-medium text-primary-foreground">Continue</button></form><p className="mt-6 text-center text-sm text-muted-foreground">New to Prostheia? <Link href="/signup" className="font-medium text-foreground underline underline-offset-4">Create an account</Link></p></main>;
}
