"use client";

import Link from "next/link";
import { useI18n } from "@/lib/i18n";

type ServerFormAction = (data: FormData) => void | Promise<void>;

export function LoginForm({ action, next, error, notice }: { action: ServerFormAction; next?: string; error: "credentials" | "confirmation" | "other" | null; notice: boolean }) {
  const { t } = useI18n();
  const errorMessage = error === "credentials" ? t("loginCredentialsError") : error === "confirmation" ? t("loginConfirmationError") : error ? t("loginError") : null;
  return <main className="mx-auto flex max-w-md flex-col justify-center px-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{t("welcomeBack")}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{t("loginTitle")}</h1><p className="mt-2 text-sm text-muted-foreground">{t("loginIntro")}</p>{errorMessage && <p role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{errorMessage}</p>}{notice && <p role="status" className="mt-5 rounded-xl border border-border bg-card px-4 py-3 text-sm text-muted-foreground">{t("signedOutNotice")}</p>}<form action={action} className="mt-8 space-y-5"><input type="hidden" name="next" value={next ?? ""}/><label htmlFor="email" className="block text-sm font-medium">{t("emailAddress")}<input id="email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><label htmlFor="password" className="block text-sm font-medium">{t("password")}<input id="password" name="password" type="password" required autoComplete="current-password" placeholder={t("enterPassword")} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><button type="submit" className="h-11 w-full rounded-xl bg-primary text-sm font-medium text-primary-foreground">{t("continueButton")}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">{t("newToProduct")} <Link href="/signup" className="font-medium text-foreground underline underline-offset-4">{t("createAccount")}</Link></p></main>;
}

export function SignupForm({ action, error, notice }: { action: ServerFormAction; error: boolean; notice: boolean }) {
  const { t } = useI18n();
  return <main className="mx-auto flex min-h-[calc(100vh-77px)] max-w-md flex-col justify-center px-6 py-12"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{t("getStarted")}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{t("signupTitle")}</h1><p className="mt-2 text-sm text-muted-foreground">{t("signupIntro")}</p>{error && <p role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{t("signupError")}</p>}{notice && <p role="status" className="mt-5 rounded-xl border border-border bg-card px-4 py-3 text-sm leading-6 text-muted-foreground">{t("signupNotice")}</p>}<form action={action} className="mt-8 space-y-5"><label htmlFor="displayName" className="block text-sm font-medium">{t("name")}<input id="displayName" name="displayName" type="text" required maxLength={100} autoComplete="name" placeholder={t("yourName")} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><label htmlFor="email" className="block text-sm font-medium">{t("emailAddress")}<input id="email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><label htmlFor="password" className="block text-sm font-medium">{t("password")}<input id="password" name="password" type="password" required minLength={8} maxLength={128} autoComplete="new-password" placeholder={t("passwordMinLength")} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/></label><button type="submit" className="h-11 w-full rounded-xl bg-primary text-sm font-medium text-primary-foreground">{t("createAccount")}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">{t("alreadyHaveAccount")} <Link href="/login" className="font-medium text-foreground underline underline-offset-4">{t("login")}</Link></p></main>;
}
