import { ArrowUpRight, BookOpen, Box, BriefcaseBusiness, LayoutDashboard, Sparkles } from "lucide-react";
import Link from "next/link";

const content = {
  Dashboard: { eyebrow: "YOUR WORKSPACE", title: "Welcome to Prostheia", description: "A focused space to learn digital dental design and work through 3D cases.", icon: LayoutDashboard },
  Practice: { eyebrow: "LEARN BY DOING", title: "Practice", description: "Build confidence with guided lessons and structured design exercises.", icon: BookOpen },
  "Free Lab": { eyebrow: "OPEN WORKSPACE", title: "Free Lab", description: "Explore a flexible CAD workspace at your own pace.", icon: Box },
  "My Cases": { eyebrow: "YOUR PROJECTS", title: "My Cases", description: "Your saved design cases will appear here when cloud projects are connected.", icon: BriefcaseBusiness },
  Progress: { eyebrow: "YOUR LEARNING", title: "Progress", description: "Track your completed lessons and growing design skills.", icon: Sparkles },
} as const;

export function PlaceholderPage({ section }: { section: keyof typeof content }) {
  const item = content[section];
  const Icon = item.icon;
  return <div className="space-y-9"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[11px] font-semibold tracking-[0.18em] text-primary">{item.eyebrow}</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{item.title}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{item.description}</p></div>{section === "Dashboard" && <Link href="/practice" className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground shadow-sm">Start practicing <ArrowUpRight className="size-4" /></Link>}</div>
    <section className="relative overflow-hidden rounded-3xl border border-border bg-card p-7 sm:p-10"><div className="pointer-events-none absolute -right-10 -top-16 size-64 rounded-full bg-primary/5 blur-3xl"/><div className="relative grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><div className="mb-6 grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-6" /></div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">A workspace taking shape</p><h2 className="mt-3 max-w-lg text-2xl font-semibold tracking-tight">Your dental design journey starts here.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">The application shell is ready. Lessons, case data, and connected workspace tools will arrive in the next implementation phases.</p><Link href="/workspace/demo" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-primary">Open CAD workspace test <ArrowUpRight className="size-4" /></Link></div><div className="grid min-h-52 place-items-center rounded-2xl border border-dashed border-border bg-background/70"><div className="text-center"><div className="mx-auto mb-3 grid size-14 place-items-center rounded-2xl bg-muted text-muted-foreground"><Icon className="size-6" /></div><p className="text-sm font-medium">{section === "Dashboard" ? "Your next lesson will appear here" : `${section} content will appear here`}</p><p className="mt-1 text-xs text-muted-foreground">Ready for the next phase</p></div></div></div></section>
    {section === "Dashboard" && <div className="grid gap-4 md:grid-cols-3"><QuickLink href="/practice" label="Practice" description="Guided lessons" icon={BookOpen}/><QuickLink href="/free-lab" label="Free Lab" description="Open CAD workspace" icon={Box}/><QuickLink href="/cases" label="My Cases" description="Saved projects" icon={BriefcaseBusiness}/></div>}</div>;
}

function QuickLink({ href, label, description, icon: Icon }: { href: string; label: string; description: string; icon: typeof BookOpen }) { return <Link href={href} className="group flex items-center gap-4 rounded-2xl border border-border bg-card p-5 transition-colors hover:bg-muted/60"><span className="grid size-11 place-items-center rounded-xl bg-muted text-foreground"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></span><ArrowUpRight className="size-4 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link> }
