-- Phase 20 content seed. Geometry is generated internally by Prostheia and remains educational.
insert into public.practice_modules(id,slug,title_en,title_sr,summary_en,summary_sr,sort_order,status)
values
 ('b7200000-0000-4000-8000-000000000001','bite_splint','Bite Splint','Okluzalna udlaga','Use shared insertion, curve, mesh editing and analysis tools to build and inspect a synthetic educational splint.','Koristite zajedničke alate za put insercije, krive, uređivanje mreže i analizu za izradu i pregled sintetičke edukativne udlage.',80,'published'),
 ('b7200000-0000-4000-8000-000000000002','digital_model','Digital Model','Digitalni model','Preserve the raw source, prepare an editable working model, and add simplified editable model components.','Sačuvajte izvorni sken, pripremite radni model koji se može uređivati i dodajte pojednostavljene komponente.',90,'published')
on conflict(slug) do update set title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,sort_order=excluded.sort_order,status='published';

insert into public.practice_lessons(id,module_id,slug,difficulty,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,estimated_minutes,case_setup,sort_order,status)
select v.id,m.id,v.slug,v.difficulty::public.difficulty_level,v.title_en,v.title_sr,v.summary_en,v.summary_sr,v.goal_en,v.goal_sr,v.minutes,jsonb_build_object('source',v.source,'objectMappings','[]'::jsonb),v.sort_order,'published'
from (values
 ('b7200000-0000-4000-8000-000000000010'::uuid,'splint_insertion_and_undercut','bite_splint','beginner',10,'Insertion direction and undercut preview','Put insercije i pregled podminiranja','Inspect the upper arch with shared directional analysis.','Pregledajte gornju vilicu zajedničkom analizom smera.','Choose and inspect an insertion direction on a synthetic arch.','Izaberite i pregledajte put insercije na sintetičkoj vilici.',8,'bite-splint-case'),
 ('b7200000-0000-4000-8000-000000000011'::uuid,'splint_boundary_and_generation','bite_splint','beginner',20,'Splint boundary and internal surface','Granica udlage i unutrašnja površina','Edit the shared boundary curve and create an editable splint solid.','Uredite zajedničku graničnu krivu i napravite udlagu koja se može uređivati.','Close and edit the splint boundary, then generate the educational solid.','Zatvorite i uredite granicu udlage, zatim generišite edukativni čvrsti model.',12,'bite-splint-case'),
 ('b7200000-0000-4000-8000-000000000012'::uuid,'splint_inspection_capstone','bite_splint','intermediate',30,'Thickness, antagonist and final check','Debljina, antagonist i završna provera','Inspect the generated splint using shared sculpt and analysis tools.','Pregledajte generisanu udlagu zajedničkim alatima za modelovanje i analizu.','Use the configured exercise target, sculpt tools and static proximity check.','Koristite podešeni cilj vežbe, alate za modelovanje i statičku proveru blizine.',15,'bite-splint-case'),
 ('b7200000-0000-4000-8000-000000000020'::uuid,'digital_model_inspection_and_orientation','digital_model','beginner',10,'Raw scan and working model orientation','Izvorni sken i orijentacija radnog modela','Inspect the immutable source and orient only its editable working copy.','Pregledajte neizmenjivi izvor i orijentišite samo radnu kopiju koja se uređuje.','Preserve the source scan while using shared Move and Rotate on the working model.','Sačuvajte izvorni sken i koristite zajedničke alate Move i Rotate na radnom modelu.',8,'digital-model-case'),
 ('b7200000-0000-4000-8000-000000000021'::uuid,'digital_model_trim_and_cleanup','digital_model','beginner',20,'Trim and clean the working model','Obrezivanje i čišćenje radnog modela','Use shared Trim, Cleanup, Fill Hole and mesh inspection tools on the working copy.','Koristite zajedničke alate Trim, Cleanup, Fill Hole i pregled mreže na radnoj kopiji.','Create an edited working geometry revision without overwriting the raw source.','Napravite izmenjenu verziju radne geometrije bez prepisivanja izvornog skena.',12,'digital-model-case'),
 ('b7200000-0000-4000-8000-000000000022'::uuid,'digital_model_base_and_capstone','digital_model','intermediate',30,'Base, removable dies and attachments','Osnova, uklonjivi patrljci i dodaci','Generate and inspect editable educational model components.','Generišite i pregledajte edukativne komponente koje se mogu uređivati.','Create a base, add optional dies or attachments, then inspect and export the edited case.','Napravite osnovu, dodajte patrljke ili dodatke po izboru, a zatim pregledajte i izvezite izmenjeni slučaj.',15,'digital-model-case')
) v(id,slug,module_slug,difficulty,sort_order,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,minutes,source)
join public.practice_modules m on m.slug=v.module_slug
on conflict(slug) do update set module_id=excluded.module_id,difficulty=excluded.difficulty::public.difficulty_level,title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,goal_en=excluded.goal_en,goal_sr=excluded.goal_sr,estimated_minutes=excluded.estimated_minutes,case_setup=excluded.case_setup,sort_order=excluded.sort_order,status='published';

create or replace function pg_temp.seed_phase20_step(p_lesson text,p_slug text,p_order int,p_title_en text,p_title_sr text,p_instruction_en text,p_instruction_sr text,p_theory_en text,p_theory_sr text,p_tools text[],p_targets text[],p_validator jsonb default null)
returns void language plpgsql as $$
declare lesson_key uuid;step_key uuid;validator_id uuid;tool_id text;
begin
 select id into strict lesson_key from public.practice_lessons where slug=p_lesson;
 insert into public.practice_steps(lesson_id,slug,sort_order,title_en,title_sr,instructions_en,instructions_sr,theory_en,theory_sr,target_object_ids,reference_modes,reference_config,example_config,required)
 values(lesson_key,p_slug,p_order,p_title_en,p_title_sr,p_instruction_en,p_instruction_sr,p_theory_en,p_theory_sr,p_targets,array['off','outline','transparent','full'],null,jsonb_build_object('label_en','Synthetic exercise reference','label_sr','Sintetička referenca vežbe','mode','outline'),true)
 on conflict(lesson_id,slug) do update set sort_order=excluded.sort_order,title_en=excluded.title_en,title_sr=excluded.title_sr,instructions_en=excluded.instructions_en,instructions_sr=excluded.instructions_sr,theory_en=excluded.theory_en,theory_sr=excluded.theory_sr,target_object_ids=excluded.target_object_ids,reference_modes=excluded.reference_modes,required=true returning id into step_key;
 delete from public.practice_step_tools where practice_step_tools.step_id=step_key;
 delete from public.practice_step_validations where practice_step_validations.step_id=step_key;
 foreach tool_id in array p_tools loop insert into public.practice_step_tools(step_id,tool_id) values(step_key,tool_id) on conflict do nothing; end loop;
 if p_validator is not null then
  insert into public.validation_configs(slug,validator_type,config,status) values('phase20_'||p_lesson||'_'||p_slug,case when p_validator->>'type'='curve_closed' then 'custom'::public.validator_type else (p_validator->>'type')::public.validator_type end,p_validator,'published') on conflict(slug) do update set validator_type=excluded.validator_type,config=excluded.config,status='published' returning id into validator_id;
  insert into public.practice_step_validations(step_id,validation_config_id,sort_order) values(step_key,validator_id,10);
 end if;
end $$;

select pg_temp.seed_phase20_step('splint_insertion_and_undercut','inspect_direction',10,'Inspect the insertion direction','Pregledajte put insercije','Select the synthetic upper arch. In Inspect, choose Insertion direction, set an axis, and preview the path.','Izaberite sintetičku gornju vilicu. U Inspect izaberite Insertion direction, podesite osu i prikažite put.','The shared preview helps inspect directional clearance. It is not a dynamic articulator or a clinical undercut measurement.','Zajednički prikaz pomaže pregledu prolaza u izabranom smeru. Nije dinamički artikulator niti kliničko merenje podminiranja.',array['select','analysis','camera','scene'],array['bite-splint-synthetic-upper'],null);
select pg_temp.seed_phase20_step('splint_boundary_and_generation','edit_boundary',10,'Edit the splint boundary','Uredite granicu udlage','Use the shared curve controls to add or edit points on Splint Boundary, and confirm that it is closed.','Koristite zajedničke kontrole krive da dodate ili uredite tačke na Splint Boundary i proverite da je zatvorena.','The curve belongs to the upper arch and does not cut or modify the source geometry.','Kriva pripada gornjoj vilici i ne seče niti menja izvornu geometriju.',array['select','analysis','camera','scene'],array['bite-splint-synthetic-upper'],jsonb_build_object('type','curve_closed','objectId','bite-splint-synthetic-upper','curveId','bite-splint-boundary-upper','curveKind','splint_boundary'));
select pg_temp.seed_phase20_step('splint_boundary_and_generation','generate_splint',20,'Generate an editable splint','Generišite udlagu koja se može uređivati','Generate the splint from the closed boundary. Select the new object and inspect its mesh in the shared CAD tools.','Generišite udlagu iz zatvorene granice. Izaberite novi objekat i pregledajte mrežu zajedničkim CAD alatima.','This exercise creates a simplified extruded solid. It is not a fitted shell and makes no production claim.','Ova vežba pravi pojednostavljeni ekstrudirani čvrsti model. To nije prilagođena ljuska i ne predstavlja proizvodnu potvrdu.',array['select','move','rotate','sculpt','mesh_edit','camera','scene'],array['bite-splint-generated'],jsonb_build_object('type','required_object','objectId','bite-splint-generated'));
select pg_temp.seed_phase20_step('splint_inspection_capstone','inspect_splint',10,'Final check','Završna provera','Inspect the splint thickness, run shared proximity against the lower antagonist, then adjust with Sculpt if needed. The numeric thickness is a Target for this exercise.','Pregledajte debljinu udlage, pokrenite zajedničku analizu blizine sa donjim antagonistom, pa je po potrebi prilagodite alatom Sculpt. Numerička debljina je Target for this exercise.','Proximity is a static comparison of the current geometry. It does not simulate jaw movement.','Blizina je statičko poređenje trenutne geometrije. Ne simulira pokret vilice.',array['select','sculpt','analysis','camera','scene'],array['bite-splint-generated','bite-splint-synthetic-antagonist'],jsonb_build_object('type','required_object','objectId','bite-splint-generated'));
select pg_temp.seed_phase20_step('digital_model_inspection_and_orientation','orient_working_copy',10,'Orient the working copy','Orijentišite radnu kopiju','Select Working digital model and use shared Move or Rotate. Leave Synthetic raw scan unchanged.','Izaberite Working digital model i koristite zajedničke alate Move ili Rotate. Ne menjajte Synthetic raw scan.','The original upload stays immutable; edits belong to the working geometry and its revisions.','Originalni unos ostaje neizmenjen; izmene pripadaju radnoj geometriji i njenim verzijama.',array['select','move','rotate','camera','scene'],array['digital-model-synthetic-raw-scan','digital-model-working-copy'],null);
select pg_temp.seed_phase20_step('digital_model_trim_and_cleanup','trim_working_model',10,'Trim the working model','Obrežite radni model','Select Working digital model, choose Face / Region or the shared Trim control, then inspect the edited mesh.','Izaberite Working digital model, odaberite Face / Region ili zajedničku kontrolu Trim, pa pregledajte izmenjenu mrežu.','Trim installs a new geometry revision and supports Undo/Redo. The raw scan remains separate.','Trim pravi novu verziju geometrije i podržava Undo/Redo. Izvorni sken ostaje odvojen.',array['select','mesh_edit','camera','scene'],array['digital-model-working-copy'],jsonb_build_object('type','required_object','objectId','digital-model-working-copy'));
select pg_temp.seed_phase20_step('digital_model_trim_and_cleanup','cleanup_inspection',20,'Clean and inspect','Očistite i pregledajte','Use Cleanup, Fill Hole or Smooth where appropriate, then inspect the working model with Section or Measure.','Po potrebi koristite Cleanup, Fill Hole ili Smooth, a zatim pregledajte radni model alatima Section ili Measure.','Use the shared mesh tools only when the geometry needs the operation; each committed edit can be undone.','Koristite zajedničke alate za mrežu kada geometrija zahteva tu operaciju; svaka izmena može da se poništi.',array['select','mesh_edit','analysis','camera','scene'],array['digital-model-working-copy'],null);
select pg_temp.seed_phase20_step('digital_model_base_and_capstone','create_components',10,'Create the model components','Napravite komponente modela','Generate a model base and optionally add a removable die or attachment. Move and inspect each editable object.','Generišite osnovu modela i po želji dodajte uklonjivi patrljak ili dodatak. Pomerite i pregledajte svaki objekat koji se može uređivati.','The educational base, dies and attachments are separate editable meshes; no boolean union or manufacturing validation is implied.','Edukativna osnova, patrljci i dodaci su odvojene mreže koje se mogu uređivati; ne podrazumeva se Boolean unija niti proizvodna validacija.',array['select','move','rotate','mesh_edit','analysis','camera','scene'],array['digital-model-base'],null);

insert into public.scenarios(domain_id,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,additional_metadata,random_eligible,status,published_at)
select d.id,v.slug,'beginner'::public.difficulty_level,v.title_en,v.title_sr,v.description_en,v.description_sr,v.code,v.indication_en,v.indication_sr,'{}'::smallint[],v.requirements_en,v.requirements_sr,v.metadata,true,'published',coalesce(s.published_at,now())
from (values
 ('bite_splint','synthetic_bite_splint','Bite splint · synthetic arches','Okluzalna udlaga · sintetičke vilice','Inspect a synthetic upper arch and antagonist with shared CAD tools.','Pregledajte sintetičku gornju vilicu i antagonistu zajedničkim CAD alatima.','PT-BS-20','Educational bite splint design exercise','Edukativna vežba dizajna okluzalne udlage',array['Inspect insertion direction and undercuts','Generate and edit the splint','Review thickness and static proximity'],array['Pregledajte put insercije i podminirana područja','Generišite i uredite udlagu','Proverite debljinu i statičku blizinu'],jsonb_build_object('caseInitializer','bite_splint','geometryProvenance','internal-synthetic-educational','noPatientData',true,'materialPreset','educational-splint','supplied',jsonb_build_object('en',array['Synthetic upper arch','Synthetic lower antagonist','Starter boundary'],'sr',array['Sintetička gornja vilica','Sintetički donji antagonist','Početna granica']))),
 ('digital_model','synthetic_digital_model','Digital model · upper scan','Digitalni model · gornji sken','Orient a working copy, trim it with shared tools and create editable model components.','Orijentišite radnu kopiju, obrežite je zajedničkim alatima i napravite komponente modela koje se mogu uređivati.','PT-DM-20','Educational digital model preparation','Edukativna priprema digitalnog modela',array['Orient the working copy','Trim and inspect the mesh','Create a base and optional attachments'],array['Orijentišite radnu kopiju','Obrežite i pregledajte mrežu','Napravite osnovu i dodatke po izboru'],jsonb_build_object('caseInitializer','digital_model','geometryProvenance','internal-synthetic-educational','noPatientData',true,'materialPreset','educational-model','supplied',jsonb_build_object('en',array['Immutable synthetic raw scan','Editable working model'],'sr',array['Neizmenjivi sintetički izvorni sken','Radni model koji se može uređivati'])))
) v(domain_slug,slug,title_en,title_sr,description_en,description_sr,code,indication_en,indication_sr,requirements_en,requirements_sr,metadata)
join public.content_domains d on d.slug=v.domain_slug left join public.scenarios s on s.slug=v.slug
on conflict(slug) do update set difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,description_en=excluded.description_en,description_sr=excluded.description_sr,patient_code=excluded.patient_code,indication_en=excluded.indication_en,indication_sr=excluded.indication_sr,tooth_numbers=excluded.tooth_numbers,requirements_en=excluded.requirements_en,requirements_sr=excluded.requirements_sr,additional_metadata=excluded.additional_metadata,random_eligible=true,status='published',published_at=coalesce(public.scenarios.published_at,now());
