-- Phase 19 Partial Denture workflow. All case geometry is generated in Prostheia.
-- The generated models and framework parts are synthetic education assets only.

insert into public.tool_definitions (id,category,label_en,label_sr,short_description_en,short_description_sr,explanation_en,explanation_sr,status)
values
 ('partial_denture_survey','analysis','Survey and undercut preview','Analiza i prikaz podminiranih regija','Inspect model orientation and directional clearance in the shared analysis worker.','Pregledajte orijentaciju modela i smerni prolaz u zajedničkoj analizi.','Survey results are a reusable, non-destructive orientation and ray-clearance preview; they do not measure clinical undercut depth.','Rezultat analize je ponovo upotrebljiv, nedestruktivan prikaz orijentacije i prolaza zraka; ne meri kliničku dubinu podminiranja.','published'),
 ('partial_denture_framework','workflow','Partial Denture framework','Skelet parcijalne proteze','Create registered framework components with stable IDs and abutment relationships.','Kreirajte registrovane komponente skeleta sa stabilnim ID-jevima i odnosima prema nosačima.','Major connectors, lingual bars, rests, clasps, minor connectors, blockout and support features use the shared CAD scene and history.','Glavni spoj, lingvalni lukovi, oslonci, kukice, sporedni spojevi, blokiranje i potporne komponente koriste zajedničku CAD scenu i istoriju.','published')
on conflict (id) do update set category=excluded.category,label_en=excluded.label_en,label_sr=excluded.label_sr,short_description_en=excluded.short_description_en,short_description_sr=excluded.short_description_sr,explanation_en=excluded.explanation_en,explanation_sr=excluded.explanation_sr,status='published';

insert into public.practice_modules (id,slug,title_en,title_sr,summary_en,summary_sr,sort_order,status)
values ('b7190000-0000-4000-8000-000000000001','partial_denture','Partial Denture','Parcijalna proteza','Survey four synthetic Kennedy case types and assemble editable partial framework components in the shared CAD workspace.','Analizirajte četiri sintetička Kennedy tipa i sastavite komponente skeleta u zajedničkom CAD prostoru.',70,'published')
on conflict (slug) do update set title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,sort_order=excluded.sort_order,status='published';

insert into public.practice_lessons (id,module_id,slug,difficulty,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,estimated_minutes,case_setup,sort_order,status)
select seed.id,module.id,seed.slug,seed.difficulty::public.difficulty_level,seed.title_en,seed.title_sr,seed.summary_en,seed.summary_sr,seed.goal_en,seed.goal_sr,seed.minutes,
 jsonb_build_object('source','partial-denture-case','kennedyClass',seed.kennedy_class,'objectMappings',jsonb_build_array()),seed.sort_order,'published'
from (values
 ('b7190000-0000-4000-8000-000000000010'::uuid,'kennedy_class_i','I','beginner',10,'Kennedy Class I · Bilateral distal extension','Kennedy klasa I · Obostrani slobodni završeci','Survey bilateral posterior spaces and plan a synthetic lower framework.','Analizirajte obostrane bočne bezube prostore i isplanirajte sintetički donji skelet.','Inspect a bilateral distal-extension case using the shared insertion direction and registered framework tools.','Pregledajte slučaj obostranog slobodnog završetka koristeći zajednički smer insercije i registrovane alate skeleta.',15),
 ('b7190000-0000-4000-8000-000000000011'::uuid,'kennedy_class_ii','II','beginner',20,'Kennedy Class II · Unilateral distal extension','Kennedy klasa II · Jednostrani slobodni završetak','Survey one posterior extension and associate components with its synthetic abutment.','Analizirajte jednostrani bočni slobodni završetak i povežite komponente sa sintetičkim nosačem.','Plan a synthetic framework around the unilateral distal extension using the shared insertion direction and registered framework tools.','Planirajte sintetički skelet oko jednostranog slobodnog završetka koristeći zajednički smer insercije i registrovane alate skeleta.',15),
 ('b7190000-0000-4000-8000-000000000012'::uuid,'kennedy_class_iii','III','intermediate',30,'Kennedy Class III · Bounded edentulous space','Kennedy klasa III · Ograničen bezubi prostor','Review a bounded space between synthetic abutment teeth and build a framework layout.','Pregledajte ograničen prostor između sintetičkih zuba nosača i oblikujte raspored skeleta.','Plan a framework around the bounded edentulous space and review the synthetic abutment relationships.','Isplanirajte skelet oko ograničenog bezubog prostora i pregledajte odnose sintetičkih zuba nosača.',18),
 ('b7190000-0000-4000-8000-000000000013'::uuid,'kennedy_class_iv','IV','intermediate',40,'Kennedy Class IV · Anterior edentulous space','Kennedy klasa IV · Prednji bezubi prostor','Inspect the anterior space and review connector and support relationships.','Pregledajte prednji bezubi prostor i odnose spojeva i potpornih elemenata.','Plan a framework for the anterior edentulous space and review connector and support relationships.','Isplanirajte skelet za prednji bezubi prostor i pregledajte odnose spojeva i potpornih elemenata.',18)
) seed(id,slug,kennedy_class,difficulty,sort_order,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,minutes)
join public.practice_modules module on module.slug='partial_denture'
on conflict (slug) do update set module_id=excluded.module_id,difficulty=excluded.difficulty::public.difficulty_level,title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,goal_en=excluded.goal_en,goal_sr=excluded.goal_sr,estimated_minutes=excluded.estimated_minutes,case_setup=excluded.case_setup,sort_order=excluded.sort_order,status='published';

create or replace function pg_temp.seed_phase19_step(p_lesson_slug text,p_slug text,p_order integer,p_title_en text,p_title_sr text,p_instruction_en text,p_instruction_sr text,p_theory_en text,p_theory_sr text,p_tools text[],p_targets text[],p_validator jsonb,p_hints jsonb)
returns void language plpgsql as $$
declare lesson_key uuid;step_key uuid;validator_key uuid;hint_value jsonb;tool_value text;validator_type public.validator_type;
begin
 select id into strict lesson_key from public.practice_lessons where slug=p_lesson_slug;
 insert into public.practice_steps(lesson_id,slug,sort_order,title_en,title_sr,instructions_en,instructions_sr,theory_en,theory_sr,target_object_ids,reference_modes,reference_config,example_config,required)
 values(lesson_key,p_slug,p_order,p_title_en,p_title_sr,p_instruction_en,p_instruction_sr,p_theory_en,p_theory_sr,p_targets,array['off','outline','transparent','full'],null,jsonb_build_object('label_en','Synthetic framework example','label_sr','Sintetički primer skeleta','mode','outline'),true)
 on conflict(lesson_id,slug) do update set sort_order=excluded.sort_order,title_en=excluded.title_en,title_sr=excluded.title_sr,instructions_en=excluded.instructions_en,instructions_sr=excluded.instructions_sr,theory_en=excluded.theory_en,theory_sr=excluded.theory_sr,target_object_ids=excluded.target_object_ids,reference_modes=excluded.reference_modes,example_config=excluded.example_config,required=true returning id into step_key;
 delete from public.practice_hints where step_id=step_key; delete from public.practice_step_tools where step_id=step_key; delete from public.practice_step_validations where step_id=step_key;
 foreach tool_value in array p_tools loop insert into public.practice_step_tools(step_id,tool_id) values(step_key,tool_value) on conflict do nothing; end loop;
 validator_type:=case when p_validator->>'type'='partial_denture_setup' then 'custom'::public.validator_type else (p_validator->>'type')::public.validator_type end;
 insert into public.validation_configs(slug,validator_type,config,status) values('partial_denture_'||p_lesson_slug||'_'||p_slug,validator_type,p_validator,'published') on conflict(slug) do update set validator_type=excluded.validator_type,config=excluded.config,status='published' returning id into validator_key;
 insert into public.practice_step_validations(step_id,validation_config_id,sort_order) values(step_key,validator_key,10);
 for hint_value in select value from jsonb_array_elements(coalesce(p_hints,'[]'::jsonb)) loop
  insert into public.practice_hints(step_id,slug,sort_order,title_en,title_sr,body_en,body_sr) values(step_key,hint_value->>'slug',(hint_value->>'order')::integer,hint_value->>'title_en',hint_value->>'title_sr',hint_value->>'body_en',hint_value->>'body_sr');
 end loop;
end $$;

select pg_temp.seed_phase19_step('kennedy_class_i','surveying',10,'Survey the arch','Analizirajte luk','Select the synthetic arch, set its insertion direction in the Partial Denture controls, then choose Insertion direction in Inspect and preview the path. Review the colored result without editing the source mesh.','Izaberite sintetički luk, podesite smer insercije u kontrolama parcijalne proteze, zatim izaberite Insertion direction u Inspect i prikažite put. Pregledajte obojeni rezultat bez izmene izvornog mesh-a.','This shared analysis combines surface orientation with a directional self-clearance ray preview. It is not a clinical undercut-depth measurement.','Ova zajednička analiza kombinuje orijentaciju površine sa smernim prikazom prolaza zraka. Ne meri kliničku dubinu podminiranja.',array['select','camera','analysis','scene'],array['partial-denture-synthetic-lower-arch'],'{"type":"partial_denture_setup","check":"survey","kennedyClass":"I"}'::jsonb,'[{"slug":"direction","order":10,"title_en":"Choose the path","title_sr":"Izaberite put","body_en":"Set one of the shared X, Y or Z insertion axes, then run Preview path on the selected synthetic arch.","body_sr":"Podesite zajedničku X, Y ili Z osu insercije, pa pokrenite Preview path na izabranom sintetičkom luku."},{"slug":"interpretation","order":20,"title_en":"Read it as a preview","title_sr":"Tumačite kao prikaz","body_en":"The map indicates orientation and directional obstruction only. It does not report undercut depth.","body_sr":"Mapa prikazuje samo orijentaciju i smernu prepreku. Ne prikazuje dubinu podminiranja."}]');
select pg_temp.seed_phase19_step('kennedy_class_i','blockout',20,'Review blockout and support regions','Pregledajte blokiranje i potporne regije','Choose Blockout in the Partial Denture controls and add the synthetic blockout component. Select it in Scene, inspect it against the arch, and use Undo/Redo to review the edit.','U kontrolama parcijalne proteze izaberite Blockout i dodajte sintetičku komponentu blokiranja. Izaberite je u Scene, pregledajte u odnosu na luk i koristite Undo/Redo za proveru izmene.','Blockout geometry is a separate registered training component. It does not alter or repair the surveyed arch mesh.','Geometrija blokiranja je zasebna registrovana komponenta za obuku. Ne menja niti popravlja analizirani mesh luka.',array['select','camera','scene','analysis'],array['partial-denture-synthetic-lower-arch'],'{"type":"required_step","message":{"en":"Inspect the blockout component against the synthetic arch.","sr":"Pregledajte komponentu blokiranja u odnosu na sintetički luk."}}'::jsonb,'[{"slug":"separate-object","order":10,"title_en":"Check the Scene Tree","title_sr":"Proverite Scene Tree","body_en":"Blockout is a distinct editable CAD object with its own stable ID and geometry history.","body_sr":"Blokiranje je zaseban CAD objekat koji se može menjati, sa sopstvenim stabilnim ID-jem i istorijom geometrije."}]');
select pg_temp.seed_phase19_step('kennedy_class_i','framework_components',30,'Plan rests, clasps and connectors','Planirajte oslonce, kukice i spojeve','Add one Rest, Clasp, Minor connector, Guide plane and Finish line for each shown abutment. Inspect the stored tooth association in each Scene object.','Dodajte Rest, Clasp, Minor connector, Guide plane i Finish line za svaki prikazani zub nosač. Pregledajte vezu sa zubom u svakom Scene objektu.','Each framework member has a stable CAD object ID. Tooth relationships are stored as IDs and do not depend on display names or Three.js parents.','Svaki član skeleta ima stabilan ID CAD objekta. Odnos prema zubu čuva se putem ID-ja i ne zavisi od naziva ni Three.js roditelja.',array['select','move','rotate','camera','scene'],array['partial-denture-synthetic-tooth-35','partial-denture-synthetic-tooth-45'],'{"type":"partial_denture_setup","check":"framework","kennedyClass":"I"}'::jsonb,'[{"slug":"abutment","order":10,"title_en":"Choose a shown abutment","title_sr":"Izaberite prikazani zub nosač","body_en":"Use the abutment selector before adding a tooth-associated part.","body_sr":"Pre dodavanja komponente vezane za zub koristite izbor zuba nosača."}]');
select pg_temp.seed_phase19_step('kennedy_class_i','framework_review',40,'Review the framework','Pregledajte skelet','Review the major connector, lingual bar, retention mesh, tooth-related framework parts, relief and current survey preview. Use shared Section, Measure, transforms and export tools where useful.','Pregledajte glavni spoj, lingvalni luk, retencionu mrežicu, komponente povezane sa zubima, rasterećenje i aktuelni prikaz analize. Po potrebi koristite zajedničke alate Section, Measure, transformacije i izvoz.','All generated shapes are synthetic educational geometry and are not manufacturing-ready or clinically validated.','Svi generisani oblici su sintetička edukativna geometrija i nisu spremni za proizvodnju niti klinički validirani.',array['select','move','rotate','analysis','camera','scene'],array['partial-denture-synthetic-lower-arch'],'{"type":"partial_denture_setup","check":"complete_case","kennedyClass":"I"}'::jsonb,'[{"slug":"design-check","order":10,"title_en":"Run Design Check","title_sr":"Pokrenite Design Check","body_en":"If a component is missing, the check names the required framework relationship or analysis state.","body_sr":"Ako komponenta nedostaje, provera navodi potrebnu vezu skeleta ili stanje analize."}]');

-- Case II–IV reuse the same four reusable CAD exercises with a different synthetic Kennedy setup.
do $$ declare klass text; lesson_slug text; prefix text; begin
 foreach klass in array array['II','III','IV'] loop
  lesson_slug:='kennedy_class_'||lower(klass);
  perform pg_temp.seed_phase19_step(lesson_slug,'surveying',10,'Survey the arch','Analizirajte luk','Select the synthetic arch, set its insertion direction in the Partial Denture controls, then choose Insertion direction in Inspect and preview the path. Review the colored result without editing the source mesh.','Izaberite sintetički luk, podesite smer insercije u kontrolama parcijalne proteze, zatim izaberite Insertion direction u Inspect i prikažite put. Pregledajte obojeni rezultat bez izmene izvornog mesh-a.','This shared analysis combines surface orientation with a directional self-clearance ray preview. It is not a clinical undercut-depth measurement.','Ova zajednička analiza kombinuje orijentaciju površine sa smernim prikazom prolaza zraka. Ne meri kliničku dubinu podminiranja.',array['select','camera','analysis','scene'],array['partial-denture-synthetic-lower-arch'],jsonb_build_object('type','partial_denture_setup','check','survey','kennedyClass',klass),'[{"slug":"direction","order":10,"title_en":"Choose the path","title_sr":"Izaberite put","body_en":"Use the shared insertion direction and run a fresh preview after changing it.","body_sr":"Koristite zajednički smer insercije i ponovo pokrenite prikaz nakon izmene."}]'::jsonb);
  perform pg_temp.seed_phase19_step(lesson_slug,'blockout',20,'Review blockout and support regions','Pregledajte blokiranje i potporne regije','Choose Blockout in the Partial Denture controls and add the synthetic blockout component. Select it in Scene, inspect it against the arch, and use Undo/Redo to review the edit.','U kontrolama parcijalne proteze izaberite Blockout i dodajte sintetičku komponentu blokiranja. Izaberite je u Scene, pregledajte u odnosu na luk i koristite Undo/Redo za proveru izmene.','Blockout geometry is separate from the surveyed model and is saved as a registered framework component.','Geometrija blokiranja je odvojena od analiziranog modela i čuva se kao registrovana komponenta skeleta.',array['select','camera','scene','analysis'],array['partial-denture-synthetic-lower-arch'],'{"type":"required_step","message":{"en":"Inspect the blockout component against the synthetic arch.","sr":"Pregledajte komponentu blokiranja u odnosu na sintetički luk."}}'::jsonb,'[{"slug":"separate-object","order":10,"title_en":"Check the Scene Tree","title_sr":"Proverite Scene Tree","body_en":"Blockout keeps its own CAD object identity and history.","body_sr":"Blokiranje zadržava sopstveni identitet CAD objekta i istoriju."}]'::jsonb);
  perform pg_temp.seed_phase19_step(lesson_slug,'framework_components',30,'Plan rests, clasps and connectors','Planirajte oslonce, kukice i spojeve','Add a Rest, Clasp, Minor connector, Guide plane and Finish line for the shown abutments. Inspect the stored tooth association in each Scene object.','Dodajte Rest, Clasp, Minor connector, Guide plane i Finish line za prikazane zube nosače. Pregledajte vezu sa zubom u svakom Scene objektu.','Framework members use stable object IDs and explicit tooth relationships.','Komponente skeleta koriste stabilne ID-jeve objekata i eksplicitne veze sa zubima.',array['select','move','rotate','camera','scene'],array['partial-denture-synthetic-lower-arch'],'{"type":"partial_denture_setup","check":"framework"}'::jsonb,'[{"slug":"abutment","order":10,"title_en":"Select an abutment","title_sr":"Izaberite zub nosač","body_en":"Choose an abutment in the workflow bar before generating associated parts.","body_sr":"Pre generisanja povezanih komponenti izaberite zub nosač u traci postupka."}]'::jsonb);
  perform pg_temp.seed_phase19_step(lesson_slug,'framework_review',40,'Review the framework','Pregledajte skelet','Review the connector, lingual bar, retention mesh, tooth-related framework parts, relief and current survey preview. Use shared Section, Measure, transforms and export tools where useful.','Pregledajte spoj, lingvalni luk, retencionu mrežicu, komponente povezane sa zubima, rasterećenje i aktuelni prikaz analize. Po potrebi koristite zajedničke alate Section, Measure, transformacije i izvoz.','Synthetic demonstration only; no manufacturing or clinical claims are made.','Samo sintetički prikaz; ne iznose se tvrdnje o proizvodnji ili kliničkoj validnosti.',array['select','move','rotate','analysis','camera','scene'],array['partial-denture-synthetic-lower-arch'],'{"type":"partial_denture_setup","check":"complete_case"}'::jsonb,'[{"slug":"design-check","order":10,"title_en":"Run Design Check","title_sr":"Pokrenite Design Check","body_en":"Review any named missing component and rerun the current survey preview if the direction changed.","body_sr":"Pregledajte navedenu komponentu koja nedostaje i ponovo pokrenite analizu ako je smer promenjen."}]'::jsonb);
 end loop;
end $$;

insert into public.scenarios(domain_id,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,patient_age,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,additional_metadata,random_eligible,status,published_at)
select domain.id,'synthetic_kennedy_class_'||lower(seed.klass),seed.difficulty::public.difficulty_level,'Partial denture · Kennedy Class '||seed.klass,'Parcijalna proteza · Kennedy klasa '||seed.klass,seed.description_en,seed.description_sr,'PT-RPD-'||seed.klass,null,'Educational removable partial denture · Kennedy Class '||seed.klass,'Edukativna parcijalna mobilna proteza · Kennedy klasa '||seed.klass,seed.teeth::smallint[],array['Survey the arch with the shared insertion direction','Inspect the directional undercut preview','Modify framework parts independently'],array['Analizirajte luk zajedničkim smerom insercije','Pregledajte smerni prikaz podminiranja','Samostalno menjajte komponente skeleta'],jsonb_build_object('caseInitializer','partial_denture','kennedyClass',seed.klass,'geometryProvenance','internal-synthetic-educational','noPatientData',true,'materialPreset','educational-framework','material',jsonb_build_object('en','Educational framework visualization','sr','Edukativni prikaz skeleta'),'supplied',jsonb_build_object('en',array['Synthetic mandibular arch','Synthetic remaining teeth','Generated support regions'],'sr',array['Sintetička mandibularna vilica','Sintetički preostali zubi','Generisane potporne regije']),'notes',jsonb_build_object('en','Internally generated educational geometry only. No patient data or external dental model library. Not clinically validated.','sr','Samo interno generisana edukativna geometrija. Nema podataka pacijenta ni spoljne biblioteke dentalnih modela. Nije klinički validirana.')),true,'published',now()
from (values ('I','beginner',array[36,37,38,46,47,48], 'Independent framework planning on a bilateral distal-extension synthetic arch.','Samostalno planiranje skeleta na sintetičkom luku sa obostranim slobodnim završecima.'),('II','beginner',array[46,47,48], 'Independent framework planning on a unilateral distal-extension synthetic arch.','Samostalno planiranje skeleta na sintetičkom luku sa jednostranim slobodnim završetkom.'),('III','intermediate',array[36,37], 'Independent framework planning around a bounded synthetic edentulous space.','Samostalno planiranje skeleta oko ograničenog sintetičkog bezubog prostora.'),('IV','intermediate',array[31,32,41,42], 'Independent framework planning around an anterior synthetic edentulous space.','Samostalno planiranje skeleta oko prednjeg sintetičkog bezubog prostora.')) seed(klass,difficulty,teeth,description_en,description_sr)
join public.content_domains domain on domain.slug='partial_denture'
on conflict(slug) do update set difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,description_en=excluded.description_en,description_sr=excluded.description_sr,patient_code=excluded.patient_code,patient_age=null,indication_en=excluded.indication_en,indication_sr=excluded.indication_sr,tooth_numbers=excluded.tooth_numbers,requirements_en=excluded.requirements_en,requirements_sr=excluded.requirements_sr,additional_metadata=excluded.additional_metadata,random_eligible=true,status='published',published_at=coalesce(public.scenarios.published_at,now());
