-- Phase 16 Crown curriculum and reusable synthetic training scenario.
-- No commercial or third-party dental model data is included. Geometry is
-- generated in src/cad/crown/geometry.ts and initialized by the shared CAD runtime.

insert into public.tool_definitions (id, category, label_en, label_sr, short_description_en, short_description_sr, explanation_en, explanation_sr, status)
values
  ('margin', 'curve', 'Margin Line', 'Margin Line', 'Place and edit points on the preparation surface.', 'Postavljajte i menjajte tačke na površini preparacije.', 'The shared curve editor stores a non-destructive boundary associated with a CAD object.', 'Zajednički editor krivih čuva nedestruktivnu granicu povezanu sa CAD objektom.', 'published'),
  ('insertion_path', 'analysis', 'Insertion Path', 'Put insercije', 'Preview directional surface orientation for a selected axis.', 'Prikažite orijentaciju površine za izabranu osu.', 'This educational preview is directional and does not make a clinical undercut determination.', 'Ovaj edukativni prikaz je smerni i ne određuje klinički podminirana mesta.', 'published'),
  ('thickness', 'analysis', 'Thickness', 'Debljina', 'Inspect ray-based thickness samples on closed geometry.', 'Pregledajte debljinu zasnovanu na zracima na zatvorenoj geometriji.', 'Open or ambiguous meshes report thickness as unavailable.', 'Otvoreni ili dvosmisleni mesh-evi prikazuju debljinu kao nedostupnu.', 'published')
on conflict (id) do update set category=excluded.category,label_en=excluded.label_en,label_sr=excluded.label_sr,short_description_en=excluded.short_description_en,short_description_sr=excluded.short_description_sr,explanation_en=excluded.explanation_en,explanation_sr=excluded.explanation_sr,status='published';

insert into public.practice_modules (id, slug, title_en, title_sr, summary_en, summary_sr, sort_order, status)
values ('b7160000-0000-4000-8000-000000000001','crown_workflow','Crown Workflow','Crown Workflow','A guided single-crown case using synthetic dental geometry and the shared CAD workspace.','Vođeni slučaj pojedinačne krunice uz sintetičku dentalnu geometriju i zajednički CAD prostor.',20,'published')
on conflict (slug) do update set title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,sort_order=excluded.sort_order,status='published';

insert into public.practice_lessons (id,module_id,slug,difficulty,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,estimated_minutes,case_setup,sort_order,status)
select seed.id,module.id,seed.slug,seed.difficulty::public.difficulty_level,seed.title_en,seed.title_sr,seed.summary_en,seed.summary_sr,seed.goal_en,seed.goal_sr,seed.minutes,
  '{"source":"crown-case","objectMappings":[{"runtimeObjectId":"crown26-preparation","semanticRole":"prepared_tooth","editable":false},{"runtimeObjectId":"crown26-adjacent-25","semanticRole":"tooth","editable":false},{"runtimeObjectId":"crown26-antagonist-36","semanticRole":"antagonist","editable":false},{"runtimeObjectId":"crown26-restoration","semanticRole":"crown","editable":true},{"runtimeObjectId":"crown26-reference","semanticRole":"reference","editable":false}]}'::jsonb,
  seed.sort_order,'published'
from public.practice_modules module cross join (values
  ('b7160000-0000-4000-8000-000000000010'::uuid,'margin','foundation',10,'Margin Line','Margin Line','Define and inspect a manual boundary on a synthetic preparation.','Definišite i pregledajte ručno iscrtanu granicu na sintetičkoj preparaciji.','Place, edit and close a Margin Line without changing the scan surface.','Postavite, izmenite i zatvorite Margin Line bez izmene površine skena.',7),
  ('b7160000-0000-4000-8000-000000000011'::uuid,'insertion_path','foundation',20,'Insertion Path and Undercut Preview','Put insercije i prikaz podminiranja','Inspect how a selected direction relates to surface orientation.','Pregledajte kako izabrani smer utiče na orijentaciju površine.', 'Run the direction-based preview and recognize its educational limits.','Pokrenite smerni prikaz i prepoznajte njegova edukativna ograničenja.',6),
  ('b7160000-0000-4000-8000-000000000012'::uuid,'placement','beginner',30,'Crown Placement','Pozicioniranje krunice','Move and rotate the synthetic restoration while keeping case objects aligned.','Pomerajte i rotirajte sintetičku restauraciju uz očuvanje poravnanja slučaja.','Adjust the restoration using the shared transform and numeric controls.','Podesite restauraciju zajedničkim alatima za transformaciju i numeričkim kontrolama.',7),
  ('b7160000-0000-4000-8000-000000000013'::uuid,'contacts','beginner',40,'Proximal and Antagonist Relationships','Proksimalni odnos i antagonist','Compare the crown with its adjacent tooth and static antagonist geometry.','Uporedite krunicu sa susednim zubom i statičkom geometrijom antagoniste.','Run explicit proximity analyses for the exercise object pairs.','Pokrenite analize blizine za parove objekata ove vežbe.',8),
  ('b7160000-0000-4000-8000-000000000014'::uuid,'sculpt','intermediate',50,'Crown Morphology Sculpt','Oblikovanje morfologije krunice','Use the shared sculpt brush to adjust synthetic occlusal morphology.','Koristite zajedničku Sculpt četkicu za podešavanje sintetičke okluzalne morfologije.','Practice Add, Remove, Smooth, Flatten and Morph on the editable restoration.','Vežbajte Add, Remove, Smooth, Flatten i Morph na restauraciji koja se može menjati.',9),
  ('b7160000-0000-4000-8000-000000000015'::uuid,'thickness','intermediate',60,'Section and Thickness Inspection','Pregled preseka i debljine','Inspect a Section view and run thickness only on the closed training restoration.','Pregledajte Section i pokrenite analizu debljine samo na zatvorenoj probnoj restauraciji.','Read the exercise target and distinguish unavailable results from measured results.','Pročitajte cilj vežbe i razlikujte nedostupne rezultate od izmerenih.',8),
  ('b7160000-0000-4000-8000-000000000016'::uuid,'full_crown_case','intermediate',70,'Full Crown Case','Kompletan slučaj krunice','Complete the case using the Margin Line, transforms, sculpt and explicit analyses.','Završite slučaj pomoću Margin Line, transformacija, Sculpt alata i eksplicitnih analiza.','Complete a synthetic single-crown workflow and pass each configured Design Check.','Završite sintetički postupak izrade pojedinačne krunice i prođite svaku podešenu Design Check proveru.',18)
) as seed(id,slug,difficulty,sort_order,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,minutes)
where module.slug='crown_workflow'
on conflict (slug) do update set module_id=excluded.module_id,difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,goal_en=excluded.goal_en,goal_sr=excluded.goal_sr,estimated_minutes=excluded.estimated_minutes,case_setup=excluded.case_setup,sort_order=excluded.sort_order,status='published';

create or replace function pg_temp.seed_phase16_step(
  p_lesson_slug text,p_slug text,p_order integer,p_title_en text,p_title_sr text,p_instruction_en text,p_instruction_sr text,p_theory_en text,p_theory_sr text,
  p_tools text[],p_targets text[],p_reference_modes text[],p_reference_config jsonb,p_example_config jsonb,p_validator jsonb,p_hints jsonb
) returns void language plpgsql as $$
declare lesson_key uuid;step_key uuid;validator_key uuid;hint_value jsonb;tool_value text;validator_type public.validator_type;
begin
  select id into strict lesson_key from public.practice_lessons where slug=p_lesson_slug;
  insert into public.practice_steps(lesson_id,slug,sort_order,title_en,title_sr,instructions_en,instructions_sr,theory_en,theory_sr,target_object_ids,reference_modes,reference_config,example_config,required)
  values(lesson_key,p_slug,p_order,p_title_en,p_title_sr,p_instruction_en,p_instruction_sr,p_theory_en,p_theory_sr,p_targets,p_reference_modes,p_reference_config,p_example_config,true)
  on conflict(lesson_id,slug) do update set sort_order=excluded.sort_order,title_en=excluded.title_en,title_sr=excluded.title_sr,instructions_en=excluded.instructions_en,instructions_sr=excluded.instructions_sr,theory_en=excluded.theory_en,theory_sr=excluded.theory_sr,target_object_ids=excluded.target_object_ids,reference_modes=excluded.reference_modes,reference_config=excluded.reference_config,example_config=excluded.example_config,required=true returning id into step_key;
  delete from public.practice_hints where step_id=step_key;
  delete from public.practice_step_tools where step_id=step_key;
  delete from public.practice_step_validations where step_id=step_key;
  foreach tool_value in array p_tools loop insert into public.practice_step_tools(step_id,tool_id) values(step_key,tool_value) on conflict do nothing; end loop;
  if p_validator is not null then
    validator_type:=case when p_validator->>'type'='analysis_target' then 'custom'::public.validator_type else (p_validator->>'type')::public.validator_type end;
    insert into public.validation_configs(slug,validator_type,config,status) values('crown_'||p_lesson_slug||'_'||p_slug||'_check',validator_type,p_validator,'published')
    on conflict(slug) do update set validator_type=excluded.validator_type,config=excluded.config,status='published' returning id into validator_key;
    insert into public.practice_step_validations(step_id,validation_config_id,sort_order) values(step_key,validator_key,10);
  end if;
  for hint_value in select value from jsonb_array_elements(coalesce(p_hints,'[]'::jsonb)) loop
    insert into public.practice_hints(step_id,slug,sort_order,title_en,title_sr,body_en,body_sr) values(step_key,hint_value->>'slug',(hint_value->>'order')::integer,hint_value->>'title_en',hint_value->>'title_sr',hint_value->>'body_en',hint_value->>'body_sr');
  end loop;
end $$;

select pg_temp.seed_phase16_step('margin','draw_margin',10,'Place a Margin Line','Postavite Margin Line',
  'Select Preparation · 26 as the Margin Line target. Use Place points and click at least three points directly on its surface. Close the loop, then run Design Check.','Izaberite Preparation · 26 kao cilj za Margin Line. Uključite Place points i postavite najmanje tri tačke direktno na površinu. Zatvorite petlju, pa pokrenite Design Check.',
  'Margin Line is a reusable curve associated with its CAD object. Picked points are projected from the selected preparation surface and stored in its local coordinates. The scan mesh is not edited.','Margin Line je zajednička kriva povezana sa CAD objektom. Izabrane tačke projektuju se sa površine odabrane preparacije i čuvaju u njenim lokalnim koordinatama. Mesh skena se ne menja.',
  array['select','camera','scene','analysis'],array['crown26-preparation'],array['off','outline','transparent'], '{"objectId":"crown26-reference","position":[0,0,0]}',
  '{"label_en":"Synthetic training Margin Line","label_sr":"Sintetička Margin Line za vežbu","mode":"outline"}',
  '{"type":"margin_complete","objectId":"crown26-preparation"}',
  '[{"slug":"choose-preparation","order":10,"title_en":"Choose the target surface","title_sr":"Izaberite ciljnu površinu","body_en":"The margin tool accepts points only from Preparation · 26. If another object is picked, select the preparation row in Scene first.","body_sr":"Alat za margin prihvata tačke samo sa Preparation · 26. Ako izaberete drugi objekat, prvo izaberite preparaciju u panelu Scene."},{"slug":"close-loop","order":20,"title_en":"Finish the loop","title_sr":"Zatvorite petlju","body_en":"Place three or more points, then use Close. Select a point and choose Edit point to reposition it on the same surface.","body_sr":"Postavite tri ili više tačaka, pa izaberite Close. Izaberite tačku i upotrebite Edit point da je premestite na istoj površini."}]');

select pg_temp.seed_phase16_step('insertion_path','directional_preview',10,'Preview an insertion direction','Prikažite smer insercije',
  'Select Preparation · 26 for the analysis target and choose +Z under Insertion direction. Run Preview path, then orbit the preparation to inspect the directional color preview.','Za cilj analize izaberite Preparation · 26 i odaberite +Z u polju Insertion direction. Pokrenite Preview path, pa orbitirajte oko preparacije i pregledajte smerni prikaz bojama.',
  'This is a direction-based surface-orientation preview. It does not calculate clinical undercuts and is not a virtual articulator.','Ovo je smerni prikaz orijentacije površine. Ne izračunava klinička podminiranja i nije virtualni artikulator.',
  array['select','camera','analysis'],array['crown26-preparation'],array['off','outline','transparent'],null,
  '{"label_en":"Preparation and chosen path axis","label_sr":"Preparacija i izabrana osa putanje","mode":"outline"}',
  '{"type":"analysis_target","kind":"undercut","objectIds":["crown26-preparation"]}',
  '[{"slug":"axis","order":10,"title_en":"Choose a direction","title_sr":"Izaberite smer","body_en":"Use the insertion-direction control to compare +Z, +X and +Y. The preview shows face orientation only.","body_sr":"Pomoću kontrole smera insercije uporedite +Z, +X i +Y. Prikaz pokazuje samo orijentaciju lica."},{"slug":"limits","order":20,"title_en":"Interpret the preview carefully","title_sr":"Pažljivo tumačite prikaz","body_en":"A colored region is not a clinically validated undercut map. Use the selected axis as an exercise input.","body_sr":"Obojeni region nije klinički potvrđena mapa podminiranja. Izabranu osu koristite kao ulazni podatak za vežbu."}]');

select pg_temp.seed_phase16_step('placement','position_restoration',10,'Position the restoration','Pozicionirajte restauraciju',
  'Select Crown restoration · 26, choose Place from tooth library to load the synthetic posterior preset, then set Z to 1.5 mm using Properties or Move. This is an exercise target, not a universal clinical value.','Izaberite Crown restoration · 26, odaberite Place from tooth library da učitate sintetički bočni preset, pa podesite Z na 1,5 mm pomoću Properties ili Move. Ovo je cilj vežbe, a ne univerzalna klinička vrednost.',
  'The preparation, adjacent tooth and antagonist keep their shared case coordinates. The library preset loads into the editable restoration, which you then position.','Preparacija, susedni zub i antagonist zadržavaju zajedničke koordinate slučaja. Bibliotečki preset učitava se u restauraciju koja se može uređivati, a nju zatim pozicionirate.',
  array['select','move','rotate','camera','scene'],array['crown26-restoration'],array['off','outline','transparent','full'], '{"objectId":"crown26-reference","position":[0,0,0]}',
  '{"label_en":"Target for this exercise · restoration position","label_sr":"Cilj ove vežbe · položaj restauracije","mode":"outline"}',
  '{"type":"transform_range","objectId":"crown26-restoration","field":"position","position":[0,0,1.5],"axes":["z"],"toleranceMm":0.2}',
  '[{"slug":"library","order":10,"title_en":"Load anatomy from the library","title_sr":"Učitajte anatomiju iz biblioteke","body_en":"Place from tooth library loads the internally generated posterior crown preset into the editable restoration. Undo restores the previous geometry.","body_sr":"Place from tooth library učitava interno generisani preset bočne krunice u restauraciju koja se može uređivati. Undo vraća prethodnu geometriju."},{"slug":"numeric-field","order":20,"title_en":"Position with numeric controls","title_sr":"Pozicionirajte numeričkim kontrolama","body_en":"The Properties panel keeps the coordinates visible while you make a controlled move.","body_sr":"Panel Properties prikazuje koordinate dok obavljate kontrolisano pomeranje."},{"slug":"reference","order":30,"title_en":"Compare the example","title_sr":"Uporedite sa primerom","body_en":"Use Outline or Transparent to inspect the protected synthetic example. Return to Off when finished.","body_sr":"Upotrebite Outline ili Transparent da pregledate zaštićeni sintetički primer. Kada završite, vratite Off."}]');

select pg_temp.seed_phase16_step('contacts','adjacent_proximity',10,'Inspect the proximal relationship','Pregledajte proksimalni odnos',
  'Choose Crown restoration · 26 and Adjacent tooth · 25 as the analysis pair. Run Proximity map. For this exercise, the nearest-surface target is no more than 1.5 mm.','Izaberite Crown restoration · 26 i Adjacent tooth · 25 kao par za analizu. Pokrenite Proximity map. Za ovu vežbu cilj za najkraće rastojanje površina nije veći od 1,5 mm.',
  'The map reports nearest-surface distances. The exercise threshold is lesson configuration and is not a universal clinical contact value.','Mapa prikazuje rastojanja do najbliže površine. Prag vežbe je podešen u lekciji i nije univerzalna klinička vrednost kontakta.',
  array['select','move','rotate','analysis','camera'],array['crown26-restoration','crown26-adjacent-25'],array['off','outline','transparent'],null,
  '{"label_en":"Target for this exercise · proximal relationship","label_sr":"Cilj ove vežbe · proksimalni odnos","mode":"outline"}',
  '{"type":"analysis_target","kind":"contact","objectIds":["crown26-restoration","crown26-adjacent-25"],"maxValue":1.5}',
  '[{"slug":"pair","order":10,"title_en":"Check the object pair","title_sr":"Proverite par objekata","body_en":"The nearest-distance map uses the selected objects. Check that restoration is first and adjacent tooth is second.","body_sr":"Mapa najkraćeg rastojanja koristi izabrane objekte. Proverite da je restauracija prva, a susedni zub drugi."},{"slug":"static-antagonist","order":20,"title_en":"Inspect the antagonist separately","title_sr":"Posebno pregledajte antagonistu","body_en":"Static proximity compares the crown to the placed antagonist. It does not simulate jaw movement.","body_sr":"Statička blizina poredi krunicu sa postavljenom antagonistom. Ne simulira kretanje vilice."}]');

select pg_temp.seed_phase16_step('contacts','occlusal_proximity',20,'Inspect the static occlusal relationship','Pregledajte statički okluzalni odnos',
  'Choose Crown restoration · 26 and Antagonist · 36 as the analysis pair. Run Proximity map and read the closest-surface range.','Izaberite Crown restoration · 26 i Antagonist · 36 kao par za analizu. Pokrenite Proximity mapu i pregledajte opseg najkraćeg rastojanja površina.',
  'This compares supplied static geometry. It does not calculate dynamic occlusion, jaw motion or articulator contacts.','Ovo poredi zadatu statičku geometriju. Ne izračunava dinamičku okluziju, pokrete vilice ili kontakte artikulatora.',
  array['select','analysis','camera'],array['crown26-restoration','crown26-antagonist-36'],array['off','outline','transparent'],null,
  '{"label_en":"Target for this exercise · static antagonist relationship","label_sr":"Cilj ove vežbe · statički odnos sa antagonistom","mode":"outline"}',
  '{"type":"analysis_target","kind":"contact","objectIds":["crown26-restoration","crown26-antagonist-36"]}',
  '[{"slug":"static-contact","order":10,"title_en":"Use a static comparison","title_sr":"Koristite statičko poređenje","body_en":"The analysis uses the restoration and antagonist in their current poses. It does not move either jaw.","body_sr":"Analiza koristi restauraciju i antagonistu u njihovim trenutnim položajima. Ne pomera nijednu vilicu."}]');

select pg_temp.seed_phase16_step('sculpt','restore_morphology',10,'Adjust synthetic crown morphology','Podesite sintetičku morfologiju krunice',
  'Select Crown restoration · 26 and make one short Add or Smooth stroke. Undo once and compare the surface. Try Flatten or Morph only after selecting the restoration again.','Izaberite Crown restoration · 26 i napravite jedan kratak potez alatima Add ili Smooth. Jednom upotrebite Undo i uporedite površinu. Alate Flatten ili Morph probajte tek nakon ponovnog izbora restauracije.',
  'The crown is a synthetic editable mesh in the shared Geometry Registry. The existing sculpt engine creates mesh revisions and Undo history.','Krunica je sintetički mesh koji se može menjati u zajedničkom Geometry Registry-ju. Postojeći Sculpt engine pravi revizije mesh-a i Undo istoriju.',
  array['select','sculpt','camera'],array['crown26-restoration'],array['off','outline','transparent','full'],'{"objectId":"crown26-reference","position":[0,0,0]}',
  '{"label_en":"Synthetic morphology example","label_sr":"Sintetički primer morfologije","mode":"outline"}',
  '{"type":"required_object","objectId":"crown26-restoration","minGeometryRevision":1}',
  '[{"slug":"small-stroke","order":10,"title_en":"Start with a small stroke","title_sr":"Počnite malim potezom","body_en":"Choose a small brush size and lower strength. A short stroke is easier to compare and undo.","body_sr":"Izaberite malu četkicu i smanjite jačinu. Kratak potez je lakše uporediti i poništiti."},{"slug":"reference-mode","order":20,"title_en":"Inspect the example","title_sr":"Pregledajte primer","body_en":"Show Example is temporary. Hide it before deciding whether your edited surface needs another pass.","body_sr":"Show Example je privremen prikaz. Sakrijte ga pre odluke da li izmenjenoj površini treba još jedan potez."}]');

select pg_temp.seed_phase16_step('thickness','section_and_thickness',10,'Inspect section and thickness','Pregledajte Section i debljinu',
  'Enable Section and slide its plane across the restoration. Then choose Crown restoration · 26, select Thickness and run analysis. Target for this exercise: the minimum measured sample is at least 0.8 mm.','Uključite Section i pomerajte ravan kroz restauraciju. Zatim izaberite Crown restoration · 26, odaberite Thickness i pokrenite analizu. Cilj ove vežbe: najmanji izmereni uzorak je najmanje 0,8 mm.',
  'Thickness uses rays through a closed training surface. Open or ambiguous geometry returns an unavailable warning; Section only clips the view.','Debljina se meri zracima kroz zatvorenu probnu površinu. Otvorena ili dvosmislena geometrija vraća upozorenje o nedostupnosti; Section samo odseca prikaz.',
  array['select','analysis','camera'],array['crown26-restoration'],array['off','outline','transparent'],null,
  '{"label_en":"Target for this exercise · thickness inspection","label_sr":"Cilj ove vežbe · pregled debljine","mode":"outline"}',
  '{"type":"analysis_target","kind":"thickness","objectIds":["crown26-restoration"],"minValue":0.8}',
  '[{"slug":"section","order":10,"title_en":"Section is non-destructive","title_sr":"Section ne menja mesh","body_en":"Use Section to inspect a cross-section. It does not trim or delete the source geometry.","body_sr":"Upotrebite Section za pregled preseka. Ne trimuje niti briše izvornu geometriju."},{"slug":"unavailable","order":20,"title_en":"Read unavailable states honestly","title_sr":"Ispravno tumačite nedostupne rezultate","body_en":"If a mesh is open or ray results are ambiguous, the engine reports thickness as unavailable instead of inventing a value.","body_sr":"Ako je mesh otvoren ili su rezultati zraka dvosmisleni, engine prikazuje debljinu kao nedostupnu umesto da izmisli vrednost."}]');

select pg_temp.seed_phase16_step('full_crown_case','margin_review',10,'Confirm the case boundary','Potvrdite granicu slučaja',
  'Review Preparation · 26 from Top and an oblique view. Confirm that Margin Line is closed and remains on the preparation.','Pregledajte Preparation · 26 odozgo i iz kosog pogleda. Potvrdite da je Margin Line zatvorena i da ostaje na preparaciji.',
  'This exercise uses a manually defined curve. It does not run automatic margin detection.','Ova vežba koristi ručno definisanu krivu. Ne pokreće automatsko prepoznavanje margine.',
  array['select','camera','analysis','scene'],array['crown26-preparation','crown26-restoration'],array['off','outline'], '{"objectId":"crown26-reference","position":[0,0,0]}',
  '{"label_en":"Example margin course","label_sr":"Primer toka Margin Line","mode":"outline"}',
  '{"type":"margin_complete","objectId":"crown26-preparation"}',
  '[{"slug":"check-course","order":10,"title_en":"Inspect the complete loop","title_sr":"Pregledajte celu petlju","body_en":"Check that the line stays on the preparation and forms a closed loop.","body_sr":"Proverite da linija ostaje na preparaciji i formira zatvorenu petlju."}]');

select pg_temp.seed_phase16_step('full_crown_case','placement_and_path',20,'Position and inspect the restoration','Pozicionirajte i pregledajte restauraciju',
  'Select Crown restoration · 26. For this exercise set Z to 1.5 mm, then run the +Z insertion-direction preview on Preparation · 26.','Izaberite Crown restoration · 26. Za ovu vežbu postavite Z na 1,5 mm, pa pokrenite +Z smerni prikaz na Preparation · 26.',
  'The numeric transform and chosen direction are exercise settings. The directional preview is not a clinical undercut map.','Numerička transformacija i izabrani smer su podešavanja vežbe. Smerni prikaz nije klinička mapa podminiranja.',
  array['select','move','rotate','analysis','camera'],array['crown26-restoration','crown26-preparation'],array['off','outline','transparent'],null,
  '{"label_en":"Target for this exercise · crown placement","label_sr":"Cilj ove vežbe · pozicioniranje krunice","mode":"outline"}',
  '{"type":"transform_range","objectId":"crown26-restoration","field":"position","position":[0,0,1.5],"axes":["z"],"toleranceMm":0.2}',
  '[{"slug":"save-alignment","order":10,"title_en":"Keep the case aligned","title_sr":"Sačuvajte poravnanje slučaja","body_en":"Move only the editable restoration. Do not recenter the preparation or antagonist.","body_sr":"Pomerajte samo restauraciju koja se može menjati. Ne centrirajte ponovo preparaciju ili antagonistu."}]');

select pg_temp.seed_phase16_step('full_crown_case','proximal_and_occlusal_review',30,'Review neighboring surfaces','Pregledajte susedne površine',
  'Run Proximity map for Crown restoration · 26 and Adjacent tooth · 25. Then compare the crown with Antagonist · 36 using the same static proximity tool.','Pokrenite Proximity map za Crown restoration · 26 i Adjacent tooth · 25. Zatim uporedite krunicu sa Antagonist · 36 istim statičkim alatom za blizinu.',
  'These are static nearest-surface checks on the supplied synthetic positions, not dynamic occlusion or an articulator simulation.','Ovo su statičke provere najbližih površina na zadatim sintetičkim položajima, a ne dinamička okluzija ili simulacija artikulatora.',
  array['select','move','rotate','analysis','camera'],array['crown26-restoration','crown26-adjacent-25','crown26-antagonist-36'],array['off','outline','transparent'],null,
  '{"label_en":"Target for this exercise · static relationships","label_sr":"Cilj ove vežbe · statički odnosi","mode":"outline"}',
  '{"type":"analysis_target","kind":"contact","objectIds":["crown26-restoration","crown26-adjacent-25"],"maxValue":1.5}',
  '[{"slug":"read-map","order":10,"title_en":"Run an explicit map","title_sr":"Pokrenite eksplicitnu mapu","body_en":"A proximity map is computed on demand and becomes stale when either object changes.","body_sr":"Mapa blizine računa se na zahtev i postaje zastarela kada se promeni bilo koji objekat."}]');

select pg_temp.seed_phase16_step('full_crown_case','sculpt_and_thickness',40,'Sculpt and inspect thickness','Oblikujte i pregledajte debljinu',
  'Make one short sculpt stroke on Crown restoration · 26. Run Thickness on that restoration and review the section without changing the source preparation.','Napravite jedan kratak Sculpt potez na Crown restoration · 26. Pokrenite Thickness na restauraciji i pregledajte presek bez izmene izvorne preparacije.',
  'Target for this exercise: minimum measured thickness at least 0.8 mm. It is a configured synthetic exercise target, not a universal material recommendation.','Cilj ove vežbe: najmanja izmerena debljina je najmanje 0,8 mm. To je podešeni sintetički cilj vežbe, a ne univerzalna preporuka za materijal.',
  array['select','sculpt','analysis','camera'],array['crown26-restoration'],array['off','outline','transparent'],null,
  '{"label_en":"Target for this exercise · morphology and section","label_sr":"Cilj ove vežbe · morfologija i presek","mode":"outline"}',
  '{"type":"analysis_target","kind":"thickness","objectIds":["crown26-restoration"],"minValue":0.8}',
  '[{"slug":"compare","order":10,"title_en":"Compare before and after","title_sr":"Uporedite pre i posle","body_en":"Use Undo to compare the sculpt revision. Re-run thickness after any change; old results become stale.","body_sr":"Upotrebite Undo da uporedite reviziju Sculpt poteza. Posle svake izmene ponovo pokrenite Thickness; stari rezultati postaju zastareli."}]');

insert into public.scenarios(domain_id,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,patient_age,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,additional_metadata,random_eligible,status,published_at)
select domain.id,'synthetic_posterior_crown_26','beginner','Posterior crown · tooth 26','Bočna krunica · zub 26',
  'Independent single-crown practice with supplied synthetic preparation, neighboring tooth and antagonist.','Samostalna vežba pojedinačne krunice uz sintetičku preparaciju, susedni zub i antagonistu.',
  'PT-SYN-026',null,'Single posterior crown','Pojedinačna bočna krunica',array[26]::smallint[],
  array['Inspect the preparation','Define a Margin Line','Position and sculpt the restoration','Review static proximity and thickness'],
  array['Pregledajte preparaciju','Definišite Margin Line','Pozicionirajte i oblikujte restauraciju','Pregledajte statičku blizinu i debljinu'],
  '{"material":{"en":"Synthetic training preset","sr":"Sintetički materijal za vežbu"},"supplied":{"en":["Preparation · 26","Adjacent tooth · 25","Antagonist · 36","Synthetic crown restoration"],"sr":["Preparation · 26","Susedni zub · 25","Antagonist · 36","Sintetička restauracija krunice"]},"notes":{"en":"Internally generated synthetic training geometry. Not a real patient case or clinically validated anatomy.","sr":"Interno generisana sintetička geometrija za vežbu. Nije stvarni slučaj niti klinički potvrđena anatomija."},"materialPreset":"synthetic_training","caseInitializer":"crown"}'::jsonb,true,'published',now()
from public.content_domains domain where domain.slug='crown'
on conflict(slug) do update set difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,description_en=excluded.description_en,description_sr=excluded.description_sr,patient_code=excluded.patient_code,patient_age=excluded.patient_age,indication_en=excluded.indication_en,indication_sr=excluded.indication_sr,tooth_numbers=excluded.tooth_numbers,requirements_en=excluded.requirements_en,requirements_sr=excluded.requirements_sr,additional_metadata=excluded.additional_metadata,random_eligible=true,status='published',published_at=coalesce(public.scenarios.published_at,now());
