-- Phase 17 Complete Denture workflow content. All geometry is generated in-app.
insert into public.tool_definitions (id,category,label_en,label_sr,short_description_en,short_description_sr,explanation_en,explanation_sr,status)
values
 ('denture_setup','workflow','Denture setup','Postavka proteze','Choose a synthetic tooth set and arch manipulation mode.','Izaberite sintetički set zuba i režim pomeranja luka.','Arch, Chain and Individual modes edit the same registered CAD tooth objects.','Režimi Arch, Chain i Individual menjaju iste registrovane CAD objekte zuba.','published'),
 ('denture_border','curve','Denture Border','Granica baze proteze','Draw a closed non-destructive boundary on an edentulous arch.','Nacrtajte zatvorenu nedestruktivnu granicu na bezubom luku.','The curve is stored against the arch in object-local coordinates.','Kriva se čuva uz luk u lokalnim koordinatama objekta.','published'),
 ('denture_base','mesh','Denture Base','Baza proteze','Generate and sculpt a synthetic editable base mesh.','Generišite i oblikujte sintetički mesh baze koji se može menjati.','Base geometry includes shallow educational tooth seats; it is not a clinical fit calculation.','Geometrija baze sadrži plitka probna ležišta zuba; ovo nije klinički proračun naleganja.','published')
on conflict (id) do update set category=excluded.category,label_en=excluded.label_en,label_sr=excluded.label_sr,short_description_en=excluded.short_description_en,short_description_sr=excluded.short_description_sr,explanation_en=excluded.explanation_en,explanation_sr=excluded.explanation_sr,status='published';

insert into public.practice_modules (id,slug,title_en,title_sr,summary_en,summary_sr,sort_order,status)
values ('b7170000-0000-4000-8000-000000000001','complete_denture','Complete Denture','Totalna proteza','A complete synthetic denture setup using the shared CAD workspace.','Kompletna sintetička postavka totalne proteze u zajedničkom CAD prostoru.',30,'published')
on conflict (slug) do update set title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,sort_order=excluded.sort_order,status='published';

insert into public.practice_lessons (id,module_id,slug,difficulty,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,estimated_minutes,case_setup,sort_order,status)
select seed.id,module.id,seed.slug,seed.difficulty::public.difficulty_level,seed.title_en,seed.title_sr,seed.summary_en,seed.summary_sr,seed.goal_en,seed.goal_sr,seed.minutes,
 '{"source":"denture-case","objectMappings":[]}'::jsonb,seed.sort_order,'published'
from public.practice_modules module cross join (values
 ('b7170000-0000-4000-8000-000000000010'::uuid,'model_analysis','beginner',10,'Model Analysis','Analiza modela','Inspect the synthetic edentulous arches, editable midlines and setup guides.','Pregledajte sintetičke bezube lukove, srednje linije i vodiče za postavku.','Review the landmarks and adjust the editable occlusal plane guide.','Pregledajte orijentire i podesite pomerljivi vodič okluzalne ravni.',8),
 ('b7170000-0000-4000-8000-000000000011'::uuid,'tooth_selection','beginner',20,'Tooth Selection','Izbor zuba','Compare two internally generated educational tooth sets.','Uporedite dva interno generisana edukativna seta zuba.','Choose a synthetic tooth set and inspect the stable FDI tooth identities.','Izaberite sintetički set i pregledajte stabilne FDI identitete zuba.',6),
 ('b7170000-0000-4000-8000-000000000012'::uuid,'anterior_setup','beginner',30,'Anterior Setup','Postavka prednjih zuba','Position the anterior segment with the shared transform controls.','Pozicionirajte prednji segment zajedničkim alatima za transformaciju.','Adjust the anterior teeth while checking the midline and arch guide.','Podesite prednje zube i proverite srednju liniju i vodič luka.',10),
 ('b7170000-0000-4000-8000-000000000013'::uuid,'posterior_setup','beginner',40,'Posterior Setup','Postavka bočnih zuba','Arrange the premolar and molar segment along the setup guide.','Poređajte pretkutnjake i kutnjake duž vodiča postavke.','Use Arch Mode on the posterior segment and inspect the opposing relationship.','Koristite Arch Mode na bočnom segmentu i pregledajte odnos suprotnih zuba.',10),
 ('b7170000-0000-4000-8000-000000000014'::uuid,'chain_mode','intermediate',50,'Chain Mode','Chain Mode','Move a linked group while preserving neighboring tooth relationships.','Pomerajte povezanu grupu uz očuvanje odnosa susednih zuba.','Select Chain Mode and make a small linked segment adjustment.','Izaberite Chain Mode i malo podesite povezani segment.',7),
 ('b7170000-0000-4000-8000-000000000015'::uuid,'occlusion','intermediate',60,'Static Contact and Occlusion Inspection','Pregled statičkih kontakata i okluzije','Run static proximity checks on opposing synthetic denture geometry.','Pokrenite statičku analizu blizine suprotne sintetičke geometrije proteze.','Inspect the current upper/lower relationship without treating it as dynamic articulation.','Pregledajte trenutni odnos gornjeg i donjeg luka bez simulacije dinamičkog artikulatora.',8),
 ('b7170000-0000-4000-8000-000000000016'::uuid,'base','intermediate',70,'Denture Border and Base','Granica i baza proteze','Draw a border, generate the base and sculpt its editable geometry.','Nacrtajte granicu, generišite bazu i oblikujte njenu geometriju.', 'Create a closed arch boundary and inspect the base cross-section and tooth seats.','Napravite zatvorenu granicu luka i pregledajte presek baze i ležišta zuba.',12),
 ('b7170000-0000-4000-8000-000000000017'::uuid,'full_denture_case','advanced',80,'Full Denture Case','Kompletan slučaj totalne proteze','Review the complete upper and lower synthetic setup and its editable CAD objects.','Pregledajte kompletnu sintetičku postavku gornjeg i donjeg luka i CAD objekte.', 'Complete both arch borders, retain both generated bases and review static relationships.','Zatvorite granice oba luka, sačuvajte obe baze i pregledajte statičke odnose.',20)
) seed(id,slug,difficulty,sort_order,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,minutes)
where module.slug='complete_denture'
on conflict(slug) do update set module_id=excluded.module_id,difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,goal_en=excluded.goal_en,goal_sr=excluded.goal_sr,estimated_minutes=excluded.estimated_minutes,case_setup=excluded.case_setup,sort_order=excluded.sort_order,status='published';

create or replace function pg_temp.seed_phase17_step(p_lesson text,p_order integer,p_title_en text,p_title_sr text,p_instruction_en text,p_instruction_sr text,p_theory_en text,p_theory_sr text,p_tools text[],p_targets text[],p_validator jsonb,p_hint_en text,p_hint_sr text)
returns void language plpgsql as $$
declare lesson_key uuid;step_key uuid;validator_key uuid;tool_value text;validator_type public.validator_type;
begin
 select id into strict lesson_key from public.practice_lessons where slug=p_lesson;
 insert into public.practice_steps(lesson_id,slug,sort_order,title_en,title_sr,instructions_en,instructions_sr,theory_en,theory_sr,target_object_ids,reference_modes,reference_config,example_config,required)
 values(lesson_key,'main',p_order,p_title_en,p_title_sr,p_instruction_en,p_instruction_sr,p_theory_en,p_theory_sr,p_targets,array['off','outline','transparent','full'],'{"objectId":"denture-synthetic-reference","position":[0,0,0]}'::jsonb,'{"label_en":"Synthetic educational setup example","label_sr":"Sintetički edukativni primer postavke","mode":"outline"}'::jsonb,true)
 on conflict(lesson_id,slug) do update set sort_order=excluded.sort_order,title_en=excluded.title_en,title_sr=excluded.title_sr,instructions_en=excluded.instructions_en,instructions_sr=excluded.instructions_sr,theory_en=excluded.theory_en,theory_sr=excluded.theory_sr,target_object_ids=excluded.target_object_ids,reference_modes=excluded.reference_modes,reference_config=excluded.reference_config,example_config=excluded.example_config,required=true returning id into step_key;
 delete from public.practice_hints where step_id=step_key; delete from public.practice_step_tools where step_id=step_key; delete from public.practice_step_validations where step_id=step_key;
 foreach tool_value in array p_tools loop insert into public.practice_step_tools(step_id,tool_id) values(step_key,tool_value) on conflict do nothing; end loop;
 validator_type:=case when p_validator->>'type'='analysis_target' or p_validator->>'type'='denture_setup' then 'custom'::public.validator_type else (p_validator->>'type')::public.validator_type end;
 insert into public.validation_configs(slug,validator_type,config,status) values('denture_'||p_lesson||'_main',validator_type,p_validator,'published') on conflict(slug) do update set validator_type=excluded.validator_type,config=excluded.config,status='published' returning id into validator_key;
 insert into public.practice_step_validations(step_id,validation_config_id,sort_order) values(step_key,validator_key,10);
 insert into public.practice_hints(step_id,slug,sort_order,title_en,title_sr,body_en,body_sr) values(step_key,'review_setup',10,'Review the training target','Pregledajte cilj vežbe',p_hint_en,p_hint_sr);
end $$;

select pg_temp.seed_phase17_step('model_analysis',10,'Inspect landmarks and plane','Pregledajte orijentire i ravan','Inspect both synthetic arches. Use the Occlusal plane guide as an editable reference; its transforms use the shared CAD controls.','Pregledajte oba sintetička luka. Koristite vodič okluzalne ravni kao pomerljivu referencu; njegove transformacije koriste zajedničke CAD alate.','Midlines and arch guides are persisted structured curves. The plane is a movable reference surface, not an anatomical measurement.','Srednje linije i vodiči luka čuvaju se kao strukturisane krive. Ravan je pomerljiva referentna površina, ne anatomsko merenje.',array['select','move','rotate','camera','scene'],array['denture-upper-edentulous-arch','denture-lower-edentulous-arch','denture-occlusal-plane'],'{"type":"denture_setup","check":"model_analysis"}','Keep the midline aligned while adjusting the plane guide.','Sačuvajte poravnanje srednje linije dok podešavate vodič ravni.');
select pg_temp.seed_phase17_step('tooth_selection',20,'Choose an educational tooth set','Izaberite edukativni set zuba','Choose Balanced · synthetic set A or Broad · synthetic set B from the Denture setup bar. Inspect FDI positions in Scene.','U traci Denture setup izaberite Balanced · synthetic set A ili Broad · synthetic set B. Pregledajte FDI pozicije u panelu Scene.','Both sets are generated internally. Tooth IDs and FDI identities remain stable when a set changes.','Oba seta su interno generisana. ID-jevi i FDI identiteti ostaju stabilni pri promeni seta.',array['select','scene','camera'],array['denture-tooth-11','denture-tooth-21','denture-tooth-36'],'{"type":"denture_setup","check":"tooth_setup"}','Use the FDI number in each object name; the library is synthetic teaching geometry.','Proverite FDI broj u nazivu objekta; biblioteka je sintetička geometrija za vežbu.');
select pg_temp.seed_phase17_step('anterior_setup',30,'Position the anterior segment','Pozicionirajte prednji segment','Choose Upper and Anterior · FDI 1–3. Select a tooth and use Move/Rotate, or choose Arch Mode to make a small anterior group adjustment.','Izaberite Upper i Anterior · FDI 1–3. Izaberite zub i koristite Move/Rotate ili Arch Mode za malo pomeranje prednje grupe.','The toolbar group commands record one shared CAD history operation. Individual Mode uses the normal gizmo and numeric properties.','Grupne komande u traci čuvaju jednu zajedničku CAD operaciju istorije. Individual Mode koristi uobičajeni gizmo i numeričke vrednosti.',array['select','move','rotate','camera','scene'],array['denture-tooth-11','denture-tooth-21','denture-tooth-12','denture-tooth-22'],'{"type":"denture_setup","check":"tooth_setup","arch":"upper","segment":"anterior"}','Check the visible midline and use Undo to compare a group change.','Proverite vidljivu srednju liniju i upotrebite Undo za poređenje grupne izmene.');
select pg_temp.seed_phase17_step('posterior_setup',40,'Position the posterior segment','Pozicionirajte bočni segment','Choose Upper and Posterior · FDI 4–8. Try Arch Mode on the segment, then select an individual molar and inspect its transform.','Izaberite Upper i Posterior · FDI 4–8. Isprobajte Arch Mode, zatim izaberite pojedinačni kutnjak i pregledajte transformaciju.','FDI identities are not silently changed by side or mirror operations. This educational case presents both arches explicitly.','FDI identiteti se ne menjaju neprimetno pri promeni strane ili ogledanju. Edukativni slučaj eksplicitno prikazuje oba luka.',array['select','move','rotate','camera','scene'],array['denture-tooth-14','denture-tooth-16','denture-tooth-24','denture-tooth-26'],'{"type":"denture_setup","check":"tooth_setup","arch":"upper","segment":"posterior"}','Use the anterior/posterior segment selector to limit group movement.','Koristite izbor prednjeg ili bočnog segmenta da ograničite grupno pomeranje.');
select pg_temp.seed_phase17_step('chain_mode',50,'Move teeth as a linked chain','Pomerajte zube kao povezani niz','Choose Chain Mode, select an upper tooth, then make a small linked move or rotation. Use Undo to restore the original setup.','Izaberite Chain Mode, označite gornji zub i malo pomerite ili zarotirajte povezanu grupu. Upotrebite Undo da vratite postavku.','Chain Mode transforms the selected tooth and its immediate neighbors as one reversible CAD command.','Chain Mode transformiše izabrani zub i neposredne susede kao jednu CAD komandu koja se može poništiti.',array['select','move','rotate','camera'],array['denture-tooth-11','denture-tooth-12'],'{"type":"denture_setup","check":"chain_mode"}','The active mode is shown in the toolbar; Undo/Redo applies to the full chain.','Aktivni režim je prikazan u traci; Undo/Redo važi za ceo niz.');
select pg_temp.seed_phase17_step('occlusion',60,'Inspect static opposing relationships','Pregledajte statičke odnose suprotnih zuba','Run Proximity map on an upper artificial tooth and a lower opposing tooth or compare the upper and lower bases.','Pokrenite Proximity mapu između gornjeg i donjeg veštačkog zuba ili uporedite baze gornjeg i donjeg luka.','This is a static closest-surface comparison on the current poses. It does not animate opening, protrusion or lateral movement.','Ovo je statičko poređenje najbližih površina u trenutnim položajima. Ne simulira otvaranje, protruziju ni bočne pokrete.',array['select','analysis','camera'],array['denture-tooth-16','denture-tooth-46'],'{"type":"analysis_target","kind":"contact","objectIds":["denture-tooth-16","denture-tooth-46"]}','Run analysis on the current pair and rerun it after moving either object.','Pokrenite analizu trenutnog para i ponovite je nakon pomeranja objekta.');
select pg_temp.seed_phase17_step('base',70,'Draw the border and inspect the base','Nacrtajte granicu i pregledajte bazu','Select an edentulous arch in the Denture Border tool, place at least three surface points and close the boundary. Select its base and inspect with Section or Sculpt.','U alatu Denture Border izaberite bezubi luk, postavite najmanje tri tačke na površini i zatvorite granicu. Izaberite bazu i pregledajte je pomoću Section ili Sculpt.','The generated base is an editable synthetic solid with shallow procedural tooth seats. It is not a clinical boolean fit or manufacturing result.','Generisana baza je sintetičko telo koje se može menjati i ima plitka proceduralna ležišta zuba. Nije klinički boolean spoj niti proizvodni rezultat.',array['select','scene','sculpt','analysis','camera'],array['denture-upper-edentulous-arch','denture-upper-base'],'{"type":"denture_setup","check":"base","arch":"upper"}','Use the base selector, then inspect its mesh revision and section.','Izaberite bazu, zatim pregledajte njenu reviziju mesh-a i presek.');
select pg_temp.seed_phase17_step('full_denture_case',80,'Review the complete denture setup','Pregledajte kompletnu postavku proteze','Review both arches, close a Denture Border on each, keep both editable bases, and run one static opposing proximity check.','Pregledajte oba luka, zatvorite Denture Border na svakom, sačuvajte obe baze i pokrenite jednu statičku analizu suprotnih površina.','This capstone uses synthetic geometry and static analysis only. It does not claim clinically validated fit or dynamic occlusion.','Završni slučaj koristi sintetičku geometriju i samo statičku analizu. Ne tvrdi da pruža klinički potvrđeno naleganje ili dinamičku okluziju.',array['select','move','rotate','scene','sculpt','analysis','camera'],array['denture-upper-base','denture-lower-base','denture-tooth-16','denture-tooth-46'],'{"type":"denture_setup","check":"complete_case"}','Both closed boundary curves and both base objects are required for this exercise check.','Za ovu proveru vežbe potrebne su obe zatvorene granične krive i oba objekta baze.');

insert into public.scenarios(domain_id,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,patient_age,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,additional_metadata,random_eligible,status,published_at)
select domain.id,seed.slug,seed.difficulty::public.difficulty_level,seed.title_en,seed.title_sr,seed.description_en,seed.description_sr,seed.patient_code,null,seed.indication_en,seed.indication_sr,'{}'::smallint[],seed.requirements_en,seed.requirements_sr,seed.metadata::jsonb,true,'published',now()
from (values
 ('synthetic_upper_complete_denture','beginner','Upper Complete Denture','Totalna proteza gornje vilice','Independent upper-arch tooth setup and base inspection with procedural educational geometry.','Samostalna postavka zuba gornjeg luka i pregled baze uz proceduralnu edukativnu geometriju.','PT-SYN-D17U','Complete upper denture','Totalna proteza gornje vilice',array['Arrange the artificial teeth','Review the arch guide and border','Inspect the editable synthetic base'],array['Poređajte veštačke zube','Pregledajte vodič luka i granicu','Pregledajte sintetičku bazu koja se može menjati'],'{"caseInitializer":"complete_denture","geometryProvenance":"internal-synthetic-educational","noPatientData":true,"materialPreset":"synthetic_training","material":{"en":"Synthetic educational preset","sr":"Sintetički edukativni materijal"},"supplied":{"en":["Edentulous upper arch","Artificial tooth sets","Editable synthetic base"],"sr":["Bezubi gornji luk","Setovi veštačkih zuba","Sintetička baza koja se može menjati"]},"notes":{"en":"All training geometry is generated inside Prostheia. No patient scan or third-party tooth library is included.","sr":"Sva geometrija za vežbu generisana je unutar Prostheia. Nema snimaka pacijenata ni tuđih biblioteka zuba."}}'),
 ('synthetic_upper_lower_complete_denture','intermediate','Upper + Lower Complete Denture','Totalna proteza gornje i donje vilice','Independent two-arch setup with static opposing-relationship inspection.','Samostalna postavka oba luka uz pregled statičkog odnosa suprotnih zuba.','PT-SYN-D17UL','Upper and lower complete dentures','Totalne proteze gornje i donje vilice',array['Arrange both FDI tooth arches','Inspect static opposing proximity','Review both editable synthetic bases'],array['Poređajte oba FDI luka zuba','Pregledajte statičku blizinu suprotnih površina','Pregledajte obe sintetičke baze koje se mogu menjati'],'{"caseInitializer":"complete_denture","geometryProvenance":"internal-synthetic-educational","noPatientData":true,"materialPreset":"synthetic_training","material":{"en":"Synthetic educational preset","sr":"Sintetički edukativni materijal"},"supplied":{"en":["Edentulous upper and lower arches","Artificial tooth sets","Two editable synthetic bases"],"sr":["Bezubi gornji i donji luk","Setovi veštačkih zuba","Dve sintetičke baze koje se mogu menjati"]},"notes":{"en":"All training geometry is generated inside Prostheia. Static proximity does not simulate jaw movement.","sr":"Sva geometrija za vežbu generisana je unutar Prostheia. Statička blizina ne simulira pokret vilice."}}')
) seed(slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,indication_en,indication_sr,requirements_en,requirements_sr,metadata)
join public.content_domains domain on domain.slug='complete_denture'
on conflict(slug) do update set difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,description_en=excluded.description_en,description_sr=excluded.description_sr,patient_code=excluded.patient_code,patient_age=null,indication_en=excluded.indication_en,indication_sr=excluded.indication_sr,tooth_numbers='{}'::smallint[],requirements_en=excluded.requirements_en,requirements_sr=excluded.requirements_sr,additional_metadata=excluded.additional_metadata,random_eligible=true,status='published',published_at=coalesce(public.scenarios.published_at,now());
