-- Phase 18 fixed-restorative learning content. CAD assets are generated in-app.
-- Restoration geometry is synthetic educational geometry; no patient or licensed library data is included.

insert into public.tool_definitions (id,category,label_en,label_sr,short_description_en,short_description_sr,explanation_en,explanation_sr,status)
values
 ('restorative_workflow','workflow','Restorative workflow','Restorativni postupak','Shared workflow controls for fixed restorative cases.','Zajedničke kontrole postupka za fiksne protetske radove.','Crown, Bridge, Inlay, Onlay and Veneer use one CAD workspace and registered restoration objects.','Crown, Bridge, Inlay, Onlay i Veneer koriste jedan CAD prostor i registrovane objekte nadoknade.','published'),
 ('bridge_units','workflow','Bridge units','Jedinice mosta','Inspect abutments, pontic and connector members in one bridge object.','Pregledajte nosače, međučlan i spojnice unutar jednog objekta mosta.','The training bridge has stable unit identities and one editable connected CAD object.','Probni most ima stabilne identitete jedinica i jedan povezani CAD objekat koji se može menjati.','published'),
 ('pontic_inspection','analysis','Pontic and gingiva inspection','Pregled međučlana i gingive','Inspect the pontic against a synthetic support reference.','Pregledajte međučlan u odnosu na sintetičku referencu potpore.','Use static proximity and Section views for educational inspection; no clinical pontic rule is inferred.','Koristite statičku blizinu i Section prikaz za edukativni pregled; ne izvodi se kliničko pravilo za međučlan.','published')
on conflict (id) do update set category=excluded.category,label_en=excluded.label_en,label_sr=excluded.label_sr,short_description_en=excluded.short_description_en,short_description_sr=excluded.short_description_sr,explanation_en=excluded.explanation_en,explanation_sr=excluded.explanation_sr,status='published';

insert into public.practice_modules (id,slug,title_en,title_sr,summary_en,summary_sr,sort_order,status)
values
 ('b7180000-0000-4000-8000-000000000001','bridge_workflow','Bridge Workflow','Postupak izrade mosta','A connected, multi-unit synthetic bridge case using the shared restorative CAD architecture.','Sintetički slučaj povezanog mosta sa više jedinica u zajedničkoj restorativnoj CAD arhitekturi.',40,'published'),
 ('b7180000-0000-4000-8000-000000000002','inlay_onlay_workflow','Inlay and Onlay Workflow','Postupak izrade Inlay i Onlay nadoknada','Compare two related but distinct partial-coverage restorations using shared CAD tools.','Uporedite dve srodne, ali različite parcijalne nadoknade uz zajedničke CAD alate.',50,'published'),
 ('b7180000-0000-4000-8000-000000000003','veneer_workflow','Veneer Workflow','Postupak izrade fasete','An anterior synthetic veneer case focused on placement and shared surface inspection.','Sintetički slučaj prednje fasete usmeren na pozicioniranje i zajednički pregled površine.',60,'published')
on conflict (slug) do update set title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,sort_order=excluded.sort_order,status='published';

insert into public.practice_lessons (id,module_id,slug,difficulty,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,estimated_minutes,case_setup,sort_order,status)
select seed.id,module.id,seed.slug,seed.difficulty::public.difficulty_level,seed.title_en,seed.title_sr,seed.summary_en,seed.summary_sr,seed.goal_en,seed.goal_sr,seed.minutes,
 jsonb_build_object('source','restorative-case','restorationType',seed.restoration_type,'objectMappings',jsonb_build_array()),seed.sort_order,'published'
from (values
 ('b7180000-0000-4000-8000-000000000010'::uuid,'bridge_units','bridge_workflow','bridge','beginner',10,'Bridge Units and Margins','Jedinice mosta i margine','Inspect the two abutments, pontic region, connector members and individual preparation margins.','Pregledajte dva nosača, područje međučlana, spojnice i pojedinačne margine preparacija.','Close a separate Margin Line on each abutment preparation.','Zatvorite zasebnu Margin Line na preparaciji svakog nosača.',12),
 ('b7180000-0000-4000-8000-000000000011'::uuid,'bridge_pontic_connectors','bridge_workflow','bridge','intermediate',20,'Pontic, Connectors and Gingiva Relation','Međučlan, spojnice i odnos sa gingivom','Inspect the pontic and adjust connector geometry on the shared bridge object.','Pregledajte međučlan i podesite geometriju spojnica na zajedničkom objektu mosta.','Review the synthetic support region and connector target for this exercise.','Pregledajte sintetičku potpornu regiju i cilj spojnica za ovu vežbu.',12),
 ('b7180000-0000-4000-8000-000000000012'::uuid,'bridge_contacts_thickness','bridge_workflow','bridge','intermediate',30,'Bridge Proximity and Thickness','Blizina i debljina mosta','Inspect static proximal and antagonist relationships and the bridge mesh.','Pregledajte statičke proksimalne odnose, antagonistu i mesh mosta.','Run shared proximity and thickness analyses, then review a Section view.','Pokrenite zajedničke analize blizine i debljine, pa pregledajte Section prikaz.',14),
 ('b7180000-0000-4000-8000-000000000013'::uuid,'bridge_full_case','bridge_workflow','bridge','intermediate',40,'Full Bridge Case · 14–16','Kompletan slučaj mosta · 14–16','Complete the connected bridge exercise with separate abutment margins and shared CAD edits.','Završite vežbu povezanog mosta zasebnim marginama nosača i zajedničkim CAD izmenama.','Review unit identities, close both margins and complete the configured analysis checks.','Pregledajte identitete jedinica, zatvorite obe margine i dovršite podešene analize.',18),
 ('b7180000-0000-4000-8000-000000000020'::uuid,'inlay_margin_insertion','inlay_onlay_workflow','inlay','beginner',10,'Inlay Margin and Insertion Direction','Inlay margina i smer insercije','Inspect the prepared cavity and define a non-destructive Margin Line.','Pregledajte preparisanu kavitaciju i definišite nedestruktivnu Margin Line.','Close the preparation boundary and preview an explicit insertion direction.','Zatvorite granicu preparacije i prikažite izričito izabran smer insercije.',10),
 ('b7180000-0000-4000-8000-000000000021'::uuid,'inlay_contact_thickness','inlay_onlay_workflow','inlay','intermediate',20,'Inlay Contact and Thickness','Inlay kontakt i debljina','Edit the synthetic inlay and inspect neighboring and opposing surfaces.','Izmenite sintetički Inlay i pregledajte susedne i suprotne površine.','Use shared proximity, thickness, Section and Design Check tools.','Koristite zajedničke alate Proximity, Thickness, Section i Design Check.',12),
 ('b7180000-0000-4000-8000-000000000022'::uuid,'onlay_coverage_margin','inlay_onlay_workflow','onlay','beginner',30,'Onlay Coverage and Margin','Onlay pokrivenost i margina','Inspect the broader synthetic occlusal and cusp coverage form.','Pregledajte širi sintetički oblik okluzalne i kvržične pokrivenosti.','Distinguish Onlay coverage from the smaller Inlay form and define its margin.','Razlikujte Onlay pokrivenost od manjeg Inlay oblika i definišite marginu.',10),
 ('b7180000-0000-4000-8000-000000000023'::uuid,'onlay_design_review','inlay_onlay_workflow','onlay','intermediate',40,'Onlay Contact and Thickness Review','Onlay pregled kontakta i debljine','Edit the onlay form and inspect static surface relationships.','Izmenite Onlay oblik i pregledajte statičke odnose površina.','Run shared contact and thickness analyses and inspect the section.','Pokrenite zajedničke analize kontakta i debljine i pregledajte presek.',12),
 ('b7180000-0000-4000-8000-000000000030'::uuid,'veneer_preparation_reference','veneer_workflow','veneer','beginner',10,'Anterior Preparation and Reference','Prednja preparacija i referenca','Inspect the synthetic preparation, adjacent teeth and optional reference model.','Pregledajte sintetičku preparaciju, susedne zube i opcionu referentnu geometriju.','Compare the facial shell with its reference and identify the target tooth 11.','Uporedite fasetnu ljuspicu sa referencom i identifikujte zub 11.',8),
 ('b7180000-0000-4000-8000-000000000031'::uuid,'veneer_position_thickness','veneer_workflow','veneer','intermediate',20,'Veneer Placement and Surface Review','Pozicioniranje fasete i pregled površine','Position the editable veneer and inspect deviation and thickness.','Pozicionirajte fasetu koja se može menjati i pregledajte odstupanje i debljinu.','Use shared transforms, Sculpt, Section and Design Check on the anterior case.','Koristite zajedničke transformacije, Sculpt, Section i Design Check na prednjem slučaju.',12)
) seed(id,slug,module_slug,restoration_type,difficulty,sort_order,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,minutes)
join public.practice_modules module on module.slug=seed.module_slug
on conflict (slug) do update set module_id=excluded.module_id,difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,goal_en=excluded.goal_en,goal_sr=excluded.goal_sr,estimated_minutes=excluded.estimated_minutes,case_setup=excluded.case_setup,sort_order=excluded.sort_order,status='published';

create or replace function pg_temp.seed_phase18_step(
 p_lesson_slug text,p_slug text,p_order integer,p_title_en text,p_title_sr text,p_instruction_en text,p_instruction_sr text,p_theory_en text,p_theory_sr text,p_tools text[],p_targets text[],p_validators jsonb,p_hints jsonb
) returns void language plpgsql as $$
declare lesson_key uuid;step_key uuid;validator_key uuid;validator_value jsonb;hint_value jsonb;tool_value text;validator_type public.validator_type;validator_order integer:=10;
begin
 select id into strict lesson_key from public.practice_lessons where slug=p_lesson_slug;
 insert into public.practice_steps(lesson_id,slug,sort_order,title_en,title_sr,instructions_en,instructions_sr,theory_en,theory_sr,target_object_ids,reference_modes,reference_config,example_config,required)
 values(lesson_key,p_slug,p_order,p_title_en,p_title_sr,p_instruction_en,p_instruction_sr,p_theory_en,p_theory_sr,p_targets,array['off','outline','transparent','full'],null,jsonb_build_object('label_en','Target for this exercise','label_sr','Cilj ove vežbe','mode','outline'),true)
 on conflict(lesson_id,slug) do update set sort_order=excluded.sort_order,title_en=excluded.title_en,title_sr=excluded.title_sr,instructions_en=excluded.instructions_en,instructions_sr=excluded.instructions_sr,theory_en=excluded.theory_en,theory_sr=excluded.theory_sr,target_object_ids=excluded.target_object_ids,reference_modes=excluded.reference_modes,reference_config=excluded.reference_config,example_config=excluded.example_config,required=true returning id into step_key;
 delete from public.practice_hints where step_id=step_key; delete from public.practice_step_tools where step_id=step_key; delete from public.practice_step_validations where step_id=step_key;
 foreach tool_value in array p_tools loop insert into public.practice_step_tools(step_id,tool_id) values(step_key,tool_value) on conflict do nothing; end loop;
 for validator_value in select value from jsonb_array_elements(coalesce(p_validators,'[]'::jsonb)) loop
  validator_type:=case when validator_value->>'type' in ('analysis_target','restorative_setup') then 'custom'::public.validator_type else (validator_value->>'type')::public.validator_type end;
  insert into public.validation_configs(slug,validator_type,config,status) values('restorative_'||p_lesson_slug||'_'||p_slug||'_'||(validator_value->>'type')||'_'||coalesce(validator_value->>'kind',validator_value->>'check','check')||'_'||substr(md5(validator_value::text),1,10),validator_type,validator_value,'published')
  on conflict(slug) do update set validator_type=excluded.validator_type,config=excluded.config,status='published' returning id into validator_key;
  insert into public.practice_step_validations(step_id,validation_config_id,sort_order) values(step_key,validator_key,validator_order) on conflict(step_id,validation_config_id) do update set sort_order=excluded.sort_order;
  validator_order:=validator_order+10;
 end loop;
 for hint_value in select value from jsonb_array_elements(coalesce(p_hints,'[]'::jsonb)) loop
  insert into public.practice_hints(step_id,slug,sort_order,title_en,title_sr,body_en,body_sr) values(step_key,hint_value->>'slug',(hint_value->>'order')::integer,hint_value->>'title_en',hint_value->>'title_sr',hint_value->>'body_en',hint_value->>'body_sr');
 end loop;
end $$;

select pg_temp.seed_phase18_step('bridge_units','bridge_setup',10,'Inspect the bridge units and margins','Pregledajte jedinice mosta i margine',
 'Select each preparation in turn. Draw and close one Margin Line on the 14 abutment and a separate Margin Line on the 16 abutment, then run Design Check.',
 'Redom izaberite svaku preparaciju. Nacrtajte i zatvorite jednu Margin Line na nosaču 14, a zasebnu Margin Line na nosaču 16, pa pokrenite Design Check.',
 'The bridge is one editable CAD object with stable abutment, pontic and connector member identities. Each preparation margin remains attached to its own object in local coordinates.',
 'Most je jedan CAD objekat koji se može menjati, sa stabilnim identitetima nosača, međučlana i spojnica. Margina svake preparacije ostaje povezana sa sopstvenim objektom u lokalnim koordinatama.',
 array['select','camera','scene','analysis'],array['restorative-bridge-preparation-14','restorative-bridge-preparation-16','restorative-bridge-bridge'],
 '[{"type":"margin_complete","objectId":"restorative-bridge-preparation-14"},{"type":"margin_complete","objectId":"restorative-bridge-preparation-16"},{"type":"restorative_setup","check":"bridge_design","restorationType":"bridge"}]'::jsonb,
 '[{"slug":"separate-surfaces","order":10,"title_en":"Keep the margins attached","title_sr":"Ostavite margine povezane","body_en":"Choose each abutment preparation from the workflow controls before drawing. Margin points are accepted only on the selected preparation.","body_sr":"Pre crtanja izaberite svaki nosač u kontrolama postupka. Tačke margine prihvataju se samo na izabranoj preparaciji."},{"slug":"closed-curves","order":20,"title_en":"Close both curves","title_sr":"Zatvorite obe krive","body_en":"The two Margin Lines have separate object IDs and undo history. Both must be closed for this setup check.","body_sr":"Dve Margin Line krive imaju zasebne ID-jeve objekata i istoriju poništavanja. Obe moraju biti zatvorene za ovu proveru."}]');

select pg_temp.seed_phase18_step('bridge_pontic_connectors','pontic_connector_review',10,'Inspect the pontic, connectors and support region','Pregledajte međučlan, spojnice i potpornu regiju',
 'Inspect the central pontic against the synthetic gingiva region. Adjust the connector diameter slider, then use Undo and Redo to review the geometry history.',
 'Pregledajte centralni međučlan u odnosu na sintetičku gingivalnu regiju. Podesite klizač prečnika spojnica, pa koristite Undo i Redo za pregled istorije geometrije.',
 'The displayed connector dimension is a target for this exercise. The support comparison is static and does not assert a clinically validated pontic design.',
 'Prikazana dimenzija spojnice je cilj ove vežbe. Poređenje potpore je statičko i ne potvrđuje klinički proverenu konstrukciju međučlana.',
 array['select','move','rotate','sculpt','analysis','camera','scene'],array['restorative-bridge-bridge','restorative-bridge-gingiva'],
 '[{"type":"restorative_setup","check":"bridge_design","restorationType":"bridge"}]'::jsonb,
 '[{"slug":"one-object","order":10,"title_en":"Select the bridge root","title_sr":"Izaberite osnovni objekat mosta","body_en":"Abutments, pontic and connector members belong to one bridge object. Select mesh children in Scene only when you need to edit a member locally.","body_sr":"Nosači, međučlan i spojnice pripadaju jednom objektu mosta. Izaberite mesh potomke u Scene panelu samo kada želite lokalno da menjate jedinicu."}]');

select pg_temp.seed_phase18_step('bridge_contacts_thickness','bridge_analysis',10,'Check static relationships and thickness','Proverite statičke odnose i debljinu',
 'Run Proximity map for the bridge against an adjacent tooth and then against the antagonist. Run Thickness on the bridge and inspect a Section view. Values are exercise measurements only.',
 'Pokrenite Proximity map za most u odnosu na susedni zub, a zatim u odnosu na antagonistu. Pokrenite Thickness za most i pregledajte Section. Vrednosti su samo merenja za vežbu.',
 'Nearest-surface distance and ray thickness are generic shared analyses. Static proximity does not model jaw motion or establish a clinical contact rule.',
 'Najkraće rastojanje površina i debljina zraka su opšte zajedničke analize. Statička blizina ne modeluje kretanje vilice niti utvrđuje kliničko pravilo kontakta.',
 array['select','analysis','camera','scene'],array['restorative-bridge-bridge','restorative-bridge-adjacent-13','restorative-bridge-antagonist-44'],
 '[{"type":"analysis_target","kind":"contact","objectIds":["restorative-bridge-bridge","restorative-bridge-adjacent-13"]},{"type":"analysis_target","kind":"contact","objectIds":["restorative-bridge-bridge","restorative-bridge-antagonist-44"]},{"type":"analysis_target","kind":"thickness","objectIds":["restorative-bridge-bridge"]}]'::jsonb,
 '[{"slug":"static-only","order":10,"title_en":"Use explicit object pairs","title_sr":"Izaberite parove objekata","body_en":"Choose the two named objects in the analysis controls. Run each comparison separately and read the measured range.","body_sr":"Izaberite dva navedena objekta u kontrolama analize. Pokrenite svako poređenje zasebno i pregledajte izmereni opseg."},{"slug":"section-view","order":20,"title_en":"Inspect a section","title_sr":"Pregledajte presek","body_en":"Section clips only the viewport. It does not alter bridge mesh data.","body_sr":"Section odseca samo prikaz u viewport-u. Ne menja podatke mesh-a mosta."}]');

select pg_temp.seed_phase18_step('bridge_full_case','bridge_capstone',10,'Complete the Bridge 14–16 case','Završite slučaj mosta 14–16',
 'Complete both abutment margins, inspect the bridge unit identities, adjust a connector or restoration mesh, and run the configured proximal, antagonist and thickness checks.',
 'Završite obe margine nosača, pregledajte identitete jedinica mosta, podesite spojnicu ili mesh nadoknade i pokrenite podešene provere proksimalnog odnosa, antagoniste i debljine.',
 'Design Check summarizes workflow state and current analysis results for this synthetic exercise; it is not manufacturing or clinical validation.',
 'Design Check sažima stanje postupka i aktuelne rezultate analiza ove sintetičke vežbe; nije validacija za izradu ili kliničku upotrebu.',
 array['select','move','rotate','sculpt','analysis','camera','scene'],array['restorative-bridge-preparation-14','restorative-bridge-preparation-16','restorative-bridge-bridge'],
 '[{"type":"margin_complete","objectId":"restorative-bridge-preparation-14"},{"type":"margin_complete","objectId":"restorative-bridge-preparation-16"},{"type":"restorative_setup","check":"bridge_design","restorationType":"bridge"},{"type":"analysis_target","kind":"contact","objectIds":["restorative-bridge-bridge","restorative-bridge-adjacent-13"]},{"type":"analysis_target","kind":"contact","objectIds":["restorative-bridge-bridge","restorative-bridge-antagonist-44"]},{"type":"analysis_target","kind":"thickness","objectIds":["restorative-bridge-bridge"]}]'::jsonb,
 '[{"slug":"review-history","order":10,"title_en":"Edit reversibly","title_sr":"Menjajte reverzibilno","body_en":"Bridge connector adjustments, transforms, curves and sculpt strokes use shared Undo and Redo history.","body_sr":"Podešavanja spojnica, transformacije, krive i Sculpt potezi mosta koriste zajedničku Undo i Redo istoriju."}]');

select pg_temp.seed_phase18_step('inlay_margin_insertion','inlay_margin',10,'Define the Inlay margin and insertion direction','Definišite Inlay marginu i smer insercije',
 'Select Preparation · 36, draw and close its Margin Line, then preview an insertion direction on the selected preparation.',
 'Izaberite Preparation · 36, nacrtajte i zatvorite Margin Line, pa prikažite smer insercije na izabranoj preparaciji.',
 'The synthetic inlay starting form and generic directional preview are educational. No automatic cavity fit or clinical undercut classification is calculated.',
 'Početni oblik sintetičkog Inlay-a i opšti smerni prikaz služe edukaciji. Ne izračunava se automatsko naleganje u kavitet niti klinička klasifikacija podminiranja.',
 array['select','camera','analysis','scene'],array['restorative-inlay-preparation-36','restorative-inlay-restoration-36'],
 '[{"type":"margin_complete","objectId":"restorative-inlay-preparation-36"},{"type":"restorative_setup","check":"single_unit_design","restorationType":"inlay"}]'::jsonb,
 '[{"slug":"local-margin","order":10,"title_en":"Keep the boundary on the cavity preparation","title_sr":"Zadržite granicu na preparaciji kaviteta","body_en":"Pick at least three points directly on the selected Preparation · 36 object and close the curve.","body_sr":"Izaberite najmanje tri tačke direktno na izabranom objektu Preparation · 36 i zatvorite krivu."}]');

select pg_temp.seed_phase18_step('inlay_contact_thickness','inlay_review',10,'Review Inlay contact and thickness','Pregledajte Inlay kontakt i debljinu',
 'Use shared Move or Sculpt controls to edit the inlay. Run Proximity against an adjacent tooth and antagonist, run Thickness, and inspect a Section.',
 'Koristite zajedničke Move ili Sculpt kontrole da izmenite Inlay. Pokrenite Proximity prema susednom zubu i antagonisti, Thickness i pregledajte Section.',
 'These analyses use the current synthetic surfaces and standard engine. Numeric values are targets for this exercise, not universal clinical cutoffs.',
 'Ove analize koriste aktuelne sintetičke površine i standardni engine. Brojčane vrednosti su ciljevi ove vežbe, a ne univerzalni klinički pragovi.',
 array['select','move','rotate','sculpt','analysis','camera','scene'],array['restorative-inlay-restoration-36','restorative-inlay-adjacent-35','restorative-inlay-antagonist-26'],
 '[{"type":"restorative_setup","check":"single_unit_design","restorationType":"inlay"},{"type":"analysis_target","kind":"contact","objectIds":["restorative-inlay-restoration-36","restorative-inlay-adjacent-35"]},{"type":"analysis_target","kind":"contact","objectIds":["restorative-inlay-restoration-36","restorative-inlay-antagonist-26"]},{"type":"analysis_target","kind":"thickness","objectIds":["restorative-inlay-restoration-36"]}]'::jsonb,null);

select pg_temp.seed_phase18_step('onlay_coverage_margin','onlay_coverage',10,'Inspect Onlay cusp coverage and margin','Pregledajte Onlay pokrivenost kvržica i marginu',
 'Inspect the broader occlusal Onlay form over Preparation · 46. Define and close the preparation Margin Line, then compare the covered cusp region with the Inlay learning material.',
 'Pregledajte širi okluzalni oblik Onlay-a na Preparation · 46. Definišite i zatvorite Margin Line preparacije, pa uporedite pokrivenu regiju kvržica sa gradivom za Inlay.',
 'This synthetic Onlay preset represents broader occlusal and cusp coverage than the Inlay preset. It is a visual teaching distinction, not automated margin or fit detection.',
 'Ovaj sintetički Onlay preset prikazuje širu okluzalnu i kvržičnu pokrivenost od Inlay preseta. To je vizuelna edukativna razlika, a ne automatsko prepoznavanje margine ili naleganja.',
 array['select','camera','analysis','scene'],array['restorative-onlay-preparation-46','restorative-onlay-restoration-46'],
 '[{"type":"margin_complete","objectId":"restorative-onlay-preparation-46"},{"type":"restorative_setup","check":"single_unit_design","restorationType":"onlay"}]'::jsonb,null);

select pg_temp.seed_phase18_step('onlay_design_review','onlay_review',10,'Edit and review the Onlay','Izmenite i pregledajte Onlay',
 'Use shared transforms or Sculpt to edit the Onlay, then inspect its proximal and antagonist relationships, ray thickness samples and a Section view.',
 'Zajedničkim transformacijama ili Sculpt alatom izmenite Onlay, pa pregledajte proksimalne i antagonističke odnose, uzorke debljine zraka i Section prikaz.',
 'The Onlay remains a distinct coverage preset, while its transforms and analyses use the same shared restorative engine as Inlay and Crown.',
 'Onlay ostaje zaseban preset pokrivenosti, dok njegove transformacije i analize koriste isti zajednički restorativni engine kao Inlay i Crown.',
 array['select','move','rotate','sculpt','analysis','camera','scene'],array['restorative-onlay-restoration-46','restorative-onlay-adjacent-45','restorative-onlay-antagonist-16'],
 '[{"type":"restorative_setup","check":"single_unit_design","restorationType":"onlay"},{"type":"analysis_target","kind":"contact","objectIds":["restorative-onlay-restoration-46","restorative-onlay-adjacent-45"]},{"type":"analysis_target","kind":"contact","objectIds":["restorative-onlay-restoration-46","restorative-onlay-antagonist-16"]},{"type":"analysis_target","kind":"thickness","objectIds":["restorative-onlay-restoration-46"]}]'::jsonb,null);

select pg_temp.seed_phase18_step('veneer_preparation_reference','veneer_reference',10,'Inspect the anterior preparation and reference','Pregledajte prednju preparaciju i referencu',
 'Inspect Preparation · 11, adjacent teeth and the synthetic Veneer surface. Toggle the example reference to compare its facial orientation and return the reference to hidden.',
 'Pregledajte Preparation · 11, susedne zube i sintetičku površinu fasete. Prikažite primer reference da uporedite facijalnu orijentaciju i zatim ponovo sakrijte referencu.',
 'The anterior shell is an internally generated synthetic training object and makes no claim about a clinically prepared surface.',
 'Prednja ljuska je interno generisan sintetički objekat za obuku i ne predstavlja tvrdnju o klinički preparisanoj površini.',
 array['select','camera','scene','analysis'],array['restorative-veneer-preparation-11','restorative-veneer-restoration-11','restorative-veneer-reference-11'],
 '[{"type":"required_object","objectId":"restorative-veneer-restoration-11","visible":true}]'::jsonb,null);

select pg_temp.seed_phase18_step('veneer_position_thickness','veneer_design',10,'Position and inspect the Veneer','Pozicionirajte i pregledajte fasetu',
 'Select the editable Veneer · 11, adjust its position or orientation with shared Move and Rotate, then review reference deviation, thickness and a Section view.',
 'Izaberite fasetu Veneer · 11 koja se može menjati, podesite njen položaj ili orijentaciju zajedničkim Move i Rotate alatima, pa pregledajte odstupanje od reference, debljinu i Section prikaz.',
 'Deviation and thickness are generic mesh inspections. Targets shown in this lesson are for the exercise and are not clinical acceptance limits.',
 'Odstupanje i debljina su opšti pregledi mesh-a. Ciljevi u ovoj lekciji služe vežbi i nisu kliničke granice prihvatanja.',
 array['select','move','rotate','sculpt','analysis','camera','scene'],array['restorative-veneer-restoration-11','restorative-veneer-reference-11','restorative-veneer-antagonist-41'],
 '[{"type":"restorative_setup","check":"veneer_position","restorationType":"veneer"},{"type":"analysis_target","kind":"deviation","objectIds":["restorative-veneer-restoration-11","restorative-veneer-reference-11"]},{"type":"analysis_target","kind":"thickness","objectIds":["restorative-veneer-restoration-11"]}]'::jsonb,null);

insert into public.scenarios(domain_id,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,patient_age,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,additional_metadata,random_eligible,status,published_at)
select domain.id,seed.slug,seed.difficulty::public.difficulty_level,seed.title_en,seed.title_sr,seed.description_en,seed.description_sr,seed.patient_code,null,seed.indication_en,seed.indication_sr,seed.tooth_numbers,seed.requirements_en,seed.requirements_sr,seed.metadata::jsonb,true,'published',now()
from (values
 ('bridge','synthetic_bridge_14_16','intermediate','Bridge 14–16','Most 14–16','Connected three-unit synthetic bridge with two editable abutment margins, central pontic and adjustable connector members.','Povezan sintetički most od tri jedinice sa marginama dva nosača, centralnim međučlanom i podesivim spojnicama.','PT-TR-181','Three-unit bridge training case','Vežba za tročlani most',array[14,15,16]::smallint[],array['Inspect both abutments','Define two separate margins','Review pontic support and connectors','Check static proximal and antagonist relationships'],array['Pregledajte oba nosača','Definišite dve zasebne margine','Pregledajte potporu međučlana i spojnice','Proverite statičke proksimalne i antagonističke odnose'],'{"caseInitializer":"restorative","restorationType":"bridge","geometryProvenance":"internal-synthetic-educational","noPatientData":true,"materialPreset":"synthetic_training","material":{"en":"Synthetic educational preset","sr":"Sintetički edukativni materijal"},"supplied":{"en":["Two synthetic abutment preparations","Adjacent teeth and antagonist","Pontic support region","Connected bridge restoration"],"sr":["Dve sintetičke preparacije nosača","Susedni zubi i antagonist","Potporna regija međučlana","Povezana mostna nadoknada"]},"notes":{"en":"All geometry is generated in Prostheia for education. Static proximity does not simulate jaw motion or establish clinical suitability.","sr":"Sva geometrija je generisana u Prostheia za edukaciju. Statička blizina ne simulira kretanje vilice niti utvrđuje kliničku podobnost."}}'),
 ('inlay_onlay','synthetic_inlay_36','beginner','Inlay 36','Inlay 36','Synthetic cavity preparation with a distinct partial-coverage Inlay starting form and antagonist.','Sintetička preparacija kaviteta sa zasebnim početnim oblikom parcijalne Inlay nadoknade i antagonistom.','PT-TR-182','Inlay training case','Vežba za Inlay',array[36]::smallint[],array['Inspect the prepared cavity','Define its Margin Line','Review insertion direction','Check proximal and antagonist proximity and thickness'],array['Pregledajte preparisani kavitet','Definišite Margin Line','Pregledajte smer insercije','Proverite proksimalnu i antagonističku blizinu i debljinu'],'{"caseInitializer":"restorative","restorationType":"inlay","geometryProvenance":"internal-synthetic-educational","noPatientData":true,"materialPreset":"synthetic_training","material":{"en":"Synthetic educational preset","sr":"Sintetički edukativni materijal"},"supplied":{"en":["Synthetic preparation 36","Synthetic adjacent teeth","Synthetic antagonist","Editable Inlay and example reference"],"sr":["Sintetička preparacija 36","Sintetički susedni zubi","Sintetički antagonist","Inlay koji se može menjati i primer reference"]},"notes":{"en":"The starter form is not an automatic cavity fit or clinical design recommendation.","sr":"Početni oblik nije automatsko naleganje u kavitet niti klinička preporuka dizajna."}}'),
 ('inlay_onlay','synthetic_onlay_46','intermediate','Onlay 46','Onlay 46','Synthetic broader occlusal and cusp coverage form with preparation, adjacent surfaces and antagonist.','Sintetički širi oblik okluzalne i kvržične pokrivenosti sa preparacijom, susednim površinama i antagonistom.','PT-TR-183','Onlay training case','Vežba za Onlay',array[46]::smallint[],array['Inspect the broader cusp coverage','Define the preparation margin','Edit the Onlay with shared tools','Review static proximity and thickness'],array['Pregledajte širu pokrivenost kvržica','Definišite marginu preparacije','Izmenite Onlay zajedničkim alatima','Pregledajte statičku blizinu i debljinu'],'{"caseInitializer":"restorative","restorationType":"onlay","geometryProvenance":"internal-synthetic-educational","noPatientData":true,"materialPreset":"synthetic_training","material":{"en":"Synthetic educational preset","sr":"Sintetički edukativni materijal"},"supplied":{"en":["Synthetic preparation 46","Synthetic adjacent teeth","Synthetic antagonist","Editable broader-coverage Onlay"],"sr":["Sintetička preparacija 46","Sintetički susedni zubi","Sintetički antagonist","Onlay sa širom pokrivenošću koji se može menjati"]},"notes":{"en":"Coverage geometry is an educational visual distinction and does not imply automatic fit.","sr":"Geometrija pokrivenosti je edukativna vizuelna razlika i ne podrazumeva automatsko naleganje."}}'),
 ('veneer','synthetic_veneer_11','beginner','Anterior Veneer 11','Prednja faseta 11','Synthetic anterior veneer case with preparation, adjacent teeth, antagonist and reference form.','Sintetički slučaj prednje fasete sa preparacijom, susednim zubima, antagonistom i referentnim oblikom.','PT-TR-184','Anterior Veneer training case','Vežba za prednju fasetu',array[11]::smallint[],array['Inspect the anterior preparation and reference','Position the veneer shell','Review deviation, thickness and section'],array['Pregledajte prednju preparaciju i referencu','Pozicionirajte fasetnu ljuspicu','Pregledajte odstupanje, debljinu i presek'],'{"caseInitializer":"restorative","restorationType":"veneer","geometryProvenance":"internal-synthetic-educational","noPatientData":true,"materialPreset":"synthetic_training","material":{"en":"Synthetic educational preset","sr":"Sintetički edukativni materijal"},"supplied":{"en":["Synthetic preparation 11","Synthetic adjacent teeth","Synthetic antagonist","Editable anterior shell and reference"],"sr":["Sintetička preparacija 11","Sintetički susedni zubi","Sintetički antagonist","Prednja ljuska i referenca koje se mogu menjati"]},"notes":{"en":"This visual case is for education only and does not provide a clinical veneer preparation or thickness prescription.","sr":"Ovaj vizuelni slučaj služi samo edukaciji i ne daje klinički postupak preparacije fasete niti propis debljine."}}')
) seed(domain_slug,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,metadata)
join public.content_domains domain on domain.slug=seed.domain_slug
where not exists(select 1 from public.scenarios scenario where scenario.slug=seed.slug);

update public.practice_modules set status='published' where slug in ('bridge_workflow','inlay_onlay_workflow','veneer_workflow');
update public.practice_lessons set status='published' where slug in ('bridge_units','bridge_pontic_connectors','bridge_contacts_thickness','bridge_full_case','inlay_margin_insertion','inlay_contact_thickness','onlay_coverage_margin','onlay_design_review','veneer_preparation_reference','veneer_position_thickness');
