-- Phase 21 educational articulator curriculum and Free Lab scenario.
-- Motion uses stable upper/lower object roles and the shared CAD analysis worker.

insert into public.practice_modules(id,slug,title_en,title_sr,summary_en,summary_sr,sort_order,status)
values ('b7210000-0000-4000-8000-000000000001','virtual_articulator','Virtual Articulator','Virtual Articulator','Explore controlled educational jaw motion and sampled opposing-surface contact in the shared CAD workspace.','Istražite kontrolisane edukativne pokrete vilice i uzorkovani kontakt suprotnih površina u zajedničkom CAD radnom prostoru.',100,'published')
on conflict(slug) do update set title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,sort_order=excluded.sort_order,status='published';

insert into public.practice_lessons(id,module_id,slug,difficulty,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,estimated_minutes,case_setup,sort_order,status)
select v.id,m.id,v.slug,v.difficulty::public.difficulty_level,v.title_en,v.title_sr,v.summary_en,v.summary_sr,v.goal_en,v.goal_sr,v.minutes,jsonb_build_object('source','articulator-case','objectMappings','[]'::jsonb),v.sort_order,'published'
from (values
 ('b7210000-0000-4000-8000-000000000010'::uuid,'reference_and_hinge','beginner',10,'Reference Position and Hinge Axis','Referentni položaj i osa šarke','Set and reset the shared articulator reference position.','Podesite i vratite referentni položaj zajedničkog artikulatora.','Understand the fixed upper arch, moving lower arch and explicit hinge pivot.','Razumite fiksnu gornju vilicu, pokretnu donju vilicu i izričitu osu i tačku šarke.',8),
 ('b7210000-0000-4000-8000-000000000011'::uuid,'open_close_motion','beginner',20,'Open and Close Motion','Pokret otvaranja i zatvaranja','Preview reversible opening motion, return to reference, and inspect sampled contacts.','Prikažite reverzibilno otvaranje, vratite referencu i pregledajte uzorkovane kontakte.','Use the same canonical parameters for preview, reset and deterministic motion samples.','Koristite iste kanonske parametre za pregled, reset i determinističke uzorke pokreta.',10),
 ('b7210000-0000-4000-8000-000000000012'::uuid,'protrusive_motion','intermediate',30,'Protrusive Motion','Protruzivni pokret','Inspect a simplified anterior translation and analyze multiple sampled poses.','Pregledajte pojednostavljeno prednje pomeranje i analizirajte više uzorkovanih položaja.','Distinguish a simulated protrusive path from patient-specific mandibular motion.','Razlikujte simulirani protruzivni put od pokreta mandibule konkretnog pacijenta.',10),
 ('b7210000-0000-4000-8000-000000000013'::uuid,'lateral_excursion_and_splint','advanced',40,'Lateral Excursion and Bite Splint Review','Bočni pokret i pregled okluzalne udlage','Inspect left and right educational excursions against the supplied Phase 20 splint mesh.','Pregledajte edukativne leve i desne bočne pokrete u odnosu na postojeću mesh geometriju udlage iz Phase 20.','Review dynamic sampled contact on the real shared splint geometry without clinical claims.','Pregledajte uzorkovani kontakt kroz pokret na stvarnoj zajedničkoj geometriji udlage bez kliničkih tvrdnji.',12)
) v(id,slug,difficulty,sort_order,title_en,title_sr,summary_en,summary_sr,goal_en,goal_sr,minutes)
join public.practice_modules m on m.slug='virtual_articulator'
on conflict(slug) do update set module_id=excluded.module_id,difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,summary_en=excluded.summary_en,summary_sr=excluded.summary_sr,goal_en=excluded.goal_en,goal_sr=excluded.goal_sr,estimated_minutes=excluded.estimated_minutes,case_setup=excluded.case_setup,sort_order=excluded.sort_order,status='published';

insert into public.tool_definitions(id,category,label_en,label_sr,short_description_en,short_description_sr,explanation_en,explanation_sr,why_it_matters_en,why_it_matters_sr,status)
values ('articulator','occlusion','Virtual Articulator','Virtual Articulator','Preview controlled educational jaw motion.','Prikažite kontrolisani edukativni pokret vilice.','Moves the lower arch from canonical parameters around an explicit hinge pivot while the upper arch stays fixed.','Pomerajte donju vilicu prema kanonskim parametrima oko izričite tačke šarke dok gornja vilica ostaje fiksirana.','Motion preview and sampled contact can be inspected in one shared CAD workspace.','Pregled pokreta i uzorkovanog kontakta dostupni su u jednom zajedničkom CAD radnom prostoru.','published')
on conflict(id) do update set category=excluded.category,label_en=excluded.label_en,label_sr=excluded.label_sr,short_description_en=excluded.short_description_en,short_description_sr=excluded.short_description_sr,explanation_en=excluded.explanation_en,explanation_sr=excluded.explanation_sr,why_it_matters_en=excluded.why_it_matters_en,why_it_matters_sr=excluded.why_it_matters_sr,status='published';

create or replace function pg_temp.seed_phase21_step(p_lesson text,p_slug text,p_order int,p_title_en text,p_title_sr text,p_instructions_en text,p_instructions_sr text,p_theory_en text,p_theory_sr text,p_tools text[],p_targets text[],p_hint_en text,p_hint_sr text,p_validator jsonb default null)
returns void language plpgsql as $$
declare lesson_key uuid;step_key uuid;validator_id uuid;tool_id text;
begin
 select id into strict lesson_key from public.practice_lessons where slug=p_lesson;
 insert into public.practice_steps(lesson_id,slug,sort_order,title_en,title_sr,instructions_en,instructions_sr,theory_en,theory_sr,target_object_ids,reference_modes,reference_config,example_config,required)
 values(lesson_key,p_slug,p_order,p_title_en,p_title_sr,p_instructions_en,p_instructions_sr,p_theory_en,p_theory_sr,p_targets,array['off','outline','transparent','full'],null,jsonb_build_object('label_en','Reference position and fixed/moving arch example','label_sr','Primer referentnog položaja i fiksne/pokretne vilice','mode','outline'),true)
 on conflict(lesson_id,slug) do update set sort_order=excluded.sort_order,title_en=excluded.title_en,title_sr=excluded.title_sr,instructions_en=excluded.instructions_en,instructions_sr=excluded.instructions_sr,theory_en=excluded.theory_en,theory_sr=excluded.theory_sr,target_object_ids=excluded.target_object_ids,reference_modes=excluded.reference_modes,example_config=excluded.example_config,required=true returning id into step_key;
 delete from public.practice_step_tools where step_id=step_key;
 delete from public.practice_step_validations where step_id=step_key;
 delete from public.practice_hints where step_id=step_key;
 foreach tool_id in array p_tools loop insert into public.practice_step_tools(step_id,tool_id) values(step_key,tool_id) on conflict do nothing; end loop;
 insert into public.practice_hints(step_id,slug,sort_order,title_en,title_sr,body_en,body_sr) values(step_key,'review-model',10,'Check the model','Proverite model',p_hint_en,p_hint_sr);
 if p_validator is not null then
  insert into public.validation_configs(slug,validator_type,config,status) values('phase21_'||p_lesson||'_'||p_slug,'custom'::public.validator_type,p_validator,'published') on conflict(slug) do update set validator_type='custom'::public.validator_type,config=excluded.config,status='published' returning id into validator_id;
  insert into public.practice_step_validations(step_id,validation_config_id,sort_order) values(step_key,validator_id,10);
 end if;
end $$;

select pg_temp.seed_phase21_step('reference_and_hinge','identify_arches',10,'Identify fixed and moving arches','Prepoznajte fiksnu i pokretnu vilicu','Use the panel labels to confirm that the upper arch remains fixed and the lower arch moves. Inspect the stated X/Y/Z axes and hinge pivot.','Proverite oznake u panelu: gornja vilica ostaje fiksna, a donja se pomera. Pregledajte navedene X/Y/Z ose i tačku šarke.','The workspace uses millimetres, a right-handed frame, X left/right, Y anterior/posterior and Z superior/inferior. Positive X is left; positive Y is anterior.','Radni prostor koristi milimetre i desnoruki sistem: X levo/desno, Y napred/nazad i Z gore/dole. Pozitivni X je levo, a pozitivni Y napred.',array['select','camera','scene','articulator'],array['bite-splint-synthetic-upper','bite-splint-synthetic-antagonist'],'The lower arch is evaluated from the reference pose; source mesh vertices remain unchanged.','Donja vilica se računa iz referentnog položaja; temena izvorne mreže ostaju nepromenjena.',null);
select pg_temp.seed_phase21_step('reference_and_hinge','return_to_reference',20,'Return to the reference position','Vratite referentni položaj','Move the slider, then choose Reset reference and confirm the lower arch returns to the same start pose.','Pomerite klizač, izaberite Reset reference i proverite da se donja vilica vraća u isti početni položaj.','Reset evaluates the canonical motion parameter at zero; it does not reverse accumulated mesh edits.','Reset ponovo računa kanonski parametar pokreta na nuli; ne vraća niti menja geometriju mreže.',array['articulator','camera'],array['bite-splint-synthetic-antagonist'],'Reset returns to the captured exercise reference without applying frame-by-frame deltas.','Reset vraća vežbu na referentni položaj bez uzastopnog dodavanja pomeraja.',null);
select pg_temp.seed_phase21_step('open_close_motion','preview_open_close',10,'Preview opening and closing','Prikažite otvaranje i zatvaranje','Choose Open / Close, play or scrub the timeline, pause, and reset to the reference position.','Izaberite Open / Close, pustite ili pomerajte vremensku liniju, pauzirajte i vratite referentni položaj.','This is a simplified educational hinge around an explicit X axis and pivot. Its exercise settings are not physiological constants.','Ovo je pojednostavljena edukativna šarka oko izričite X ose i tačke oslonca. Podešavanja vežbe nisu fiziološke konstante.',array['articulator','camera'],array['bite-splint-synthetic-antagonist'],'The upper arch stays fixed. Opening rotates only the lower arch around the configured pivot.','Gornja vilica ostaje fiksna. Pri otvaranju se donja vilica rotira oko podešene tačke šarke.',null);
select pg_temp.seed_phase21_step('open_close_motion','sampled_contact',20,'Analyze the sampled opening path','Analizirajte uzorkovani put otvaranja','Run Analyze motion. Review the per-pose contact states and first sampled contact, then change the threshold and analyze again.','Pokrenite Analyze motion. Pregledajte stanje kontakta u svakom položaju i prvi uzorkovani kontakt, zatim promenite prag i ponovite analizu.','Dynamic contact here means deterministic multi-pose proximity sampling. First contact is the first detected sample, not a continuous collision time.','Dinamički kontakt ovde znači determinističku analizu blizine kroz više položaja. Prvi kontakt je prvi uzorak sa kontaktom, a ne tačno vreme sudara.',array['articulator','analysis','camera'],array['bite-splint-synthetic-upper','bite-splint-synthetic-antagonist'],'A threshold contact and a surface intersection are reported as distinct states.','Kontakt unutar praga i presek površina prikazuju se kao različita stanja.',jsonb_build_object('type','analysis_target','kind','dynamic_contact','objectIds',jsonb_build_array('bite-splint-synthetic-upper','bite-splint-synthetic-antagonist')));
select pg_temp.seed_phase21_step('protrusive_motion','preview_protrusion',10,'Preview protrusive motion','Prikažite protruzivni pokret','Choose Protrusive, scrub from the reference position to the end of the configured exercise path, and reset.','Izaberite Protrusive, pomerajte klizač od reference do kraja podešenog puta vežbe i resetujte položaj.','This phase uses a reversible anterior translation in canonical +Y. It does not model patient-specific condylar movement.','Ova faza koristi reverzibilno prednje pomeranje duž kanonske +Y ose. Ne modeluje pokret kondila konkretnog pacijenta.',array['articulator','camera'],array['bite-splint-synthetic-antagonist'],'The displayed travel is an exercise configuration only, not a universal clinical target.','Prikazani pomeraj je samo podešavanje vežbe, a ne univerzalni klinički cilj.',null);
select pg_temp.seed_phase21_step('protrusive_motion','analyze_protrusion',20,'Analyze protrusive samples','Analizirajte protruzivne uzorke','Run Analyze motion for the Protrusive path and inspect the separation/contact states at several samples.','Pokrenite Analyze motion za protruzivni put i pregledajte razdvajanje i kontakt u više uzoraka.','The upper mesh is fixed and the same lower object IDs are tested at every deterministic sample.','Gornja mreža je fiksna, a isti ID-jevi donje vilice proveravaju se u svakom determinističkom uzorku.',array['articulator','analysis'],array['bite-splint-synthetic-upper','bite-splint-synthetic-antagonist'],'Change a relevant transform or exercise parameter and the previous result becomes stale.','Promenite relevantnu transformaciju ili podešavanje vežbe i prethodni rezultat postaće zastareo.',jsonb_build_object('type','analysis_target','kind','dynamic_contact','objectIds',jsonb_build_array('bite-splint-synthetic-upper','bite-splint-synthetic-antagonist')));
select pg_temp.seed_phase21_step('lateral_excursion_and_splint','inspect_lateral_excursions',10,'Inspect left and right lateral excursions','Pregledajte leve i desne bočne pokrete','Switch between Left lateral and Right lateral. Confirm that X translation reverses direction and reset after each preview.','Prebacite se između Left lateral i Right lateral. Proverite da se smer pomeranja X ose menja i resetujte posle svakog pregleda.','In Prostheia coordinates positive X is left and negative X is right. This is a simplified translation exercise.','U Prostheia koordinatama pozitivan X je levo, a negativan X desno. Ovo je pojednostavljena vežba pomeranja.',array['articulator','camera'],array['bite-splint-synthetic-antagonist'],'The actual generated Phase 20 splint stays attached to the fixed upper arch.','Stvarna generisana udlaga iz Phase 20 ostaje vezana za fiksnu gornju vilicu.',null);
select pg_temp.seed_phase21_step('lateral_excursion_and_splint','dynamic_splint_capstone',20,'Review the splint through motion','Pregledajte udlagu kroz pokret','Run a dynamic sampled contact analysis for one lateral path and identify the first sampled contact or confirm no contact was found.','Pokrenite analizu uzorkovanog kontakta kroz jedan bočni put i odredite prvi uzorkovani kontakt ili potvrdite da kontakt nije pronađen.','The existing splint mesh and the shared contact worker are reused. Results describe this configured synthetic exercise only.','Koriste se postojeća mesh geometrija udlage i zajednički radnik za kontakt. Rezultati opisuju samo ovo podešeno sintetičko okruženje.',array['articulator','analysis','camera'],array['bite-splint-generated','bite-splint-synthetic-antagonist'],'The contact path is sampled. It is not clinical occlusal diagnosis or manufacturing approval.','Put kontakta se uzorkuje. Ovo nije klinička dijagnoza okluzije niti odobrenje za izradu.',jsonb_build_object('type','analysis_target','kind','dynamic_contact','objectIds',jsonb_build_array('bite-splint-generated','bite-splint-synthetic-antagonist')));

insert into public.scenarios(domain_id,slug,difficulty,title_en,title_sr,description_en,description_sr,patient_code,indication_en,indication_sr,tooth_numbers,requirements_en,requirements_sr,additional_metadata,random_eligible,status,published_at)
select d.id,'synthetic_virtual_articulator_splint','intermediate','Virtual Articulator · bite splint','Virtual Articulator · okluzalna udlaga','Independently inspect a generated synthetic splint against an antagonist through educational jaw motion.','Samostalno pregledajte generisanu sintetičku udlagu u odnosu na antagonist kroz edukativni pokret vilice.','PT-VA-21','Educational dynamic occlusion inspection','Edukativni pregled dinamičke okluzije',array[]::smallint[],array['Preview opening, protrusive and lateral motion','Analyze sampled opposing contact','Review the generated synthetic bite splint'],array['Prikažite otvaranje, protruzivni i bočni pokret','Analizirajte uzorkovani kontakt suprotnih površina','Pregledajte generisanu sintetičku okluzalnu udlagu'],jsonb_build_object('caseInitializer','articulator','geometryProvenance','internal-synthetic-educational','noPatientData',true,'materialPreset','educational-splint','material',jsonb_build_object('en','Synthetic educational geometry','sr','Sintetička edukativna geometrija'),'supplied',jsonb_build_object('en',jsonb_build_array('Synthetic upper arch','Synthetic lower antagonist','Generated bite splint'),'sr',jsonb_build_array('Sintetička gornja vilica','Sintetički donji antagonist','Generisana okluzalna udlaga')),'notes',jsonb_build_object('en','Educational kinematic simulation only. Not patient-specific, clinically validated, or approved for manufacturing.','sr','Samo edukativna kinematička simulacija. Nije prilagođena pacijentu, klinički validirana niti odobrena za izradu.')),true,'published',now()
from public.content_domains d where d.slug='bite_splint'
on conflict(slug) do update set difficulty=excluded.difficulty,title_en=excluded.title_en,title_sr=excluded.title_sr,description_en=excluded.description_en,description_sr=excluded.description_sr,patient_code=excluded.patient_code,indication_en=excluded.indication_en,indication_sr=excluded.indication_sr,tooth_numbers=excluded.tooth_numbers,requirements_en=excluded.requirements_en,requirements_sr=excluded.requirements_sr,additional_metadata=excluded.additional_metadata,random_eligible=true,status='published',published_at=coalesce(public.scenarios.published_at,now());

-- The default scenario browser seeds known tools from this registry and keeps content editable in Admin.
insert into public.tool_object_roles(tool_id,object_role)
select 'articulator',role from (values('maxilla'::public.cad_object_role),('mandible'::public.cad_object_role),('antagonist'::public.cad_object_role),('splint'::public.cad_object_role)) roles(role)
on conflict do nothing;
